Workday/canvas-kit

.storybook/config.js

When t he addon `storybook-readme` was updated from `5.0.2` to `5.0.5`, there was a regression where `github` was no longer the default `codeTheme` and code would not be highlighted correctly unless this was explicitly specified in Storybook's config.
An issue has been raised here: https://github.com/tuchk4/storybook-readme/issues/186
Instead of rolling back and locking `storybook-readme` at `5.0.2`, it was fairly trivial to specify a theme explicitly.

Specify theme in storybook config

---

modules/_canvas-kit-react/index.ts
modules/cookie-banner/react/lib/CookieBanner.tsx

Original PR: #22 
`Banner` was not exported from the `canvas-kit` universal module. Adding it required removing conflicting types in `CookieBanner`.
This *could* be a breaking change if anyone relies on `BannerProps` exported by `@workday/canvas-kit-react` OR `@workday/canvas-kit-react-cookie-banner`. `BannerProps` from `@workday/canvas-kit-react` will now by pointing to `BannerProps` from `@workday/canvas-kit-banner` and `@workday/canvas-kit-react-cookie-banner` will no longer export `BannerProps`
applicable

fix: Added Banner to @workday/canvas-kit-react

---

.npmrc
.travis.yml
.yarnrc
package.json
utils/check-lockfile-links.js

Original PR: #11 
* Added lint check for Artifactory paths
* Added linting to travis CI
* Added `frozen-lockfile` option to installs to prevent accidental yarn.lock file overriding
applicable

chore: Add lint check for Artifactory paths

---

.prettierignore
.travis.yml

Opening the repo and moving from travis-ci.com to travis-ci.org changed the travis key for the repo. The variables used for the build had to be re-added. 
Running the command to add the variables to the travis file also changed the indentation, I'm going to leave it like this since the Travis CLI will keep changing it.

build(travis): regenerate build vars

---

modules/form-field/react/stories/stories_Checkbox.tsx
modules/form-field/react/stories/stories_ColorInput.tsx
modules/form-field/react/stories/stories_ColorPreview.tsx
modules/form-field/react/stories/stories_Radio.tsx
modules/form-field/react/stories/stories_Select.tsx
modules/form-field/react/stories/stories_TextArea.tsx
modules/form-field/react/stories/stories_TextInput.tsx

Previously, all of the READMEs in form-field for input modules (Checkbox, Select, Text Input, etc.) were pointed to Form Field's READMEs.
Now, for each input module's story, they point to their respective module's README instead. E.g. the `Form Field/Checkbox/...` stories point to this: `modules/checkbox/react/README.md`.

Update READMEs in form-field

---

README.md

Our travis build badge in the readme was pointing to `.com` from before we open sourced. Just needed to update to `.org`

fix(readme): Point readme build badge to correct URL

---

modules/page-header/react/README.md
modules/page-header/react/lib/PageHeader.tsx
modules/page-header/react/spec/PageHeader.spec.tsx
modules/page-header/react/stories/stories.tsx

Update `PageHeader` to use `IconButtons` instead of `SystemIcons` wrapped in links. The original implementation was a temporary solution when we didn't have `IconButtons` implemented.
References https://github.com/Workday/canvas-kit/pull/13
applicable

refactor(page-header): Update PageHeader to support IconButton

---

modules/_canvas-kit-react/README.md
modules/_canvas-kit-react/index.ts

The fonts module should be opt-in so consumers can choose whether or not they consume things from our CDN (it's the only module that pulls directly from that URL). Currently it's being exported by default from @workday/canvas-kit-react and it should not be.
Closes https://github.com/Workday/canvas-kit/issues/38

Fix fonts module export

---

modules/common/react/package.json
modules/header/react/package.json
modules/side-panel/react/package.json
package.json
yarn.lock

Versions of lodash before 4.17.12 are vulnerable to Prototype Pollution. The function defaultsDeep allows a malicious user to modify the prototype of Object via {constructor: {prototype: {...}}} causing the addition or modification of an existing property that will exist on all objects.
https://www.npmjs.com/advisories/1065

fix: Update lodash version to fix vulnerability

---

modules/common/react/README.md
modules/common/react/lib/Popper.tsx
modules/common/react/spec/Popper.spec.tsx

A request was made to be able to support adding a z-index to the wrapping div. This was solved generically using the styled components pattern to spread remainder props on the top-level element.
[style guide](https://ghe.megaleo.com/UIC/wd-components/blob/master/docs/STYLEGUIDE.md)

fix(Popper): Spread remainder props on wrapper div

---

modules/menu/react/README.md
modules/menu/react/lib/Menu.tsx
modules/menu/react/lib/MenuItem.tsx
modules/menu/react/spec/Menu.spec.tsx

The menu always fires the onClose event at the end of the onClick event (if onClose is provided). 
This change gives each menu item the ability to to skip the onClose event from firing, giving the menu more flexibility.
In our use case, a menu item has the ability to replace the contents of the menu with different menu items when it is clicked. This is difficult to do, because `onClose` will always fire. We were previously handling this by maintaining state in our application to determine if the `onClose` callback was actually supposed to close the menu.

feat(menu): Menu Item can skip onClose

---

modules/header/react/lib/Header.tsx
modules/header/react/lib/parts/Search.tsx
modules/header/react/spec/Search.spec.tsx
modules/header/react/spec/__snapshots__/GlobalHeader.snapshot.tsx.snap
modules/header/react/spec/__snapshots__/Header.snapshot.tsx.snap
modules/header/react/spec/__snapshots__/Search.snapshot.tsx.snap

Closes https://github.com/Workday/canvas-kit/issues/42
Extra html attributes sent to header no longer spread to multiple elements.
Magnifying glass icon is now to clickable to submit search
Search clear button (x) is now accessible via keyboard controls
applicable

fix(header): Header Search Accessibility & Prop Spread Fixes

---

.travis.yml

We need to skip the cleanup phase for Travis since we rely on the artifacts generated from the `install` phase to release.
This PR also tags every publish as prerelease. This models how Lerna does it for us today. We currently need to manually push `latest` as a dist-tag since we have no official `latest` version. 
We'll eventually need to change this up and write a script that pushes the appropriate dist tags during a publish.

build(travis): skip cleanup on npm publish

---

.travis.yml
CHANGELOG.md

In Travis Git tags are considered a "branch". This fixes the conditional to run `npm publish` on a particular tag format:
`/^v\d+\.\d+(\.\d+)?(-\S*)?$/`
This has been tested by:
```sh
travis-conditions eval "branch =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/ AND tag IS present" --data '{"branch": "v3.0.0-alpha.4", "tag": "v3.0.0-alpha.4"}'
```
applicable

ci(travis): fix npm publish conditional

---

modules/tooltip/css/lib/tooltip.scss
modules/tooltip/css/lib/variables.scss

This PR updates the Tooltip CSS styles so they match the React component. 
| Breaking Changes | Yes    | Yes   |
Note : The story doesn't perfectly match the React one because it relies on a Button style that doesn't exists yet in CSS. It will be added to the `css-update` later and we'll update the story of `Tooltip CSS` after that.
**Visual:**
- Updated styling to match React implementation. No longer includes an arrow since the origin of the tooltip should be obvious when your mouse is on it (there's also an animation that helps).
**Code:**
- Removed `wdc-tooltip-menu` implementation. This is moving to the Popup module
- Removed tooltip max width
- Removed a large majority of the tooltip variables as they are no …

refactor(Tooltip): Update CSS styles to match React implementation

---

.storybook/config.js
package.json
yarn.lock

We had several console warnings appearing in Storybook after recent updates. This remedies most of them.
There is still a warning appearing for the use of `:first-child`. This is an upstream issue and is being tracked [here](https://github.com/storybookjs/storybook/issues/6998) and [here](https://github.com/emotion-js/emotion/issues/1105).
Before:
After:

chore(storybook): Fix console warnings

---

modules/avatar/react/lib/Avatar.tsx
modules/avatar/react/spec/__snapshots__/Avatar.snapshot.tsx.snap
modules/header/react/spec/__snapshots__/GlobalHeader.snapshot.tsx.snap

We never removed the background when we replaced the `SystemIcon` with `SystemIconCircle`. If the user passes the theme of Blue with an image, they get a flash of blue while the image loads (see https://ghe.megaleo.com/design/canvas-kit-react/issues/470). This change always uses our standard `Skeleton` background color (`soap200`) while the image is loading if `url` is defined.
Closes https://ghe.megaleo.com/design/canvas-kit-react/issues/470

fix(avatar): Update background color when url is defined

---

modules/header/react/stories/stories.tsx

@jessespencer noticed there were some duplicate icons in the header stories. These were due to incorrect rebase merges. This PR removes the duplicates.
Before:
After:

fix(header): Remove duplicate icon buttons

---

modules/layout/react/lib/Layout.tsx
modules/layout/react/spec/Layout.snapshot.tsx
modules/layout/react/spec/__snapshots__/Layout.snapshot.tsx.snap

There was a type error happening when a child of `Layout` returned null. It should be possible to have conditional columns, so this change makes that possible.
Closes https://github.com/Workday/canvas-kit/issues/84

fix(Layout): Add check for null children

---

modules/form-field/react/README.md
modules/form-field/react/lib/FormField.tsx
modules/form-field/react/lib/Label.tsx
modules/form-field/react/lib/types.ts
modules/form-field/react/spec/FormField.spec.tsx

This PR updates exports `FormField` enums/interfaces to match our API & Pattern guidelines to avoid naming clashes in the future.
| Breaking Changes | No    | Yes   |
- Updated `LabelPosition` to `FormFieldLabelPosition`
- Updated `LabelPositionBehavior` to `FormFieldLabelPositionBehavior`
- Updated `ErrorBehavior` to `FormFieldErrorBehavior`
Closes #100
applicable

fix(FormField): Add component prefix to exported enums and interfaces

---

.storybook/config.js
modules/avatar/react/stories/stories.tsx
modules/core/react/README.md
modules/core/react/stories/stories.tsx
modules/form-field/react/stories/stories_Checkbox.tsx
modules/form-field/react/stories/stories_ColorInput.tsx
modules/form-field/react/stories/stories_ColorPreview.tsx
modules/form-field/react/stories/stories_Radio.tsx
modules/form-field/react/stories/stories_Select.tsx
modules/form-field/react/stories/stories_TextArea.tsx
modules/form-field/react/stories/stories_TextInput.tsx
modules/menu/react/stories/stories.tsx
modules/side-panel/react/stories/stories.tsx

We're adding `inputProviderDecorator` to the Storybook configuration file instead of adding it every time we need it. This makes sure we can properly style form inputs using `data-whatinput` in both React and CSS.

refactor: Move InputProviderDecorators to Storybook config

---

modules/status-indicator/react/lib/StatusIndicator.tsx

We were missing exports for the type and emphasis enums on `StatusIndicator`. This change names them correctly and exports them.
Closes https://github.com/Workday/canvas-kit/issues/165.

fix(status-indicator): Export type and emphasis enums

---

modules/layout/css/README.md
modules/layout/css/index.scss
modules/layout/css/lib/layout.scss
modules/layout/css/lib/variables.scss
modules/layout/css/package.json
modules/layout/css/stories.tsx

This PR updates the Layout (formerly known as Grid) CSS styles so they match the React component. 
| Breaking Changes | No    | Yes   |
- `lib/grid-system.scss` moved to `lib/layout.scss`
- `$wdc-grid-system-breakpoints` > `$wdc-layout-breakpoints`
- `$wdc-grid-system-columns` > `$wdc-layout-columns`
refactor(layout): Update CSS styles to match React implementation (#168)

refactor(layout): Update CSS naming to match React implementation

---

modules/table/react/README.md
modules/table/react/lib/TableRow.tsx
modules/table/react/spec/TableRow.snapshot.tsx
modules/table/react/spec/__snapshots__/TableRow.snapshot.tsx.snap

This addresses #170 
Changes include:
- Updated exports `TableRowStates` to `TableRowState`
- Using `StatusColors` for error and alert colors. This includes a breaking change: Error color is now changed updated `cinnamon500` from `cinnamon400`
| Breaking Changes | Visual | Code |
|--------------------|-------|------|
| | Yes| Yes|

refactor(table): TableRow API update and cleanup

---

package.json
yarn.lock

This fixes a security vulnerability in the transitive dependency lodash.merge 4.6.1

chore: Bump jest-axe from 3.1.1 to 3.2.0

---

.storybook/config.js
cypress/helpers/index.ts
cypress/helpers/stories.ts
cypress/integration/Button.spec.ts
package.json

Added `window.setCurrentStory(story: string, variation: string)` to enable faster (re)loading of Storybook stories. The `story` parameter matches the string inside `storiesOf` and the `variation` matches the string inside the `.add` function
Use (in browser's console):
```ts
setCurrentStory('button', 'primary')
```
<details>
<summary>Animated GIF. Warning! Tests are fast and flash rapidly!</summary>
</details>

feat: Add faster testing of stories in Cypress

---

modules/avatar/react/README.md
modules/avatar/react/lib/Avatar.tsx
modules/avatar/react/spec/Avatar.snapshot.tsx
modules/avatar/react/stories/stories.tsx

This is part of the API changes ongoing work https://github.com/Workday/canvas-kit/issues/51, we want to rename the `themeColor` prop to `variant`.
- `AvatarTheme` changed to `AvatarVariant`
- `Avatar`'s `themeColor` prop renamed to `variant`
refactor(avatar): Change themeColor to AvatarVariant (#194)

refactor(avatar): Change themeColor to variant

---

modules/banner/react/README.md
modules/banner/react/index.ts
modules/banner/react/lib/Banner.tsx
modules/banner/react/lib/types.tsx
modules/banner/react/spec/Banner.snapshot.tsx
modules/banner/react/stories/stories.tsx

This is part of the API changes ongoing work https://github.com/Workday/canvas-kit/issues/51, we want to rename the `BannerTheme ` prop to `BannerErrorType `.
- `BannerTheme` removed. We're now using `ErrorType` from `@workday/canvas-kit-react-common`
- Banner `theme` prop renamed to `error`
refactor(banner): Change BannerTheme to BannerErrorType (#195)

refactor(banner): Change BannerTheme to ErrorType

---

modules/tooltip/css/stories.tsx

This PR doesn't have any breaking changes. It updates the story of CSS `Tooltip` to match the story of React `Tooltip`, now that we have CSS `Button`.
refactor(tooltip): Update story (#198)

refactor(tooltip): Update CSS story to match the React version

---

modules/core/react/index.ts
modules/core/react/lib/colors.types.ts
modules/core/react/lib/spacing.ts
modules/icon/react/README.md
modules/icon/react/lib/AppletIcon.tsx

This is part of the API changes ongoing work https://github.com/Workday/canvas-kit/issues/51, we want to rename enums to singular
- Rename `CanvasSpacingNumbers` -> `CanvasSpacingNumber`
- Rename `BrandingColors` to `BrandingColor`

refactor(core): Rename enums to singular

---

modules/form-field/react/stories/stories_Switch.tsx
modules/switch/react/README.md

This is part of the API changes ongoing work https://github.com/Workday/canvas-kit/issues/51, we want to add a11y messaging in `switch`'s Readme 
docs(switch): Add a11y messaging in Readme and move story location (#197)

refactor(switch): Add a11y messaging in Readme and move story location

---

modules/common/css/lib/errors.scss

We're updating `text-input` React (#218) so this PR is to make sure the CSS matches these changes
- Error and alert icons are not longer displayed inside `text-input` components
refactor(text-input): Remove error icon in CSS (#222)

refactor(text-input): Remove error icon in CSS

---

modules/card/css/README.md
modules/card/css/lib/card.scss
modules/card/css/stories.tsx
modules/card/react/lib/Card.tsx
modules/card/react/spec/__snapshots__/Card.snapshot.tsx.snap
modules/modal/css/README.md
modules/modal/css/stories.tsx
modules/modal/react/lib/Modal.tsx
modules/popup/css/README.md
modules/popup/css/lib/popup.scss
modules/popup/css/stories.tsx
modules/popup/react/lib/Popup.tsx

I found a few issues with Cards, Popups and Modals. The heading margin issue was noted in our recent design review.
- All of their headings where the same, but named different things. Now we support `*-heading`, `*-header`, and `*-title` to be flexible.
- Card headings had the browser default margin top which was adding extra space to popups and modals as well
- `PopupProps` were missing their div attribute interface extension
- Margin top on card headers removed which changes the height of the card. Could cause reflow issues
applicable

fix: Card, Popup and Modal cleanup

---

.github/workflows/ci.yml
cypress.json

We're evaluating Github Actions. The PR adds common CI tasks already covered by Travis, but also adds Cypress tests and uploads to the Cypress dashboard. Cypress runs can be found here: https://dashboard.cypress.io/#/projects/odida5/runs
It doesn't look like Github Actions runs if created from a fork. Here is an example of it working inside my fork: https://github.com/NicholasBoll/canvas-kit/pull/1. Screenshot below:

ci: Create github action for CI and add Cypress to CI

---

.github/workflows/chromaticqa.yml
.github/workflows/chromaticqa_master.yml
.storybook/config.js
package.json
yarn.lock

ChromaticQA will help us keep track of visual changes requiring approval for visual diffs. According to the documentation, multiple baselines should be supported. That should include `master` (the main baseline) and any visual diffs detected in pull request branches. I'm not sure how well this baselining will work. I was surprised it wasn't based on the name of a branch - we shall see how well it works.
There are 2 new jobs - one for pull requests and one for master. Master auto-accepts changes to the baseline because we only allow changes to be approved through pull requests.
https://www.chromaticqa.com/builds?appId=5d854c26ba934e0020f5e98a

ci: Add ChromaticQA to CI

---

.travis.yml

Github Actions is covering the `testing` portion of TravisCI, only faster. Let's remove it.

ci: Remove Travis from pull requests

---

modules/skeleton/react/lib/skeleton.tsx
modules/skeleton/react/spec/__snapshots__/skeleton.snapshot.tsx.snap

Fixes #253 
Currently the Skeleton clobbers the z-index of most elements on the page sitting at 999, this was leftover from a previous implementation that is no longer valid. Unlike what #253 specifies this PR removes the z-index altogether. It was just left in there by mistake.
applicable

fix(skeleton): Remove z-index

---

modules/layout/react/lib/Column.tsx
modules/layout/react/lib/Layout.tsx

This will prevent `spacing` from being rendered in the dom.
applicable

fix(layout): Remove spacing prop from DOM

---

.github/workflows/chromaticqa.yml
modules/button/react/stories/stories.tsx
package.json
yarn.lock

According to my conversation with the ChromaticQA team, our baseline issue should be partially addressed by updating to the latest version of `storybook-chromatic`. The team is currently working on a Github action: https://github.com/chromaui/action (currently in beta).
Here's what the baselines now look like:
Before:
```
7f607b on master
```
After:
```
7f607b on chore/update-chromaticqa
```
Before all PRs used the `master` baseline which was a problem where each CI run against a PR potentially rebaselined another PR. Now we're able to send the baseline explicitly. I've tested this against this PR and another PR to make sure the baselines did not interfere with each other and it doesn't look like they do anymore.
```
ci: Update ChromaticQA for better baselines (#269)
```

ci: Update ChromaticQA for better baselines

---

modules/checkbox/react/README.md
modules/checkbox/react/lib/Checkbox.tsx
modules/form-field/react/stories/stories_Checkbox.tsx

Checkboxes can have an indeterminate state in a nested checkbox context. If the "parent" checkbox has some, but not all, child checkboxes selected, that checkbox is considered indeterminate or otherwise known as "partially selected". 
More information here: https://css-tricks.com/indeterminate-checkboxes/

fix(checkbox): Added an indeterminate checkbox type

---

modules/button/react/lib/utils.ts

It does what it says! This takes advantage of `InputProvider` to hide the focus styling when using a mouse and showing it when keyboard navigation begins. This is added to all buttons (including the deprecated ones).
Depends on #276. Blocked until that is merged.

feat(button): Utilize InputProvider for mouse input focus

---

modules/_labs/core/react/package.json

Somehow an Emotion 9 dep snuck in (must have been a bad rebase). This fixes it.

fix(labs): Update incorrect emotion version in labs core

---

modules/avatar/react/package.json
modules/button/react/package.json
modules/icon/react/package.json
modules/layout/react/package.json
package.json

The `@emotion/is-prop-valid` dependency was mistakenly added to the workspace package.json rather than the components' that explicitly need it. This causes "Module not found" errors when using the reference outside of the Canvas Kit repo. This PR removes the workspace dep (it's not needed there), and adds it to the components that use `isValidProp`.

fix: Lower is-prop-valid dep into components that need it

---

modules/side-panel/react/lib/SidePanel.tsx

Fixes: https://github.com/Workday/canvas-kit/issues/303

fix(side-panel): Change width of children container when closed

---

modules/_canvas-kit-css/README.md
modules/core/css/lib/variables/colors.scss
modules/core/css/lib/variables/depth.scss

There were two files that were inconsistently importing sass files. This fixes it and clarifies usage in the top level README.

fix: Add missing tilde on SASS imports (#307)

---

modules/common/css/README.md
modules/common/css/lib/accessibility.scss
modules/common/react/lib/styles/accessibleHide.ts

Code to make text screen reader only was added to JS common repo but was not mirrored in the css. This adds a new class to the common css
This PR also changes Change word-wrap: normal to white-space, see:
https://medium.com/@jessebeach/beware-smushed-off-screen-accessible-text-5952a4c2cbfe

fix(common): Port accessible hide styles from JS to CSS

---

.travis.yml

By default the ChromaticQA CLI doesn't exit a `0` on changes. We use the Github integration, so we want to exit `0` even with changes so the TravisCI check passes. Chromatic then adds an additional check that is attached to approvals.

ci: Exit 0 on ChromaticQA changes

---

modules/_canvas-kit-css/index.scss
modules/_canvas-kit-css/package.json

Fixes #309.
We forgot to add the individual form field modules to the `canvas-kit-css` universal module back when we split `canvas-kit-css-form` into separate modules for each form field (#24). Whoops. This fixes that.
applicable

fix: Add missing dependencies to CKCSS universal module

---

modules/side-panel/react/lib/SidePanel.tsx

Fixes: https://github.com/Workday/canvas-kit/issues/320
We were forcing aria attributes so the side panel and it wasn't accessible. We still kept the role as default, but removed `aria-orientation`. The consumer can now pass any other aria attribute if they need to override anything.

fix(side-panel): Add flexibility for aria attributes

---

modules/_labs/menu/react/lib/Menu.tsx

fix: Change React dependency import for Menu to fix type declarations for consumers.
React was being imported the more ES6-y way, rather than the TypeScript method. This causes some linters and IDEs to not resolve the depedency correctly, and therefore not see the Menu as a valid react component.

feat(menu): Fix import of React dependency.

---

modules/common/css/lib/accessibility.scss
modules/form-field/css/README.md

fix: bad quote marks on accessible hide CSS (#343)

---

.prettierrc.js
COMPONENT_STATUS.md
eslintrc.js
lerna.json
modules/_canvas-kit-css/README.md
modules/_canvas-kit-react/README.md
modules/_labs/combobox/react/README.md
modules/_labs/combobox/react/tsconfig.json
modules/_labs/drawer/react/tsconfig.cjs.json
modules/_labs/drawer/react/tsconfig.es6.json
modules/_labs/drawer/react/tsconfig.json
modules/_labs/header/react/README.md
modules/checkbox/react/README.md
modules/form-field/css/README.md
package.json
wallaby.js

The `format:pretty` command would fail because we were pointing to a `.prettierrc` file but we actually store the prettier configurations in `.prettierrc.js`. I also updated the file path in the `eslintrc.js`.
I then ran the command to update any files that needed formatting.

chore: Use proper prettier file in configs

---

modules/button/css/stories.tsx

This updates the IA for `Buttons/Button/CSS/Depracated`. It currently is in the `Others` category on storybook.
applicable

docs: Update incorrect story category for deprecated CSS buttons

---

modules/text-input/react/lib/TextInput.tsx

Typing the ref as `React.Ref` instead of `React.RefObject` allows the prop to also accept [callback refs](https://reactjs.org/docs/refs-and-the-dom.html#callback-refs).
Example use:
[![Edit fancy-sea-ryh19](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fancy-sea-ryh19?fontsize=14&hidenavigation=1&theme=dark)

fix(text-input): Update type of inputRef

---

modules/_labs/core/react/index.ts
modules/_labs/core/react/lib/CanvasProvider.tsx
modules/_labs/core/react/lib/theming/README.md
modules/_labs/core/react/lib/theming/createCanvasTheme.ts
modules/_labs/core/react/lib/theming/index.ts
modules/_labs/core/react/lib/theming/styled.ts
modules/_labs/core/react/lib/theming/theme.ts
modules/_labs/core/react/lib/theming/useTheme.ts
modules/_labs/core/react/spec/breakpoints.spec.tsx
modules/_labs/core/react/spec/createCanvasTheme.spec.tsx
modules/_labs/core/react/spec/useTheme.spec.tsx
modules/_labs/core/react/stories/stories_theme.tsx

There were two issues with #272:
- During review, we switched from using `deepmerge` to `lodash/merge`. I didn't realize at the time that `lodash/merge` mutates the object it's returning, so we were updating the `defaultCanvasTheme` unintentionally
- I tried using our own `ThemeProvider` to mitigate an issue with `@storybook/addon-knobs`. After realizing this wasn't causing the problem with the addon, I left it as is. However, there is an issue with this in conjunction with our custom `styled` function and how React hooks work. Since we expect `theme` to be passed to `useTheme` through `styled` from Emotion (since we can't use `useContext` within class components), we _do_ need to use Emotion's `ThemeContext`. This is because Emotion is calling our interpolations and passing the theme …

fix(labs): Fix theming implementation

---

modules/form-field/css/stories/stories_TextInput.tsx

This updates the IA for Inputs/Text Input/CSS/Left Label. Previously, it was incorrectly categorized under `TextInput` (without the space).
applicable

docs: Update incorrect story category for CSS Text Input

---

cypress/support/commands.ts
modules/modal/react/lib/ModalContent.tsx

Tests are failing on CI, but not locally. I'm making a PR to see what it takes to fix on the CI.
There is some strange issue where the "tab" key is hit before the event listener is added. There are some issues on `cypress-tab-plugin` that causes errors. On investigating, I discovered this issue: https://github.com/Bkucera/cypress-plugin-tab/issues/13

test: Fix modal specs

---

cypress/integration/storybook.spec.ts

TravisCI runs slow. This test sometimes takes a loooong time

fix: Increase storybook test timeout

---

wallaby.js

At some point adding unit tests to `_labs` components broke our Wallaby config. This change fixes Wallaby again.

fix: Fix Wallaby config for labs components

---

.travis.yml

Upgrade to Chromatic 2.0: https://www.chromaui.com/
This should give us:
* Visual Reviews
* Storybook hosting
**Note:** Migrating to 2.0 will mean every PR and master has to create new baselines. If a PR has already approve visual changes, those changes will have to be re-approved.
**Note:** This change requires an update to the required checks (`ci/chroma` vs `ci/chromatic`)

chore: Upgrade to Chromatic 2.0

---

modules/_canvas-kit-react/index.ts

This includes `Select` into `@workday/canvas-kit-react` exports.

fix(Select): Includes Select to CKR main exports

---

.travis.yml

Our Visual Regression checking of cross-browsers regressed when upgrading Chroma to v2 which doesn't actually support cross-browser rendering yet. In the meantime, we'll run both v1 and v2. v1 will give us cross-browser visual regression and v2 will give us preview features the new visual review process and Storybook hosting.

ci: Add Chroma v1 for cross-browser visual regression

---

modules/form-field/react/lib/FormField.tsx
modules/form-field/react/lib/Hint.tsx
modules/form-field/react/spec/Hint.spec.tsx

Fixes: https://github.com/Workday/canvas-kit/issues/385
With the translation efforts, we forgot to update the `error` and `alert` labels for the error messages. We also had to add a prop to `FormField` to allow customization.

fix: Remove hard coded strings for alert and error and added new props

---

jest.config.js
utils/spec/ComponentStatesTable.spec.tsx

Add tests for `permutateProps` function added in #418.

test: Add tests for permutateProps utility function

---

modules/_labs/header/react/lib/Header.tsx
modules/_labs/header/react/lib/parts/SearchBar.tsx
modules/_labs/header/react/lib/parts/WorkdayLogoTitle.tsx
modules/_labs/header/react/stories/stories.tsx
modules/button/react/lib/ButtonStyles.ts

An alternative solution from the one proposed in #422
This fixes #420, a bug where the slot containing the nav and icon buttons were getting squished. This was because the slot containing the nav and icons shrunk past the default content size. In addition, icon buttons weren't sized properly in IE11, they need a min-width set, otherwise they collapse.
**Before**:
[Flexbugs](https://github.com/philipwalton/flexbugs#flexbug-1) describes this bug: "Minimum content sizing of flex items not honored" in IE11.
> The flexbox spec defines an initial flex-shrink value of 1 but says items should not shrink below their default minimum content size. You can usually get this same behavior by setting a flex-shrink value of 0 (instead of the default 1) and a flex-basis value of auto. That will cause the …

fix(header): Allow elements to flex correctly in IE11

---

modules/_labs/core/react/lib/theming/README.md
modules/_labs/core/react/lib/theming/useTheme.ts

The global type declaration overrides an internal Workday window object. We are going to remove the type declaration but should also rethink where the fallback should be for an internal use case of `useTheme` (or if we should even include it here?)
applicable

fix(labs): Remove global type from useTheme hook

---

modules/banner/react/package.json
modules/checkbox/react/package.json
modules/color-picker/react/package.json
modules/form-field/react/package.json
modules/radio/react/package.json
modules/select/react/package.json
modules/switch/react/package.json
modules/text-area/react/package.json
modules/text-input/react/package.json

When we added RTL support in https://github.com/Workday/canvas-kit/pull/337/files, we forgot to update the dependencies. RTL depends on the labs `styled` functionality (along with theming), which is not yet stable. These are temporary dependencies until theming moves to `@workday/canvas-kit-react-core`.

fix: Add missing Labs core dependencies to form modules

---

.storybook/config.js
cypress/helpers/stories.ts
cypress/support/index.ts
package.json
yarn.lock

Other people could use our Storybook helpers in Cypress. Why not make it an open source library and dogfood it?
https://github.com/NicholasBoll/cypress-storybook

chore: Update Cypress/Storybook integration to use cypress-storybook

---

.travis.yml

To ensure consumers can test out hot fixes as soon as possible, we would like to introduce Canary builds for each merge to master. This will make every PR available immediately after its merged rather than waiting for our ~2 week release cycle. Hopefully this will also reduce the number of ad hoc releases we need to do.
Rather than using tags to indicate the version like we do for release (because this would tag every commit on master), we will tie canary builds to commit SHAs using lerna's [`--canary`](https://github.com/lerna/lerna/tree/master/commands/publish#--canary) flag
- The default behavior is `3.3.3-alpha.7+eddbcc7` (where `7` is the index of the commit from the last release (`3.3.2`)). 
- We can configure `alpha` here, but nothing else. I recommend we use `next` instead (e.g. …

ci: Add canary build script on master commit/merge

---

.travis.yml

#443 added support for Canary builds, but it has an issue (see https://github.com/lerna/lerna/issues/1769). When determining the previous version to base the canary version off of, [for some reason Lerna uses `git describe` instead of looking at `lerna.json`](https://github.com/lerna/lerna/issues/1769#issuecomment-522847704). Since Travis performs a shallow git clone (currently at a depth of 3), it only checks out the latest 3 commits. When `git describe` can't find a tag from a previous release within those 3 commits, it returns `null`, which causes Lerna to attempt to use the version `null-next.2+cebbd9c` and subsequently fail.
This PR extends the depth of the Travis repo clone to 50 ([the maximum](https://docs.travis-ci.com/user/customizing-the-build#git-clone-depth)). 
**Note: this …

ci: Fix canary build null version error

---

.travis.yml

In #444 I accidentally instructed Travis to run on tag instead of on commit to the master branch. This should get the canary publish running.

ci: Run canary publish on master commit instead of tag

---

.travis.yml

After struggling to get the version checks to work properly with `lerna publish --canary` and discussing how we'd like to publish canary modules, we've decided to force publish everything rather than only doing canary builds of the modules that have changed since the last release. This PR utilizes the `--force-publish` flag to accomplish this.

ci: Force publish all modules for canary builds

---

.travis.yml

With `--force-publish` for lerna canary builds, we still need the history to determine the next version to use. This removes the clone depth entirely as discussed.

ci: Disable git clone depth

---

modules/_labs/combobox/react/README.md

The stories link on the Readme is pointing to the wrong location for stories

docs: Fix broken link on  ComboBox Readme

---

.editorconfig
.travis.yml
utils/get-lerna-version.js

Give us a notification in slack when a canary build has been published so we don't have to check the Travis logs
Example format (incorrect version no):
**New canary build published from [merge commit 6ead127](https://github.com/Workday/canvas-kit/commit/6ead127) (v3.3.2)**
`yarn add @workday/canvas-kit-{module}@3.3.2`
or
`yarn add @workday/canvas-kit-{module}@next`

ci: Announce canary builds on slack

---

.travis.yml
package.json
utils/get-lerna-version.js
utils/publish-canary.js
yarn.lock

I broke the canary build in #458. I guess Travis doesn't like deploy scripts to be multiple lines.
Since this was going to be a very convoluted line if I kept it as shell scripts, I decided to convert this deploy step into a node script. This makes use of Slack's attachments API for nicer formatting.
Hopefully this fixes the build 🤞

ci: Use node script for publishing canary versions

---

utils/publish-canary.js

I was under the impression that `lerna publish --canary` would update the `lerna.json` file, but it does not. The check for the version was looking in `lerna.json`, so we were getting an old version. This updates the logic to pull the version from the logs of the `lerna publish` command.

ci: Pull canary version from lerna publish logs instead of lerna.json

---

modules/_labs/core/react/lib/theming/useTheme.ts
modules/checkbox/react/lib/Checkbox.tsx
modules/common/react/index.ts
modules/common/react/lib/styles/focusRing.ts
modules/form-field/react/stories/stories_Checkbox.tsx

We're adding theming to our inputs. The consumer must wrap their components in a `CanvasProvider` and then they can pass their custom theme to any child components through the `theme` prop.
Partially addresses #358

feat(checkbox): Add theming support

---

utils/publish-canary.js

The lerna output is quieter in CI so the previous regex did not work. This uses a less specific regex, which should correctly capture the packages. We can also reduce the script down to one regex, which can get both the packages and the version using `.match()` and `.exec()`

ci: Use less specific regex for canary publish

---

modules/form-field/react/stories/stories_TextArea.tsx
modules/text-area/react/lib/TextArea.tsx

We're adding theming to our inputs. The consumer must wrap their components in a CanvasProvider and then they can pass their custom theme to any child components through the theme prop.

feat(text-area): Add theming support

---

modules/button/react/lib/IconButton.tsx
modules/button/react/lib/IconButtonToggleGroup.tsx
modules/button/react/spec/IconButton.spec.tsx

Due to some changes in the way we use `@emotion/styled`, we are no longer able use [component selectors](https://emotion.sh/docs/styled#targeting-another-emotion-component) in Emotion via Babel. This is because `styled` functions using Emotion's `CreateStyled`, like our own [Canvas styled component](https://github.com/Workday/canvas-kit/blob/ed41a76be50068cb1ae15b666d9305a6a97c4b72/modules/_labs/core/react/lib/theming/styled.ts#L52), does not work with the babel plugin for emotion.
This is a known issue and will be fixed in Emotion 11 by https://github.com/emotion-js/emotion/pull/1220 via a mapping configuration so the plugin knows about custom styled functions.
For now the fix is to just remove the usage of component selectors. This PR addresses that by using an identifier class name …

fix(button): Fix Component Selector Issue

---

modules/form-field/react/stories/stories_Switch.tsx
modules/radio/react/lib/Radio.tsx
modules/switch/react/lib/Switch.tsx

We're adding theming to our inputs. The consumer must wrap their components in a `CanvasProvider` and then they can pass their custom theme to any child components through the `theme` prop.
Partially addresses #358 
Blocked on https://github.com/Workday/canvas-kit/pull/457
Notes:
- I noticed we were still using Blueberry 500 for the checked color. This is an old styling and all of our other inputs now use Blueberry 400. The checked background was updated. If you need to force Blueberry 500 for whatever reason, you can wrap the switch with a custom theme
- The checked disabled state was a light gray when it should have been a light blue. This has been updated.

feat(switch): Add theming support

---

.storybook/config.js
modules/form-field/react/stories/stories_Checkbox.tsx
modules/form-field/react/stories/stories_ColorInput.tsx
modules/form-field/react/stories/stories_Radio.tsx
modules/form-field/react/stories/stories_Select.tsx
modules/form-field/react/stories/stories_Switch.tsx
modules/form-field/react/stories/stories_TextArea.tsx
modules/form-field/react/stories/stories_TextInput.tsx
package.json
yarn.lock

We are testing way too many stories that aren't useful for visual regression. This PR tells Chromatic to ignore all stories by default and only include ones that are marked.
applicable

test: Explicitly enable snapshots

---

modules/button/react/lib/ButtonBase.tsx
modules/button/react/lib/DropdownButton.tsx
modules/button/react/lib/TextButton.tsx
modules/button/react/stories/stories_iconButton.tsx
modules/button/react/stories/stories_visualTesting.tsx

In preparation for #468, we would like to have static state tables in place so that we can ensure no regressions are introduced in the upcoming button refactor. This PR adds them for `Button`, `DropdownButton`, and `TextButton`. It also moves the existing `IconButton` static states story to a common folder with the others (I thought this was clearer than having to dive into subfolders for each visual testing story - especially when we start to add multiple stories for theming).
Note: There are actually quite a few issues with some of the prop combinations. Some problems are stylistic, while others make it clear where we've exposed possible prop combinations that shouldn't be available. I would propose we leave them as is for now and try to address them in the refactor. Would love some …

test(button): Add static state tables for all Button components

---

utils/check-dependencies-exist.js

In order for stories to be friendlier to copy/paste, a story should use the package name.
This change allows for a package's story to reference the package by name. The dependency check was requiring the package to define the dependency, which was illegal.

feat: Allow a module's story to self-reference the package

---

eslintrc.js
modules/_labs/core/react/lib/theming/useTheme.ts
modules/core/react/spec/InputProvider.spec.tsx
modules/icon/css/lib/canvas-kit-css-icon.js
modules/icon/css/lib/utils.js
modules/icon/react/lib/AppletIcon.tsx
package.json
yarn.lock

We were unnecessarily using `Object.entries` in the check for an empty context in `useTheme`. This function requires a polyfill in IE 11, so I've switched it to use `Object.keys` instead, since this is equivalent for checking whether an object is empty.
Continued:
After a bit more exploration, we were using several functions that required polyfills. This PR now adds a lint check to ensure we don't do this in the future.

fix: Avoid polyfill requirements

---

.travis.yml

We were part of the beta process for Chromatic v2 and now they have rolled those into their main offering. We can stop running both the main Chromatic offer plus the beta offering. This will speed up out CI process.
This PR also reduces the noise in the log from webpack by passing `--quiet`

chore: Simplify Chromatic CI runs

---

.travis.yml
utils/publish-canary.js

#481 forgot to account for the variable preid (`next` vs. `prerelease` in the regex for searching the Lerna output). This resolves that error [seen here](https://travis-ci.org/Workday/canvas-kit/builds/658924582).
Also, we want to push these prelease canary builds under a major release (e.g. `v4.0.0-prerelease.3+SHA`). This also tells Lerna to use a major bump for prerelease branches.

ci: Fix prerelease canary builds

---

.travis.yml

Don't want to get into trouble in the future by not specifying that we're running the workspace version of Chromatic (instead of a random global one for example).
Oops, removed `yarn` from the `chromatic` cmd in #500, this adds it back.

ci: Explicit use of yarn for Chromatic cmd

---

.travis.yml
package.json
yarn.lock

Things we did to speed up Travis (hopefully for real this time):
- Exit Chromatic after upload so it doesn't hold up the build
- Remove caching for yarn and npm (node_modules). Loading and building the cache is longer than the savings incurred by having a cache.
- Deduplicate instances of Webpack in our yarn.lock
- Replace `concurrently` with `run-p` (part of `npm-run-all`, a dep we already use). Concurrently was a 40mb hit to our cache and didn't add any value from what we already have.
We went from around 20 to 25 min to 15min. Not too shabby.

ci: Travis build speed improvements

---

modules/_labs/drawer/react/lib/DrawerHeader.tsx
modules/_labs/drawer/react/spec/Drawer.spec.tsx
modules/_labs/drawer/react/stories/stories.tsx

We want to be able to use the side panel with the header. However we are going to keep it open and therefore we do not want to render a close button. 
Closes #506 
- [x ] branch has been rebased on the latest master commit
- [ x] tests are changed or added
- [ x] `yarn test` passes
- [ x] all (dev)dependencies that the module needs is added to its `package.json`
- [ x] code has been documented and, if applicable, usage described in README.md
- [ x] module has been added to `canvas-kit-react` and/or `canvas-kit-css` universal modules, if
applicable
- [ x] design approved final implementation
- [ x] code adheres to the [API & Pattern guidelines](../API_PATTERN_GUIDELINES.md)

feat(drawer): Make the close icon in DrawerHeader optional

---

modules/_labs/pagination/react/lib/Pages.tsx
modules/button/css/README.md
modules/button/react/index.ts
modules/button/react/package.json
modules/button/react/stories/stories_IconButton.tsx
modules/modal/css/stories.tsx
modules/popup/css/stories.tsx
modules/popup/react/lib/Popup.tsx
modules/popup/react/stories/stories.tsx
modules/toast/react/lib/Toast.tsx
modules/toast/react/package.json

There were a few bugs that were not caught in #471. This PR addresses them.
I'm honestly unsure how some of these made it past CI... 🤔

fix(button): Misc. fixes after refactor

---

.storybook/webpack.config.js

After some recent changes, Travis logs have become really noisy when building storybook ([Example](https://travis-ci.org/github/Workday/canvas-kit/builds/662071720?utm_medium=notification&utm_source=email)).
This stems from the `ProgressPlugin` that storybook's webpack config uses. This updates in place locally, but for some reason it generates a new line for each update in Travis. I updated our custom webpack config to remove this plugin when in the Travis env. This should not affect warnings or errors being reported.

ci: Quiet Travis build-storybook webpack logs

---

modules/_labs/core/react/lib/theming/theme.ts
modules/_labs/core/react/lib/theming/types.ts
modules/button/react/lib/Button.tsx
modules/button/react/lib/DeleteButton.tsx
modules/button/react/lib/DropdownButton.tsx
modules/button/react/lib/HighlightButton.tsx
modules/button/react/lib/IconButton.tsx
modules/button/react/lib/OutlineButton.tsx
modules/button/react/lib/TextButton.tsx
modules/button/react/lib/parts/ButtonContainer.tsx
modules/button/react/stories/stories_visualTesting.tsx

Does what it says! Excludes `deprecated_Button`
Closes #518 
applicable

feat(button): Add theming support to buttons

---

utils/check-dependencies-exist.js

Fix an issue where the file wasn't being output so the annotation matching wasn't picking it up correctly.

ci: Fix annotation for extra dependencies

---

modules/_labs/color-picker/react/lib/parts/ColorReset.tsx
modules/_labs/color-picker/react/lib/parts/SwatchBook.tsx
modules/color-picker/react/index.ts

When Importing Labs:ColorPicker, we had a build error due to improper file imports
Closes https://github.com/Workday/canvas-kit/issues/575

fix(ColorPicker): Export ColorSwatch from the ColorPicker index

---

cypress/integration/Modal.spec.ts
modules/modal/react/lib/ModalContent.tsx
modules/modal/react/spec/Modal.spec.tsx
modules/popup/react/lib/Popup.tsx

Fixes: https://github.com/Workday/canvas-kit/issues/587
applicable

Fix: Add missing accessibility aria-modal=true to the Modal and aria-label

---

modules/_labs/core/react/lib/type.ts
modules/common/react/lib/theming/useTheme.ts
modules/core/react/lib/type.ts
modules/core/react/package.json

Under certain location circumstances, our product needs to load extra fonts for the best experience (e.g. using Noto for CJK character support). We don't want to always load these fonts as they can take a while to load and are often unnecessary. To remedy this, we need to enable consumers to opt out of our font stack at page load so they can rely on a font stack they've specified at a higher level.
Since this only needs to happen at page load, this PR simply updates our type hierarchy to look for a window variable set before adding the `fontFamily` property to our various levels. This method is more performant, simpler and provides less room for error than what was explored in #552. It also avoids all bespoke teams within the Workday application from having to manage the font stack …

feat(core): Add window configuration option to inherit font family

---

modules/button/react/README.md
modules/button/react/lib/Button.tsx
modules/button/react/lib/DeleteButton.tsx
modules/button/react/lib/DropdownButton.tsx
modules/button/react/lib/HighlightButton.tsx
modules/button/react/lib/IconButton.tsx
modules/button/react/lib/OutlineButton.tsx
modules/button/react/lib/TextButton.tsx
modules/button/react/lib/deprecated_Button.tsx
modules/button/react/lib/parts/ButtonContainer.tsx
modules/button/react/lib/types.ts
modules/button/react/spec/Button.spec.tsx
modules/button/react/spec/IconButton.spec.tsx

Proof of concept for adding `href`/anchor support to our button components.
Some UI buttons require an href (marketing sites, download buttons, etc.). This is in support of those use cases.
Adds a special `as` prop to all button components (excluding `Hyperlink`). When `as="a"` is defined, we switch from `React.ButtonHTMLAttributes<HTMLButtonElement>` to `React.AnchorHTMLAttributes<HTMLAnchorElement>`
Closes: https://github.com/Workday/canvas-kit/issues/87

feat(button): Add href support

---

utils/storybook/ControlledComponentWrapper.tsx
utils/storybook/index.ts

We have a controlled component wrapper for form inputs so that the stories update when you interact with them. But we do this in many different ways and none of them are clear when looking at the documented example.
Before:
```tsx
// example 1
export const Default = () => (
<FormField label="Label" inputId="my-checkbox-field">
{controlComponent(<Checkbox label="Checkbox option" disabled={true} />, ControlledWrapperComponent.ControlProp.Checked)}
</FormField>
}
// example 2
export const Default = () => (
<FormField label="Label" inputId="my-checkbox-field">
<ControlledComponentWrapper controlledProp={ControlledComponentWrapper.ControlledProp.Checked}>
<Checkbox label="Checkbox option" disabled={true} />
</ControlledComponentWrapper>
</FormField>
)
```
I think we did this originally because …

chore: Refactor control wrapper to hooks for easier examples

---

.github/workflows/ci.yml
.travis.yml

The CI is a bit hard to read with verbose output. The CI cannot rewrite lines, so it dumps out thousands of progress lines. We only need to know about errors in CI.
Example output we're trying to reduce:
```
...
<s> [webpack.Progress] 69% building 4085/4110 modules 25 active /home/runner/work/canvas-kit/canvas-kit/node_modules/string.prototype.matchall/auto.js
<s> [webpack.Progress] 69% building 4085/4111 modules 26 active /home/runner/work/canvas-kit/canvas-kit/node_modules/globalthis/auto.js
<s> [webpack.Progress] 69% building 4085/4112 modules 27 active /home/runner/work/canvas-kit/canvas-kit/node_modules/promise.allsettled/auto.js
<s> [webpack.Progress] 69% building 4085/4113 modules 28 active /home/runner/work/canvas-kit/canvas-kit/node_modules/array.prototype.flat/shim.js
<s> …
```

chore: Decrease output of build-storybook

---

cypress/integration/Popup.spec.ts
modules/popup/react/lib/Popup.tsx
modules/popup/react/package.json
modules/popup/react/spec/Popup.spec.tsx
modules/popup/react/stories/stories_VisualTesting.tsx
modules/toast/react/spec/Toast.spec.tsx

Adds visual and cypress test for Popup and change enzyme test to react testing library

test(popup): Add tests for Popup

---

utils/publish-canary.js

In #616 we updated our prerelease canary versions to include the sha. Unfortunately `git rev-parse --short HEAD` returns with a trailing new line, which means the full command wasn't executed (ignoring the `--dist-tag prerelease` param). 
The last canary build based on the merge of #616 used the default preid `canary`, which will unfortunately need to be removed for all modules.
This PR trims the sha before using it so we don't insert a new line into the lerna publish command before running it.

ci: Remove new line in lerna publish canary script

---

utils/publish-canary.js

One more! #616 added a sha to canary release versions, but I forgot to update the regex used to pull the version for the slack update.
Also, I added an extra slack announcement for failed canary publishes.

ci: Fix version regex for canary publish

---

.github/workflows/ci.yml

We recently changed to `actions/checkout@v2` which apparently doesn't have any git history which is preventing ChromaticQA from finding proper baselines. This is causing all PRs in the prerelease branch to have no baselines and registers all stories as new.
More info: https://www.chromatic.com/docs/ci#github-actions

ci: Fix ChromaticQA Baselines

---

.travis.yml
utils/report-failure.js

Currently if there is a build failure after a merge we get an email if it's on master (slow) and nothing if it's another "trunk-style" branch (e.g. `prerelease/v4`). This will post a message to slack whenever the `trunk` stage in travis fails.
Closes #617

ci: Report trunk build failures to slack

---

modules/toast/react/stories/stories_visualTesting.tsx

This is currently blocked until master is merged into pre release v4. With the change introduced in https://github.com/Workday/canvas-kit/pull/600 , passing null to transform origin will now capture the stories for toast.

fix(toast): Fix chromatic stories for toast

---

modules/color-picker/react/lib/ColorInput.tsx

Fixes: https://github.com/Workday/canvas-kit/issues/364
Currently, the placeholder text confuses accessibility and announces it as if it were a value. This PR eliminated that duplication and clarifies what is announces by voice over.
applicable

fix(color-picker): Fix accessibility announcement for color input

---

modules/toast/react/package.json
package.json
utils/check-lockfile.js
yarn.lock

Our latest beta build (`4.0.0-beta.2`) was broken due to an incorrect merge which caused `@workday/canvas-kit-react-toast` to have a dev dependency on `@workday/canvas-kit-labs-react-core@3.6.0`. This meant some of our components were pulling an old version of CK, which caused issues due to incompatibility between v4 and 3.6.0. 
This PR updates the old dev dep, removes the CK references from our yarn.lock file, and updates our check-lockfile script to look for CK dependencies (which should not be there).
In the future, we plan to remove these devDeps all together to avoid this entirely (since they're not required in a yarn workspace) (see #645)

chore: Fix version issue in beta build

---

CONTRIBUTING.md

We no longer encourage rebasing in pull request branches. We utilize the Squash feature in Github to maintain clean history

docs: Remove rebase section for pull requests

---

utils/create-component/createComponent.js
utils/create-component/createCssModule.js
utils/create-component/createReactModule.js
utils/create-component/writeModuleFiles.js
utils/css-build.js
utils/js-build.js
utils/promote-component.js

The API of mkdirp changed with version 1.0 from callbacks to promises, but we didn't update our use-cases. The change of version was in #531. I tested this with a new module

chore: Fix create-module and promote-module

---

package.json

Fixes an invalid reference to `check-lockfile-links.js` which was renamed to `check-lockfile.js` in #644.

fix: Fix check-lockfile call during precommit linting

---

lerna.json
package.json
utils/publish-canary.js

Addresses everything in https://github.com/Workday/canvas-kit/issues/661:
- Change prerelease canary dist tag to `prerelease-next` so it doesn't clobber `prerelease` releases
- Use previous release for canary preids instead of the sha (which can result in unpredictable resolutions). Example: `4.0.0-beta.4-next.0`
- Skip canary builds if last merge commit was a release (if `CHANGELOG.md` was changed)
- **Disable prerelease canaries for now**. The above changes will not be reflected as we've decided to disable prerelease canary builds temporarily since we've had some issues and they're not being used.
- **Change default publish behavior of Lerna to publish all modules regardless of whether they've been updated (`--force-publish="*"`)**
Closes #661

ci: Improve canary builds & publish behavior

---

modules/checkbox/react/lib/Checkbox.tsx
modules/radio/react/lib/Radio.tsx

Fixes #650 
I'll do my best to explain how this fix came to be for both `Radio` and `Checkbox` because they are implemented similarly.
The first thing was to fix ripple positioning in IE11. This means that we have to make sure that the ripple is placed intentionally by setting `top: 0px` instead of the default `top:auto` which is browser controlled.
Hang on, not that simple though. The width of the border for the parent element (`RadioBackground`, `CheckboxBackground`) will render with offset errors on all browsers when this happens.
Why? This is because absolutely positioned element coordinates are based on the parent's content not the content + border width (border-box doesn't help this). So to align correctly you have to account for the border's width, i.e. `top: -1px`. If the border …

fix: Align hover ripple for checkbox and radio components in IE11

---

modules/_canvas-kit-css/package.json

This hasn't been cut to an official release yet but technically >=3.7.1-next.0 may be broken. Not sure when this change went in.
Changing the package listing for badge to be the correct one in CSS.
Not sure how we can catch this one via testing. Another dep-check rule?

fix: Fix incorrect dep listing

---

modules/switch/react/lib/Switch.tsx

Fixes: https://github.com/Workday/canvas-kit/issues/657
Make the input display block pinning the input to the left

fix(switch): Fix click target for switch

---

utils/create-component/createComponent.js
utils/create-component/createCssModule.js
utils/create-component/createReactModule.js
utils/create-component/templates/css/packageJson.js
utils/create-component/templates/react/packageJson.js

Resolves #643
Adds a step in the create-component cli to add a public config to new modules
`utils/create-component/createComponent.js`
Run the script!
```sh
yarn create-component
```
If the module should be public (the default), this config will be added to the package.json
```json
"publishConfig": {
"access": "public"
},
```
Otherwise, it will be omitted, and the module will be private when published.
n/a
applicable

chore: Add public config to create-component script

---

yarn.lock

Dependabot doesn't seem to understand monorepos. This removes a dependency that shouldn't be there in the `yarn.lock` file introduced in #703

chore: Remove unneeded dependency

---

modules/avatar/react/stories/stories_visualTesting.tsx

Fixes the Avatar visual test from showing as constant regressions in Chromatic

test(avatar): Fix visual regression threshold

---

4.0-MIGRATION-GUIDE.md
modules/button/react/lib/TextButton.tsx
modules/button/react/lib/ToolbarDropdownButton.tsx
modules/button/react/lib/ToolbarIconButton.tsx
modules/common/react/lib/styles/focusRing.ts
modules/common/react/spec/focusRing.spec.ts

- Updates background colors of `ToolbarIconButton` and `ToolbarDropdownButton` to use the same backgrounds as icon buttons per the spec.
- Updates `focusRing` API to add more control over how the shadows are inset
- Shifts inverse `TextButton` variant focus outline 2px inwards (using new `focusRing` API) per the spec
- `focusRing`'s `inset` option has changed slightly. It used to be a boolean type. Now it is typed as `undefined | 'inner' | 'outer'`. This allows consumers to specify whether both shadows are on the outside (`undefined`), just the inner shadow is inset (`'inner'`), or both shadows are inset (`'outer'`). This was option was unused throughout most of our codebase so it shouldn't have much impact.
applicable

fix(button): Misc. styling fixes and update to focusRing API

---

modules/_labs/drawer/react/lib/DrawerHeader.tsx
modules/_labs/drawer/react/package.json
modules/_labs/drawer/react/stories/stories_visualTesting.tsx
modules/side-panel/react/lib/SidePanel.tsx

Partially fixes: #683
Add snapshots for drawer component

test(drawer): Add stories and snapshots for drawer

---

modules/icon/css/README.md
modules/icon/css/lib/canvas-kit-css-icon.js
modules/icon/react/README.md
modules/icon/react/lib/SystemIcon.tsx

I missed a few things in #706. This addresses those issues.

fix(icon): Fix icon color references

---

modules/form-field/react/stories/visual-testing/stories_Radio.tsx

This fixes an issue where our `Radio` component's visual regression story does not display an error message for the `Error` type `FormField`.
It should say "Error: Helpful text goes here." Underneath the second `RadioGroup`

test(radio): Fix prop table logic

---

modules/_labs/select/react/lib/SelectOption.tsx

Fixes the Select component to style text colors using `pickForegroundColor` to ensure proper contrast.

fix(select): Fix theming colors for proper contrast

---

modules/_labs/select/react/lib/SelectOption.tsx
modules/common/react/lib/utils/colorUtils.ts
modules/common/react/spec/colorUtils.spec.tsx
modules/common/react/spec/createCanvasTheme.spec.tsx
modules/icon/react/lib/SystemIconCircle.tsx

If no colors provided or neither meets contrast requirements, falls back to the first that meets
contrast requirements of frenchVanilla100, blackPepper300, blackPepper400, blackPepper500,
blackPepper600.
Based on our conversation today, implemented the fallback logic into `pickForegroundColor`
applicable

refactor(common): Update pickForegroundColor to use fallback color logic

---

utils/publish-canary.js

Canary builds after we removed the sha from the canary package versions

ci: Fix canary regex to grab version

---

modules/icon/react/README.md
modules/icon/react/lib/AccentIcon.tsx
modules/icon/react/lib/AppletIcon.tsx
modules/icon/react/lib/Graphic.tsx
modules/icon/react/lib/Icon.tsx
modules/icon/react/lib/Svg.tsx
modules/icon/react/lib/SystemIcon.tsx
modules/icon/react/lib/SystemIconCircle.tsx

Resolves #574 
This PR adds an `iconRef` prop to the `Icon` component, which also affects the components listed below. Documentation was also updated to reflect this change.
* AccentIcon
* AppletIcon
* Graphic
* Svg
* SystemIcon
* SystemIconCircle
`modules/icon/react/lib/Icon.tsx`
Probably the best way to test this is to add an `iconRef` to an `Icon`.
```jsx
const ref = React.createRef();
return (
<Icon iconRef={ref} {...otherIconProps} />
)
```
n/a
n/a

feat: Add iconRef to Icon components

---

cypress/helpers/selectLabs.ts
modules/_labs/select/react/lib/SelectBase.tsx

Fixes #761.
In addition to fixing the a11y violation reported in #761, this PR replaces the `aria-owns` attribute assigned to the Select button with the more appropriate `aria-controls`.
Previously, we had been linking the Select button with its corresponding menu using `aria-owns`. `aria-owns` expresses a parent/child relationship between DOM elements, which doesn't reflect the relationship between the Select button and its corresponding menu ([source](https://www.w3.org/WAI/PF/aria-1.1/states_and_properties#aria-owns), [source](https://github.com/w3c/html-aria/issues/124#issuecomment-451726237)).
`aria-controls` more accurately describes the relationship between the button and its menu ([source](https://www.w3.org/WAI/PF/aria-1.1/states_and_properties#aria-controls)).

fix(select): Fix a11y issues

---

modules/form-field/react/lib/Hint.tsx
modules/form-field/react/stories/visual-testing/theming/stories_FormField.tsx

Closes #768.
Updates the text color of form field error messages to pull from the `error.main` theme color (`cinnamon500` in the default Canvas theme).
Also adds a `Form Field Themed States` visual testing story.

refactor(form-field): Update error message color

---

.storybook/preview-head.html
cypress/helpers/modal.ts
cypress/integration/Modal.spec.ts
cypress/integration/PopupStack.spec.ts
modules/modal/react/lib/Modal.tsx
modules/modal/react/lib/ModalContent.tsx
modules/modal/react/package.json
modules/modal/react/stories/stories_VisualTesting.tsx
modules/popup-stack/README.md
modules/popup-stack/lib/PopupStack.ts
modules/popup-stack/stories/stories_testing.tsx
modules/popup/react/README.md
modules/popup/react/lib/Popper.tsx
modules/popup/react/lib/Popup.tsx
modules/popup/react/lib/useAssistiveHideSiblings.ts
modules/popup/react/lib/useBringToTopOnClick.ts
modules/popup/react/lib/useCloseOnEscape.ts
modules/popup/react/lib/useCloseOnOutsideClick.ts
modules/popup/react/lib/useFocusTrap.ts
modules/popup/react/lib/usePopupStack.ts
modules/popup/react/stories/stories.tsx
modules/popup/react/stories/stories_testing.tsx
modules/tooltip/react/lib/useTooltip.tsx
modules/tooltip/react/stories/visual.tsx

Fixes #750
applicable
feat(popup-stack): Add adapter API to integrate with other popup systems (#782)
This is a potentially breaking  change if you use `usePopupStack` and `ReactDOM.createPortal(contents, document.body)`:
We added `createContainer` to `PopupStack`. React no longer controls the element that is given to the the `PopupStack`. The `PopupStack` will now create a containing element that your content should render into. If you recognize this pattern, you'll need to render into `stackRef.current` instead of `document.body`.
Before:
```tsx
const ref = React.createRef<HTMLDivElement>(null);
usePopupStack(ref)
React.createPortal(contents, document.body)
```
Now
```tsx
const stackRef = usePopupStack()
React.createPortal(contents, stackRef.current)
```

feat(popup-stack): Add adapter API to integrate with other popup systems

---

modules/button/react/lib/ButtonStyles.ts

We are specifying a literal font stack in our button's style, this will override the behavior that we changed in #553 
Everything in Canvas Kit React should use the `fontFamily` import from `core`.

fix(button): Remove literal fontFamily

---

cypress/integration/SelectLabs.spec.ts
modules/_labs/select/react/lib/SelectMenu.tsx
modules/_labs/select/react/stories/stories_testing.tsx

Fixes an issue where activating the Labs Select menu caused the browser to scroll to the top of the page.
In #535, we modified Select to focus the menu inside of a `useLayoutEffect` call with an empty dependency array (previously, focus was being applied to the menu using Popper's `onFirstUpdate`). This had the unintended consequence of causing the browser to scroll to the top of the page whenever a Select menu was activated -- we suspect focus was being applied after the menu had been rendered but _before_ it had been positioned by Popper, thus causing the browser to scroll to the top of the page where the menu is originally positioned prior to being moved by Popper.
As an immediate fix, I've reverted to the previous method of focusing the menu using `onFirstUpdate`. The long-term …

fix(select): Fix undesired scrolling when activating menu

---

cypress/integration/SelectLabs.spec.ts
modules/_labs/select/react/lib/SelectBase.tsx
modules/_labs/select/react/spec/Select.spec.tsx
modules/_labs/select/react/stories/stories_testing.tsx

Fixes #781.
Previously, the Labs Select was throwing an a11y violation when assigned the `aria-required` prop (the Select is rendered using a `button` and `button` isn't allowed to have `aria-required`). This PR adds special handling which passes `aria-required` along to the Select Menu to be applied to the `listbox` in accordance with Workday Accessibility's requirements.
I've also added a corresponding Cypress and unit tests.

fix(select): Support aria-required

---

cypress/integration/ColorPicker.spec.ts
modules/_labs/color-picker/react/README.md
modules/_labs/color-picker/react/lib/ColorPicker.tsx
modules/_labs/color-picker/react/stories/stories_ColorPicker.tsx
modules/_labs/color-picker/react/stories/stories_testing.tsx

Fixes #760
The original implementation used keydown to detect the "Enter" key and fire the `onColorChange` event. If focus is transferred during the timing of this event, the enter key will actually be forwarded to the next target. This isn't exactly what we want.
This PR moves the custom color input into a `form` element and uses the submit event to handle special functionality like the enter key. This is a more accessible option.

fix(color-picker): Prevent enter key fowarding to next focus target

---

modules/_labs/select/react/lib/SelectBase.tsx

Minor fix to add a corresponding `cancelAnimationFrame` call to the `requestAnimationCall` used to scroll the focused option into view upon menu activation.

fix(select): Add cancelAnimationFrame to unmount

---

modules/_labs/menu/react/lib/Menu.tsx

Fixes #632
Prevent scrolling the page. The Menu calls `focus` on the `ul` on mount, but this is before PopperJS positions the menu. This causes the browser to scroll to the top of the page (default position of the Popper until positioning). This change delays the `focus` call until after the Popper is positioned.
We'll have a more robust focus utility function later. VoiceOver on iOS has issues with setting focus on newly created DOM too early. See #694

fix(menu): Delay focus to prevent scrolling

---

modules/skeleton/react/lib/skeleton.tsx
modules/skeleton/react/package.json
modules/skeleton/react/spec/skeleton.spec.tsx

Fixes #792
Removes aria-live from Skeleton loaders and replaces with visually-hidden text content for a better and more consistent screen reader experience.

fix(skeleton): Remove aria-live and add loading text content

---

cypress/integration/Menu.spec.ts
modules/_labs/menu/react/lib/MenuItem.tsx
modules/_labs/menu/react/stories/stories.tsx

Fixes #808 
Add `scrollIntoViewIfNecessary` to the `MenuItem` to make sure it is focused item is visible. Uses the same algorithm as the Labs select menu

fix(menu): Auto scroll to selected menu item if necessary

---

blank.yml

This workflow file will run when an issue is first opened, adding it to the `Backlog` project and the `Open` column. It uses the `GH_RW_TOKEN` secret which is currently one of my personal tokens. We can update this secret at any time to any account we want.
I was unable to get the `GITHUB_TOKEN` to work as expected: https://github.com/NicholasBoll/test-github-actions/actions/runs/198099260. If we can get the `GITHUB_TOKEN` to work in the future, we should use that so the account shows up as the github_actions account instead of mine. For now, I'm just magically triaging every new issue! Yay me!

ci: Add new issues into Backlog project

---

modules/_labs/color-picker/react/lib/ColorPicker.tsx
modules/_labs/color-picker/react/lib/parts/SwatchBook.tsx
modules/_labs/color-picker/react/stories/stories_VisualTesting.tsx

Fixes issue: https://github.com/Workday/canvas-kit/issues/770
In order to support grid layout in IE11, -ms-grid-row and -ms-grid-column need to be explicitly set. In addition IE doesn't support gridGap, so adjusted to use margin spacing. Lastly, I abstracted out some variables regarding the number of swatches within a row to possibly help support further future development.

fix(color-picker): Fix IE rendering for color picker swatchbook

---

cypress/integration/SelectLabs.spec.ts
modules/_labs/select/react/lib/Select.tsx
modules/_labs/select/react/stories/stories_testing.tsx

We manage assistive focus on the Select component using [aria-activedescendant](https://www.w3.org/TR/wai-aria-practices-1.1/#kbd_focus_activedescendant); when the keyboard is used to navigate the menu, `aria-activedescendant` is updated to refer to the ID of the currently focused option.
Prior to this fix, assistive focus could be applied to a disabled option using the keyboard (Up/Down/Home/End keys) if that disabled option happened to be the first or last option in the menu. The disabled option was correctly styled without focus styles and it was unselectable, but `aria-activedescendant` was still being set to refer to the disabled option's ID. The Select's internal component state also incorrectly set focus to the disabled option. This meant the user could navigate to a disabled …

fix(select): Prevent disabled options from being keyboard-focused

---

cypress/integration/ColorPicker.spec.ts
modules/_labs/color-picker/react/lib/ColorPicker.tsx
modules/_labs/color-picker/react/lib/parts/ColorReset.tsx
modules/_labs/color-picker/react/lib/parts/SwatchBook.tsx
modules/_labs/color-picker/react/spec/ColorPicker.spec.tsx
modules/_labs/color-picker/react/stories/stories_ColorPicker.tsx
modules/_labs/color-picker/react/stories/stories_VisualTesting.tsx

As a policy, we don't add `data-` attributes to our shipped codebase. If we every need them for testing, we'll use them at the `spec` level but never at a component level. This one somehow slipped through so I'm removing them here and changing our Cypress tests accordingly.
Bonus: removed `addon-actions` from the `ColorPicker` story. This is most likely going to freeze browsers like IE11.

test(color-picker): Remove data attributes

---

cypress/integration/SelectLabs.spec.ts
modules/_labs/select/react/lib/SelectBase.tsx
modules/_labs/select/react/lib/SelectOption.tsx
modules/_labs/select/react/stories/stories_visualTesting.tsx

Previously, the `disabled` attribute was incorrectly being applied to disabled options; options are represented as `<li>` elements, and `disabled` is not a valid attribute for an `<li>`. Workday Accessibility advised that we set `aria-disabled="true"` on the disabled option instead.
This PR also includes a small tweak that prevents `aria-required` from being unnecessarily set to `"false"` on the Select menu if `aria-required` or `required` was never passed as a prop in the first place (i.e., render `<ul role="listbox">` instead of `<ul role="listbox" aria-required="false">`).

fix(select): Replace disabled attribute on options with aria-disabled

---

.github/workflows/ci.yml

Update to use `pull_request_target` so we aren't exposing our service keys anymore.
First run will be to make sure everything works, but I'm still using the `pull_request` event instead of `pull_request_target`. Once that passes, I'll change it to use `pull_request_target`. The reason is I cannot test `pull_request_target` in a pull request because that event will use the base branch instead of the changes in the pull request...
Then we won't even know 100% for sure until merge this PR and then open another PR to make sure the CI passes there...

ci: Use secrets and pull_request_target

---

cypress/integration/Modal.spec.ts
modules/modal/react/package.json
modules/modal/react/stories/stories.tsx
modules/popup/react/package.json

focus-trap-js had a bug when handling radio-buttons.
applicable

Bump focus-trap-js to 1.1.0 and add cypress test

---

modules/form-field/react/lib/Label.tsx
modules/form-field/react/stories/visual-testing/stories_Radio.tsx

This fixes #852 . When a `FormField` renders a `legend` as its label (i.e. when the `useFieldset` prop is true) and long-form text overflows the parent container's width. This doesn't happen in Chrome or FF.
Adding `width: 100%` on the `legend` element fixes this bug but can only be applied to top-labeled `FormField`s. If it's applied to the side-labeled fields then it will interfere with the `min-width` property for that label position.
Does this on IE11:
Should do this on all browsers:

fix(form-field): Fix legend overflow bug (IE11)

---

modules/popup-stack/lib/PopupStack.ts

Previously, if there were multiple imports (from different bundles) of the PopupStack, the adapter would be overwritten each time the PopupStack was imported. While the PopupStack can be overridden, the adapter should not be (otherwise, createAdapter becomes a bit useless 😅 ) 
applicable

fix(popup-stack): Move adapter var to popup-stack global namespace

---

yarn.lock

The prismjs version bump in #826 introduced an issue which prevented stories from being loaded in Storybook in IE11. Upon loading a story, the page would go completely white with console errors referencing code from the prismjs package:
The following steps were performed in this PR to revert the changes from #826:
1. `git revert a41252f0f413a77f02a52675b637f272f031099e` ([commit](https://github.com/Workday/canvas-kit/commit/a41252f0f413a77f02a52675b637f272f031099e))
2. Disabled (temporarily) the `--install.frozen-lockfile true` line in .yarnrc to allow the `yarn` command in the next step to resolve conflicts and write to yarn.lock
3. Ran `yarn` to automatically resolve merge conflicts in yarn.lock
4. Re-enabled the `--install.frozen-lockfile true` line in .yarnrc
5. Staged resolved …

fix: Revert prismjs from 1.21.0 back to 1.17.1

---

modules/popup/react/README.md

It is fine for the `usePopupStack` to be used directly. The only time it shouldn't be used is when `Popper` is used.

docs(popup): Change language around use of usePopupStack

---

modules/popup/react/README.md
modules/popup/react/lib/useCloseOnEscape.ts

Fixes #877
This PR adds an optional parameter, `previousFocusRef`, to the `useCloseOnEscape` hook. If provided, this allows the focus to return the specified element before calling `onClose`.
`modules/popup/react/lib/useCloseOnEscape.ts`
n/a
n/a
applicable

[WIP] feat(popup): Add previousFocusRef to useCloseOnEscape hook

---

modules/_labs/drawer/react/lib/Drawer.tsx
modules/toast/react/lib/Toast.tsx

Fixes #878 
This PR adds IE11 support for word wrapping in the Drawer component.
`modules/_labs/drawer/react/lib/Drawer.tsx`
* Pull down changes
* Run `yarn start`
* visit `http://localhost:9001/?path=/story/testing-react-labs-drawer--drawer-states`
* update the text in one of the drawers
* I would recommend something like "Note: Internet_Explorer_Eleven was originally released in October 2013"
* See "Internet_Explorer_Eleven" as expected
n/a
See screenshots in #878 
applicable

fix(drawer): Add support for word wrapping in IE11

---

modules/common/react/lib/CanvasProvider.tsx

Solves issue #862 where IE11 is not adding a display property to the bdo tag.
applicable

fix(common): Remove unintended whitespace around bdo tag (IE11) (#862)

---

modules/modal/react/lib/ModalContent.tsx

This fixes an issue where the Popup adapter is being used. It will flash because the adapter will remove the containing element for popups and show again. The animation makes detach/attach cycle a visible flashing. This is already added to the Popup.tsx file, we just missed the Modal.

fix(modal): Add exception to modal enter animation

---

modules/_labs/menu/react/lib/MenuItem.tsx
modules/_labs/menu/react/stories/stories.tsx
modules/_labs/menu/react/stories/stories_visualTesting.tsx
modules/menu/css/stories.tsx

Fixes #851 
This PR updates the MenuItem styles in the Labs Menu component to keep consistent spacing around icons. I also updated and added a visual test. And I verified that the CSS version of the Menu component does not have this issue.
`modules/_labs/menu/react/lib/MenuItem.tsx`
* pull down this branch locally
* run `yarn start`
* visit `http://localhost:9001/?path=/story/labs-menu-react--with-icons`
* visit `http://localhost:9001/?path=/story/testing-react-labs-menu--menu-item-states`
n/a
applicable

fix(menu): Update MenuItem icon styles

---

.storybook/preview-head.html
modules/_labs/core/react/stories/stories.tsx
modules/_labs/core/react/stories/stories_visualTesting.tsx
modules/banner/css/stories.scss
modules/banner/css/stories.tsx
modules/button/css/stories.tsx
modules/card/css/stories.tsx
modules/common/react/stories/stories_direction.tsx
modules/core/css/stories.tsx

In Storybook, we are doing a universal selector for children of a `<section>` and adding a margin. This was probably for convenience purposes. However, this means that any `section` rendered in a story would universally apply a margin to their children.
For something like `SidePanel` (#866), **it is a section** by default so this would have unintentional layout behaviors in a story.
The fix is to remove the universal selector for `section` and apply the class name `.story` to whatever stories used `section` for this convenience since it does the same thing. All-in-all this smells like some legacy stuff that we just need to get rid of.
Definitely would like to merge this before #866 if possible so I'm going to mark that PR "blocked by" this one.
applicable

docs: Remove universal selector for section elements

---

modules/_labs/side-panel/react/lib/SidePanel.tsx

This PR addresses a simple alteration to the specs that change the top spacing of the IconButton from 32px to 24px.

fix(side-panel): Update Toggle spacing

---

.travis.yml
package.json
utils/create-component/createComponent.js
utils/create-component/createReactModule.js
utils/promote-component.js
utils/publish-canary.js
yarn.lock

Swap `node-cmd` for `child_process.exec` (it's the same underlying function). Clean up unused require statements and update to Node 12 to polish off #903, this increases the buffer size as part of Node updates so we removed that option arg in the codebase.

ci: Use exec instead of node-cmd

---

utils/create-component/createComponent.js
utils/create-component/createCssModule.js
utils/create-component/createReactModule.js

The create component scripts were still dependent on `node-cmd` which was removed here: https://github.com/Workday/canvas-kit/commit/bc2f1f499736d6b792c3eccc05e7bca93b83c817#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L95
Also, we still need to use the `colors` module for our cli coloring which was removed here: 
https://github.com/Workday/canvas-kit/commit/bc2f1f499736d6b792c3eccc05e7bca93b83c817#diff-cf53da1297de5bd1a9a1f27c12e693097fcad3810a132ab41d49b4a469c0fdf6L4

chore: Fix create component scripts

---

modules/select/react/lib/Select.tsx
modules/select/react/spec/Select.spec.tsx

A `Select` should support a single `SelectOption` child.

fix(select): Allow a single option

---

package.json
yarn.lock

Something about #897 has been causing a non-deterministic transient dependency issue in some environments. For some reason, `@emotion/styled-base` is not installed under some circumstances, even though it is a dependency of `@emotion/styled` (which is used in many of our components). We were unable to track down the source of the issue, so I've temporarily added this package as a workspace dependency to get our master builds passing again.

fix: Add Emotion dependency to fix transient dep issue

---

.storybook/main.js
package.json
yarn.lock

In #897 I inadvertently disabled postcss transpilation, but only for storybook builds. It didn't show up until we tried to upload the built storybook to chromatic. The problem came from switching from a custom webpack rule to `@storybook/preset-css`. I've gone back to a custom rule (based on the simple preset) and it should fix the issue.

fix: Re-enable postcss for storybook builds to transpile svg-load

---

modules/_labs/menu/react/lib/Menu.tsx

Closes #859.
Our documentation describes behavior which the Menu component was not following. It should auto-collapse the width based on the content, but it was using an arbitrary minimum width. This PR removes the `min-width` style from being applied.
applicable
Before:
After:

fix(menu): Remove minimum width and collapse around the content

---

modules/common/react/lib/styles/hideMouseFocus.ts

Fixes #925
I went through many iterations testing with the following code:
```ts
const temp = {
'&:focus': {
background: 'red',
},
...mouseFocusBehavior({
'&:focus': {
backgroundColor: 'blue',
},
}),
};
const Div = styled('div');
const Foo = Div(temp);
const styles = css(
mouseFocusBehavior({
'&:focus': {
outline: 'none',
},
})
);
```
I made sure that `mouseFocusBehavior` works for both `styled` and `css`.

fix(common): Fix mouseFocusBehavior type issue

---

modules/_labs/README.md
modules/_labs/breadcrumbs/react/README.md
modules/_labs/color-picker/react/README.md
modules/_labs/combobox/react/README.md
modules/_labs/core/react/README.md
modules/_labs/drawer/react/README.md
modules/_labs/header/react/README.md
modules/_labs/menu/react/README.md
modules/_labs/pagination/react/README.md
modules/_labs/select/react/README.md
modules/_labs/side-panel/react/README.md
modules/_labs/tabs/react/README.md
utils/create-component/createComponent.js
utils/create-component/templates/css/readme.js
utils/create-component/templates/react/readme.js

docs: Standardize README badges for Labs components

---

utils/create-component/createComponent.js
utils/create-component/createCssModule.js
utils/create-component/createReactModule.js
utils/create-component/templates/react/stories_VisualTesting.js

Our createComponent script was bombing out with `TypeError: exec is not a function` due to incorrect `require` statements for `exec`. Originally, `node-cmd` was used to run commands, but it was removed as a dependency in favor of `exec` in #908. However, the `require` statements in the createComponent scripts weren't updated to use `exec` until #912. This PR adds the necessary destructuring to get those `require` statements working.
It also fixes a path issue with the `stories_VisualTesting` template.

fix: Fix create component scripts

---

modules/form-field/react/README.md

The example in the `FormField` Readme is uh... not super helpful, or at least not copy/paste ready. I updated it.
applicable

chore(form-field): Update FormField Readme

---

modules/badge/react/README.md
modules/badge/react/lib/CountBadge.tsx
modules/badge/react/spec/CountBadge.spec.tsx
modules/badge/react/stories/stories.tsx
modules/badge/react/stories/stories_visualTesting.tsx

Resolves #936 
This PR adds functionality for custom limits to format the displayed count in `CountBadge`. I also added a test and updated the docs.
applicable

Add custom limit to CountBadge

---

modules/_labs/breadcrumbs/react/package.json
modules/_labs/color-picker/react/package.json
modules/_labs/combobox/react/package.json
modules/_labs/drawer/react/package.json
modules/_labs/header/react/package.json
modules/_labs/menu/react/package.json
modules/_labs/pagination/react/package.json
modules/_labs/select/react/package.json
modules/_labs/side-panel/react/package.json
modules/avatar/react/package.json
modules/banner/css/package.json
modules/banner/react/package.json
modules/button/css/package.json
modules/button/react/package.json
modules/checkbox/react/package.json
modules/color-picker/react/package.json
modules/common/react/package.json
modules/form-field/css/package.json
modules/icon/react/package.json
modules/page-header/react/package.json
modules/popup/react/package.json
modules/segmented-control/react/package.json
modules/select/react/package.json
modules/side-panel/react/package.json
modules/status-indicator/react/package.json
modules/text-input/react/package.json
modules/toast/react/package.json
modules/tooltip/react/package.json

This PR updates `@workday/canvas-system-icons-web` to the latest (1.0.41) across all packages that have it as a dependency.
applicable

chore: Update @workday/canvas-system-icons-web dependency

---

modules/skeleton/react/README.md
modules/skeleton/react/lib/parts/skeletonHeader.tsx
modules/skeleton/react/lib/parts/skeletonShape.tsx
modules/skeleton/react/lib/parts/skeletonText.tsx
modules/skeleton/react/stories/stories.tsx

This change exposes the background color of the skeletons as a prop that can be changed as needed. Requested by #757.
The implementation allows skeleton components (shape, text, and header) to be colored individually.
Any advice/criticism on the PR/change is welcome. If I need to change some other documentation as well, please let me know.

feat(skeleton): Add option for different skeleton colors

---

modules/common/react/lib/utils/components.ts
modules/common/react/lib/utils/index.ts
modules/common/react/lib/utils/mergeCallbacks.ts
modules/common/react/lib/utils/models.ts
modules/common/react/lib/utils/useMount.ts
modules/common/react/lib/utils/useUniqueId.ts
modules/common/react/spec/components.spec.tsx
modules/common/react/spec/models.spec.tsx
utils/create-component/createReactModule.js
utils/create-component/nameUtils.js
utils/create-component/templates/react/SSR.js
utils/create-component/templates/react/component.content.js
utils/create-component/templates/react/component.js
utils/create-component/templates/react/component.target.js
utils/create-component/templates/react/index.js
utils/create-component/templates/react/model.js
utils/create-component/templates/react/stories.js
utils/create-component/templates/react/stories_VisualTesting.js
utils/custom-lint-rules/restricted-imports.js
utils/custom-lint-rules/restricted-imports.spec.ts

* Add `createComponent` helper functions
* Add model types and helper functions
* Update new component templates to use Compound Component helper functions
This PR adds compound component helper functions to help with creating compound components. These utility functions take care of complexity around Typescript, enforce ref forwarding, enable element remapping, etc. Documentation for creating compound components will follow.
applicable
Still to be done:

feat: Add compound component utility functions

---

modules/modal/react/README.md
modules/modal/react/lib/ModalContent.tsx
modules/modal/react/spec/Modal.spec.tsx
modules/popup/react/README.md

Allow for custom aria-label attribute on the close button for the modal.
Fixes #955
`<Modal closeButtonAriaLabel="Example Label" />`

feat: Add closeButtonAriaLabel to Modal Component

---

.storybook/main.js
.storybook/mdx-code-block-rewrite.js
.storybook/whole-source-loader.js
modules/card/react/lib/Card.tsx
modules/card/react/stories/card.stories.mdx
modules/card/react/stories/examples/Default.tsx
modules/card/react/stories/examples/Depth.tsx
modules/card/react/stories/examples/WithNoPadding.tsx

Added MDX helpers to improve Storybook Docs documentation and align with the new Canvas site documentation.
- Added `ExampleCodeBlock` that takes in an example file and will show it live and set the source code to be the whole file. This makes it so stories are fully copy/pasteable into product
- Added `PropsTable` component that creates a table of arguments.
- Updated Card docs with this style
Notice the code block includes `import` statements.

docs: Improve documentation

---

.storybook/mdx-code-block-rewrite.js

Before a story named 'NamedKeys' would show up to Storybook as 'NamedKeys'. This change will present the story as 'Named Keys' like it should.

docs: Fix Story names

---

.storybook/preview-head.html

Fonts aren't preloading with the following warnings:
> A preload for 'https://design.workdaycdn.com/beta/assets/fonts@1.0.0/roboto/ttf/Roboto-Regular.ttf' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.
Since preloads are failing, we're also getting the following warnings:
> The resource https://design.workdaycdn.com/beta/assets/fonts@1.0.0/roboto/ttf/RobotoMono-Regular.ttf was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
This fixes both warnings and makes sure Chromatic is correctly preloading fonts.

fix: Add crossorigin to font preloads

---

API_PATTERN_GUIDELINES.md
CONTRIBUTING.md
CREATING_COMPOUND_COMPONENTS.md

Doc to create new compound components. This document builds on the doc introduced in #937. It is a step-by-step guide to building components from scratch with code sandbox examples between steps.
Rendered docs can be found here: https://github.com/Workday/canvas-kit/blob/67d88f7bf7a21d394e267e3bbefe6276950d9ef7/CREATING_COMPOUND_COMPONENTS.md

docs: Add compound Component Creation Doc

---

modules/popup/react/lib/Popup.tsx
modules/popup/react/package.json
modules/popup/react/stories/stories.tsx
modules/popup/react/stories/stories_VisualTesting.tsx

The close icon in Popup wasn't responding to RTL. So now we're using updating our internal styled function.
applicable

fix(popup): Fix Popup icon RTL bug

---

5.0-MIGRATION-GUIDE.md
modules/css/README.md
modules/css/action-bar/README.md
modules/css/badge/README.md
modules/css/banner/README.md
modules/css/button/README.md
modules/css/card/README.md
modules/css/checkbox/README.md
modules/css/common/README.md
modules/css/core/README.md
modules/css/form-field/README.md
modules/css/icon/README.md
modules/css/layout/README.md
modules/css/loading-animation/README.md
modules/css/menu/README.md
modules/css/modal/README.md
modules/css/page-header/README.md
modules/css/popup/README.md
modules/css/radio/README.md
modules/css/select/README.md
modules/css/table/README.md
modules/css/text-area/README.md
modules/css/text-input/README.md
modules/css/tooltip/README.md

Adds deprecation messages to the CSS readmes and updates the migration guide with relative info. Also adds missing info about the slash imports change made in #992 and how consumers should use the codemod.

Deprecate CKCSS and update migration guide

---

utils/publish-canary.js

Fixes slack update message for new canary builds
Before:
```
New canary build published (v5.0.0-beta.0-next.9+52852d7b)
Merge commit 52852d7b
yarn add @workday/canvas-kit-{module}@5.0.0-beta.0-next.9+52852d7b
or
yarn add @workday/canvas-kit-{module}@next
```
After:
```
New canary build published (v5.0.0-beta.0-next.9+52852d7b)
Merge commit 52852d7b
yarn add @workday/canvas-kit-{module}@5.0.0-beta.0-next.9+52852d7b
or
yarn add @workday/canvas-kit-{module}@prerelease-next
```
(note `next` > `prerelease-next` in last line)

ci: Fix canary dist-tag for prerelease canaries in slack message

---

modules/codemod/lib/v5/renameButtonRefs.ts
modules/codemod/lib/v5/spec/renameButtonRefs.spec.ts
modules/docs/mdx/5.0-MIGRATION-GUIDE.mdx

Fixes `renameButtonRef` to only include named imports from the CK button module. Handles renames. Tested on our codebase.

fix: Scope buttonRef codemod to only Button components

---

modules/tooltip/react/lib/Tooltip.tsx
modules/tooltip/react/spec/Tooltip.spec.tsx

fix(tooltip): Allow aria-label pass-through in muted tooltips

---

utils/create-component/createReactModule.js
utils/create-component/templates/react/package.js

This was accidentally left in from when the `package.json` was in source control.

chore: Remove package.json from create component script

---

modules/labs-react/tabs/stories/Tabs.stories.mdx
modules/labs-react/tabs/stories/examples/SinglePanel.tsx

Update the `SinglePanel` example to use a hosted model. This came up as a confusing point in our workshop - if we hoist the model, why not use the model?

docs(tabs): Update single tabs panel example

---

cypress/integration/Modal.spec.ts
cypress/integration/Popup.spec.ts
modules/modal/react/lib/ModalContent.tsx
modules/modal/react/package.json
modules/modal/react/stories/stories.tsx

Before the fix, when a tooltip is opened on top of a modal, it required two clicks to close the tooltip and then the modal. With the fix, a single click will close a tooltip and the modal underneath. 
applicable

fix(popup): Allow tooltips to close alongside modals on click outside

---

modules/_labs/combobox/react/lib/Combobox.tsx

Resolves [1075](https://github.com/Workday/canvas-kit/issues/1075). Added default maxHeight: 200 and overflowY: auto like Drowdown Menu to control the overflow of large items.
applicable

feat(comboxbox):Added default maxHeight to autocomplete container

---

tsconfig.json

In #1029, the following was added to our root tsconfig:
```
"baseUrl": "./",
"paths": {
"@workday/canvas-kit-react*": ["modules/react*"],
"@workday/canvas-kit-labs-react*": ["modules/labs-react*"],
"@workday/canvas-kit-preview-react*": ["modules/preview-react*"]
}
```
Since we're using labs components (e.g. `Box`) inside of our main module, this causes the `tsc` build to compile files from both `labs-react` and `react`. Because of this, the dist folder now looks like this:
```
dist/
commonjs/
labs-react/
box/
react/
action-bar/
avatar/
...
es6/
(the same as above)
```
instead of:
```
dist/
commonjs/
action-bar/
avatar/
...
es6/
(the same as above)
```
- `@workday/canvas-kit-react` package.json references `"module": "/dist/es6/index.js"` (and similarly for main/commonjs)
- This file …

build: Fix slash imports build pathing

---

modules/preview-react/package.json

It was reported that we have some circular deps in v5. This addresses some* of those.
* We mistakenly had `@workday/canvas-kit-labs-react` as a full dependency of `@workday/canvas-kit-preview-react`. It was only a dev dependency used for one test. This has been updated.
There are two cyclical dependencies remaining:
- `@workday/canvas-kit-labs-react -> @workday/canvas-kit-preview-react -> @workday/canvas-kit-labs-react`
- This should not cause any issues as `labs` is only a dev dep of `preview  `
- `@workday/canvas-kit-react -> (nested cycle: @workday/canvas-kit-labs-react -> @workday/canvas-kit-preview-react -> @workday/canvas-kit-labs-react) -> @workday/canvas-kit-react`
- This should not cause any issue because it is just a nested version of the previous cycle.
Unfortunately this is a …

chore: Fix circular dep in preview module

---

modules/react/tokens/index.ts

Resolves #1109
Previously we were parsing out colors from `canvas-colors-web` like this:
```ts
const {default: colors, gradients, ...semanticColors} = canvasColorsWeb;
```
And exporting them from a default `canvas` object like this:
```ts
const canvas = {
colors,
depth,
space,
type,
fontFamily,
monoFontFamily,
...semanticColors,
};
```
TS throws an error because `...semanticColors` has a `color` key which is overwrites the default export. This happened to work because the colors in the default export and the `colors` key were identical.
To resolve this, we're removing the default export and explicitly import each color key.
applicable

fix(tokens): Fixes color token exports

---

modules/react/index.ts

Some how these two exports weren't automatically added to the `@workday/canvas-kit-react` entry point (the `create-component` script should do this for us). This adds the correct `Banner` and `Disclosure` exports so they can now be imported directly from the bundle rather than having to use slash imports.

fix: Add missing exports for CKR bundle

---

cypress/integration/Modal.spec.ts
cypress/integration/Popup.spec.ts
modules/react/modal/stories/Modal.stories.mdx
modules/react/modal/stories/examples/CustomTarget.tsx
modules/react/popup/lib/hooks/usePopupTarget.ts
modules/react/popup/stories/Popup.stories.mdx
modules/react/popup/stories/examples/CustomTarget.tsx

- Remove ref forwarding requirement in `Popup.Target`, `Modal.Target`, and `Dialog.Target`
- Add examples to show using custom targets for `Popup` and `Modal`
- Add Cypress specifications for new examples
Fixes #1114

fix(popup): Remove ref fowarding requirement in Popup.Target

---

modules/tooltip/react/lib/OverflowTooltip.tsx

Fixes #1125
The intent of the overflow tooltip is to first find an ellipsis element, then fallback to finding an overflow element if no ellipsis element was found. The `findEllipsisElement` is intended to be a recursive function, but accidentally called `findOverflowElement` instead of `findEllipsisElement`.

fix(tooltip): Fix overflow ellipsis detection

---

cypress/integration/Modal.spec.ts
cypress/support/commands.ts
modules/docs/utils/get-specifications.js
modules/modal/react/stories/stories_testing.tsx
modules/popup/react/lib/focus-trap-js.d.ts
modules/popup/react/lib/focus-trap-js.js
modules/popup/react/lib/useFocusTrap.ts
modules/popup/react/package.json

Fixes #1097
The library code has been copied locally using the code from https://github.com/alexandrzavalii/focus-trap-js/pull/11
This is fine for v4, but will require some rework in v5. v5 introduces `useFocusRedirect` with similar logic. It makes sense to move code from the `focus-trap-js` library into the common module that can handle both focus trapping and focus redirecting.

fix(modal): Fix focus trap when Modal contains an iframe

---

modules/_labs/breadcrumbs/react/lib/Breadcrumbs/Dropdown/Menu.tsx
modules/_labs/breadcrumbs/react/lib/Breadcrumbs/Dropdown/MenuItemLink.tsx
modules/_labs/breadcrumbs/react/lib/Breadcrumbs/List/Collapsible.tsx
modules/_labs/breadcrumbs/react/lib/Breadcrumbs/types.ts
modules/_labs/breadcrumbs/react/spec/Breadcrumbs.spec.tsx

Resolves #1070
`onAction` event handlers weren't properly supported in `Breadcrumb.MenuItemLink`s like they were in `Breadcrumb.Link`s. This PR fixes that.
`modules/_labs/breadcrumbs/react/lib/Breadcrumbs/Dropdown/MenuItemLink.tsx`
* pull up storybook
* visit `?path=/story/labs-breadcrumbs-react--collapsible`
* click on the `Ledger Account is “4200: Property”` menu item
* see an alert fire
* click on the `2018_08_28_Summary_of_Annual_Recurring_Revenue` menu item
* see the page redirect
applicable

fix: Resolve Breadcrumb MenuItemLink onAction bug

---

modules/checkbox/react/lib/Checkbox.tsx

Resolves #1134
When really long text was added as the checkbox label, the space between the box and the label overlapped. This PR fixes that.
applicable

fix: Fix Checkbox width bug

---

.travis.yml
utils/publish-canary.js

Closes #1119. 
- Adds support for canary builds on `support/v*` branches under the dist tag `support-next`.
- Adds a new release stage for support releases that uses the `support` dist tag so we don't temporarily take over `latest`

ci: Use `support` dist tags for for support branches

---

modules/react/common/README.md
modules/react/common/lib/utils/components.ts
modules/react/common/spec/components.test-d.tsx
modules/react/dialog/lib/DialogCard.tsx
modules/react/dialog/lib/DialogPopper.tsx
modules/react/modal/lib/Modal.tsx
modules/react/modal/lib/ModalCard.tsx
modules/react/modal/lib/ModalHeading.tsx
modules/react/popup/lib/PopupCard.tsx
modules/react/popup/lib/PopupCloseIcon.tsx
modules/react/toast/lib/Toast.tsx

Fixes #1145 
```tsx
ExtractProps<typeof Card>; // React.HTMLAttributes<HTMLDivElement> & CardProps
ExtractProps<typeof Card, 'aside'>; // React.HTMLAttributes<HTMLElement> & CardProps
ExtractProps<typeof Card, never>; // CardProps
```
Usage:
```tsx
import {ExtractProps} from '@workday/canvas-kit-react/common';
import {TextInput} from '@workday/canvas-kit-react/text-input';
export interface MyComponentProps extends ExtractProps<typeof TextInput> {
myExtraProp: boolean
}
const MyComponent = ({ myExtraProp, ...props}: MyComponentProps) => {
// do something with `myExtraProp`
return <TextInput {...props} />
}
```

feat(common): Add HTML attribute interface to ExtractProps

---

modules/react/common/lib/utils/changeFocus.ts
modules/react/dialog/lib/Dialog.tsx

- Update `changeFocus` to take any input and explicitly test for `HTMLElement`
- Update `Dialog` and `Modal` types to take optional model config.

fix: ChangeFocus takes any input and Dialog/Modal accepts model config

---

modules/react/pagination/stories/pagination.stories.mdx

This commit fixes a broken link in the `pagination.stories.mdx` file.
This commit fixes a broken link in the `pagination.stories.mdx` file.

docs: Fixed broken link in pagination.stories.mdx

---

modules/react/package.json

In 4.x we made a change (#974) to add support for React 17. Somehow, in the #992 Slash Imports PR, this [peer dependency regressed](https://github.com/Workday/canvas-kit/pull/992/files#diff-3be175031a0046a5ad6ec23a2bfdea7e7d8e996dc4e6846a8f8d885ddc4b0edeR46), and we missed it.
This PR fixes the main package to support React 17 again. I also validated the other packages are supporting React 17 as well.
applicable

fix: Add support for React 17 in main

---

modules/popup/react/lib/usePopupStack.ts
modules/popup/react/stories/stories_Popper_testing.tsx

Fixes #1158
- Add `dir` to `usePopupStack` to automatically set direction for portalled popups
Before:
After:

fix(popup): Fix RTL rendering for popups

---

.travis.yml

This PR will enable automatic rebaselining in support branches. Without this change, every PR set to be merged to a support branch will have to re-accept the same changes in every PR after a visual change.

ci: Add Chromatic baseline to support branches

---

modules/react/toast/lib/Toast.tsx
modules/react/toast/stories/examples/RTL.tsx
modules/react/toast/stories/stories_visualTesting.tsx
modules/react/toast/stories/toast.stories.mdx

Resolves #1225 
This PR fixes some margins when rendering the toast in RTL, see related issue [#1225](https://github.com/Workday/canvas-kit/issues/1225). The solution was to switch to the `styled` wrapper to take advantage of automatic rtl flipping.
Before fix:
After fix:

fix: Update toast to properly render rtl

---

modules/react/button/README.md
modules/react/button/lib/IconButton.tsx
modules/react/button/lib/PrimaryButton.tsx
modules/react/button/lib/SecondaryButton.tsx
modules/react/button/lib/TertiaryButton.tsx
modules/react/button/lib/ToolbarDropdownButton.tsx
modules/react/button/lib/ToolbarIconButton.tsx
modules/react/button/lib/parts/ButtonLabelIcon.tsx
modules/react/button/stories/icon-button/IconButton.stories.mdx
modules/react/button/stories/icon-button/examples/MirroredIcon.tsx
modules/react/button/stories/visual-testing/stories_IconButton.tsx
modules/react/button/stories/visual-testing/stories_ToolbarDropdownButton.tsx
modules/react/button/stories/visual-testing/stories_ToolbarIconButton.tsx
modules/react/button/stories/visual-testing/utils.tsx
modules/react/icon/README.md
modules/react/icon/lib/AccentIcon.tsx
modules/react/icon/lib/AppletIcon.tsx
modules/react/icon/lib/Graphic.tsx
modules/react/icon/lib/Icon.tsx
modules/react/icon/lib/Svg.tsx
modules/react/icon/lib/SystemIcon.tsx
modules/react/icon/lib/SystemIconCircle.tsx
modules/react/icon/stories/stories.tsx

Co-authored-by: Stefan Urosevic <stefanuros@gmail.com>
Co-authored-by: Alan B Smith <a.bax.smith@gmail.com>
Resolves #751
This PR updates @stefanuros' original PR (#949) to Canvas Kit v5. There were a lot of file changes with buttons, and this was the more simple route to resolve the conflicts. It also makes some minor alterations to the original PR.
- `mirror` and `mirrorIcon` prop names have been updated to `shouldMirror` and `shouldMirrorIcon` respectively
- tests and docs have been updated to reflect this change as well
- small doc tweaks were added
`modules/react/icon/lib/Svg.tsx`
This PR touches quite a few components. I would personally start at the root with `Svg`. Below is a tree view of how these components are related. Each nested component consumes the components higher in the …

feat(icon): Add shouldMirror prop to icons

---

.github/workflows/forward-merge.yml

This change will enable forward merging to the `prerelease/v6` branch

ci: Update forward merge to support v6

---

cypress/integration/Tooltip.spec.ts
modules/react/tooltip/lib/OverflowTooltip.tsx
modules/react/tooltip/stories/examples/Ellipsis.tsx

This change adds support for the following use case:
```tsx
<OverflowTooltip>
<SomeCustomComponent />
</OverflowTooltip>
```
The problem was `react-innertext` was used to determine the text of the content inside the `OverflowTooltip`. `react-innertext` uses VDOM `children` to determine text. But in this case, `children` has no text, just a single child of type `SomeCustomComponent`. Therefore calculated `titleText` is `''` and the tooltip will never show. The fix is to use [DOM innerText](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText) instead which should work regardless of React JSX structure. This should be safe because the text is always calculated based on `onFocus` or `onMouseEnter` events; the same time that overflow is calculated.
The `Ellipsis` example was …

fix(tooltip): Update OverflowTooltip to support non-elements

---

modules/react/tooltip/lib/OverflowTooltip.tsx
modules/react/tooltip/lib/useTooltip.tsx

IE11 doesn't define the `children` property in `Element`. It defines `children` as part of the `HTMLElement` interface. This means that `findEllipsisElement` will fail if `OverflowTooltip` contains any SVG element. An issue has been filed with MDN to update their docs. The code now does specific testing against an `HTMLElement` for `innerText` (not defined on `SVGElement` in any browser) as well as testing the presence of `.children` to avoid IE11 crashing on SVG elements.
More info here: https://github.com/mdn/content/issues/8890

fix(tooltip): Fix OverflowTooltip with SVG in IE11

---

modules/codemod/lib/v6/deprecateCookieBanner.ts
modules/codemod/lib/v6/index.ts
modules/codemod/lib/v6/spec/deprecateCookieBanner.spec.ts
modules/docs/mdx/6.0-MIGRATION-GUIDE.mdx
modules/react/cookie-banner/README.md
modules/react/cookie-banner/index.ts
modules/react/cookie-banner/lib/CookieBanner.tsx
modules/react/cookie-banner/stories/stories.tsx

Resolves #1214
Deprecate CookieBanner
This update soft-deprecates all exports from `canvas-kit-labs-react/cookie-banner`. These changes are handled automatically by the v6 codemod. Please refer to the v6 migration guide for more information.
---
This PR:
- Updates `CookieBanner` to `DeprecatedCookieBanner`
- Updates `CookieBannerProps` to `DeprecatedCookieBannerProps`
- Updates the `CookieBanner` README
- Adds deprecation information to the V6 migration guide
- Adds a soft-deprecation codemod for `CookieBanner`
- Adds a test for the codemod
`modules/react/cookie-banner/lib/CookieBanner.tsx`
applicable

feat(cookie-banner): Deprecate CookieBanner

---

modules/codemod/lib/v6/deprecateHeader.ts
modules/codemod/lib/v6/index.ts
modules/codemod/lib/v6/spec/deprecateHeader.spec.ts
modules/codemod/lib/v6/utils/index.ts
modules/docs/mdx/6.0-MIGRATION-GUIDE.mdx
modules/labs-react/header/README.md
modules/labs-react/header/index.ts
modules/labs-react/header/lib/GlobalHeader.tsx
modules/labs-react/header/lib/Header.tsx
modules/labs-react/header/lib/parts/DubLogoTitle.tsx
modules/labs-react/header/lib/parts/WorkdayLogoTitle.tsx
modules/labs-react/header/lib/parts/index.ts
modules/labs-react/header/lib/shared/themes.tsx
modules/labs-react/header/lib/shared/types.tsx
modules/labs-react/header/spec/GlobalHeader.spec.tsx
modules/labs-react/header/spec/SSR.spec.tsx
modules/labs-react/header/stories/stories.tsx
modules/react/side-panel/stories/stories.tsx

Resolves #1190
Deprecate Header exports
This update soft-deprecates all exports from `canvas-kit-labs-react/header`. These changes are handled automatically by the codemod transform included in this PR. Please refer to the v6 migration guide for more information.
---
This PR:
- Adds a codemod to update header exports
- Updates the v6 migration guide
- Deprecates header components
- Adds console warnings to `DubLogoTitle`, `GlobalHeader`, `Header`, and `WorkdayLogoTitle`
- Adds deprecation JSDoc notes for all labs/header exports
- Renames Header and related exports
- `DubLogoTitle` => `DeprecatedDubLogoTitle`
- `GlobalHeader` => `DeprecatedGlobalHeader`
- `Header` => `DeprecatedHeader`
- `HeaderHeight` => `DeprecatedHeaderHeight`
- `HeaderTheme` => `DeprecatedHeaderTheme`
- `HeaderVariant` …

feat: Deprecate Header and Global Header

---

README.md

Seems like you're not using travis anymore for builds?
or at least I can't find it, in which case we should close this PR and update the link and the badge image instead
lmk
Remove Travis badge since Travis is no longer used.

docs: Remove travis badge [skip release]

---

modules/react/tabs/lib/Tab.tsx

Fixes: #1326
Update the tab Emotion styled to use the `[aria-selected=true]` CSS selector instead of a selector based on internal state. This will allow for style overrides.

fix(tabs): Allow consumers to style the selected tab

---

cypress/integration/Tooltip.spec.ts
modules/react/tooltip/lib/OverflowTooltip.tsx
modules/react/tooltip/spec/OverflowTooltip.spec.tsx
modules/react/tooltip/stories/examples/Ellipsis.tsx
modules/react/tooltip/stories/stories_testing.tsx

Previous fix for OverflowTooltip issue in IE 11 only partially solved the problem:
https://github.com/Workday/canvas-kit/pull/1263
Fixes: IE11 OverflowTooltip 
---

fix(tooltip): Fix findEllipsisElement IE11

---

cypress/integration/Button.spec.ts
modules/docs/mdx/6.0-MIGRATION-GUIDE.mdx
modules/react/button/lib/PrimaryButton.tsx
modules/react/button/lib/parts/ButtonContainer.tsx
modules/react/button/lib/parts/ButtonLabelIcon.tsx
modules/react/button/lib/types.ts
modules/react/button/stories/button/Button.stories.mdx
modules/react/button/stories/button/examples/PrimaryInverse.tsx
modules/react/button/stories/button/examples/SecondaryInverse.tsx
modules/react/button/stories/button/examples/TertiaryInverse.tsx
modules/react/button/stories/visual-testing/stories_PrimaryButton.tsx

Resolves: #1321
This change updates our `PrimaryButton` styles. For more information, please see the V6 migration guide.
---
Below is a list of all relevant changes:
- Update the v6 migration guide
- Use 40% opacity for disabled styling on the entire container
- Make sure it doesn't have any adverse effects on themed buttons
- Create new inverse variant - view spec for details
- Decrease padding between icon and text (12px to 8px)
- Decrease container padding outside the icon (28px to 24px)
- Decrease icon size (24px to 20px) - button container height will be the same
- Add icon support – icons should be 20 x 20px
- Create a new extra small size - view specs for details

feat(button): Update PrimaryButton for v6

---

modules/docs/mdx/6.0-MIGRATION-GUIDE.mdx
modules/react/button/lib/SecondaryButton.tsx
modules/react/button/stories/visual-testing/stories_SecondaryButton.tsx

Resolves: #1322 
This change updates our `SecondaryButton` styles. For more information, please see the V6 migration guide.
---
#1331 Should be reviewed and merged before this PR.
Below is a list of all relevant changes:
- Update the v6 migration guide
- Decrease padding between icon and text (12px to 8px)
- Decrease container padding outside the icon (28px to 24px)
- Decrease icon size (24px to 20px) - button container height will be the same
- Add icon support – icons should be 20 x 20px
- Create a new extra small size - view specs for details

feat(button): Update SecondaryButton for v6

---

modules/docs/mdx/6.0-MIGRATION-GUIDE.mdx
modules/react/button/lib/TertiaryButton.tsx
modules/react/button/lib/parts/ButtonContainer.tsx
modules/react/button/lib/types.ts
modules/react/button/stories/visual-testing/stories_TertiaryButton.tsx

Resolves #1323
This change updates our `TertiaryButton` styles. For more information, please see the V6 migration guide.
---

feat(button): Update Tertiary Buttons for v6

---

modules/codemod/index.js

Fix the incorrect usage of `spawn` from #1340. This update uses `spawn`'s streaming API instead of `exec`s API.

fix: Fix codemod command

---

cypress/integration/Popup.spec.ts
cypress/integration/Tooltip.spec.ts
modules/react/tooltip/lib/Tooltip.tsx
modules/react/tooltip/lib/useTooltip.tsx
modules/react/tooltip/spec/Tooltip.spec.tsx
modules/react/tooltip/spec/useTooltip.spec.tsx
modules/react/tooltip/stories/Tooltip.stories.mdx
modules/react/tooltip/stories/examples/DelayedTooltip.tsx

This PR introduces the default delay time of 300ms for showing a tooltip, and adds the ability to control the delay time for showing and hiding the tooltip.
Currently, Canvas-Kit tooltip doesn't support delayed showing and hiding. As a result, the tooltip appears as soon as the anchor item is hovered. I don't think that's the typical behavior of a tooltip, it's redundant most of the time, and makes the UI look busy. I chose 500ms as the default delay per my brief research (listed below in References) on tooltip behavior
This change could cause visual regression tests to fail if a screen shot is taken expecting a tooltip to show immediately. Your visual regression will either have to add an explicit wait of 300ms, or change the delay to 1ms only under test. …

fix(tooltip): Add delay to Tooltip show and hide

---

cypress/integration/Tabs.spec.ts
modules/react/tabs/lib/overflow/useOverflowTarget.tsx

The "More" button in tabs should be focusable so that keyboard users and screen reader users can access it.

fix(tabs): Fix focusability of the More button

---

modules/react/popup/lib/hooks/useReturnFocus.tsx

Fixes: https://github.com/Workday/canvas-kit/issues/1292

docs(popup): Fix typo in JSDoc description for useReturnFocus

---

.storybook/preview.js
modules/docs/mdx/6.0-MIGRATION-GUIDE.mdx
modules/react/_examples/stories/GlobalHeader.stories.mdx
modules/react/_examples/stories/PageHeader.stories.mdx
modules/react/_examples/stories/examples/GlobalHeader.tsx
modules/react/_examples/stories/examples/PageHeader.tsx

Resolves: #1362, #1363  
Now that we've deprecated  `PageHeader` and `GlobalHeader` components in v6, we'd like to provide an example for users to use so that they can migrate from the deprecated component.

docs: Add headers examples to Storybook

---

modules/preview-react/package.json

Add `formik` and `yup` to `preview-react`'s dev dependencies.
---
I accidentally removed `formik` and `yup` dev dependencies from `preview-react` when resolving the merge conflict. This PR adds them back.

fix: Add formik and yup back to preview dev deps

---

.github/workflows/pull-request.yml

For a more accurate verify process, I've added `visual-testing` to the verify step as a dependency.

chore: Have verify action to wait on visual tests [skip release]

---

modules/docs/mdx/5.0-MIGRATION-GUIDE.mdx

The v5 migration guide doesn't mention `ExtractProps`. This utility type was added later in the release cycle and fixed many problems we encountered and we have been suggesting `ExtractProps` for people who wrap Canvas Kit components.

docs: Add ExtractProps to the v5 migration guide

---

modules/labs-react/search-form/lib/SearchForm.tsx

Removed browsers' default autocomplete as it is overlapping with the search form's autocomplete results.

fix(search-form): Remove default autocomplete

---

modules/codemod/package.json
package.json
yarn.lock

Pin `colors` to unaffected version.
---
The maintainer of faker.js and colors.js went rogue and introduced some breaking changes into the latest patch versions of those modules. 
The code affecting `colors` is this infinite loop that was introduced: https://github.com/Marak/colors.js/commit/5d2d242f656103ac38086d6b26433a09f1c38c75#diff-92bbac9a308cd5fcf9db165841f2d90ce981baddcb2b1e26cfff170929af3bd1R18
I'm not sure what the long term strategy will be for CKR (maybe moving to a different library for console colors like [chalk](https://www.npmjs.com/package/chalk)) but this just makes sure that the local dev environments and CI does not go bust in case it pulls in the latest `colors` version.

chore: Pin colors to version 1.4.0

---

cypress.json
modules/react/popup/lib/Popper.tsx
modules/react/popup/spec/Popper.spec.tsx
modules/react/popup/stories/stories_Popper.tsx

Allow access to the `PopperJS` instance to allow resize positioning of a Popup.
Before this change, the following video would show the popup size changing, but not recentering.

fix: Allow repositioning of PopperJS instances

---

modules/preview-react/_examples/stories/SelectWithFormik.stories.mdx
modules/preview-react/_examples/stories/TextInputWithFormik.stories.mdx
modules/preview-react/_examples/stories/examples/SelectWithFormik.tsx
modules/preview-react/_examples/stories/examples/TextInputWithFormik.tsx
modules/preview-react/form-field/stories/FormField.stories.mdx
modules/preview-react/form-field/stories/examples/Select.tsx
modules/preview-react/text-input/stories/TextInput.stories.mdx

Fixes: #1434
---
This PR:
* Adds a new Preview Select with Formik example 
* Moves the TextInput with Formik example to the "Examples" section
* Adds a new Preview Select + Preview FormField example

docs: Add examples for Select and TextInput with Formik

---

modules/preview-react/form-field/lib/FormFieldHint.tsx

fix(preview): Preview FormField.Hint error text not the correct color

---

modules/popup-stack/lib/PopupStack.ts

Fixes an issue where an adapted PopupStack was never removed from the DOM

fix(popup-stack): Fix popup element removal when adapter is used

---

README.md

Correct typo in README file
---

docs: Correct typo in README file

---

modules/react/tabs/lib/TabsList.tsx

v6 removed an extra `div` in Tabs, but didn't change `margin` to `padding` in the single `div` element which caused a regression of the bottom border of the tablist.
---

fix(tabs): Add back the extending bottom border

---

modules/react/popup/lib/hooks/useDisableBodyScroll.ts

No issue raised for this, but this fixes an issue in IE 11 where the background behind a modal can sometimes remain scrollable. It seems that this is due to partial support for the overflow attribute in IE 11.
---

fix: Set overflowX and overflowY to cater for IE11 scrolling bug

---

modules/react/action-bar/lib/ActionBar.tsx

Fixes: #1509
This change updates the CSS selector for the `ChildrenContainer`. We're using [the same selector as what's used in Stack](https://github.com/Workday/canvas-kit/blob/master/modules/labs-react/layout/lib/utils/stack.ts#L10). It is also now SSR-safe by avoiding applying styles to `style` tags. If you were compensating for this bug by adding space for non-button elements in the ActionBar, you'll need to remove that adjustment.
---
Fixed:

fix(action-bar): Update CSS selector to fix spacing bug

---

modules/react/popup/lib/hooks/usePopupTarget.ts

Fixes: #1234 
Add a ref to banner component doesn't cause the ref to work. Code uses instanceof to apply ref to element rather than class instance.
This is a suggestion from @NicholasBoll
---

fix: Update usePopupTarget to apply Refs to elements not class instance

---

modules/labs-react/layout/lib/Stack.tsx
modules/labs-react/layout/stories/Stack.stories.mdx

fix(layout): Pass key to Stack.Item when using shouldWrapChildren

---

modules/react/banner/lib/Banner.tsx

Convert Banner to a functional component with ref forwarding to be compatible with compound components that use `as`.

fix(banner): Convert Banner to a functional component

---

modules/react/form-field/lib/Label.tsx

Fixes: #1537
---
The `margin-left` wasn't properly flipping for RTL. Now, because of our `styled`, it will.

fix: Add RTL support to FormField.Label

---

commitlint.config.js
modules/codemod/lib/v6/moveAndRenameSearchBar.ts
modules/codemod/lib/v6/spec/deprecateHeader.spec.ts
modules/codemod/lib/v6/spec/moveAndRenameSearchBar.spec.ts
modules/codemod/lib/v6/utils/index.ts

Fixes: #1496 
The current code mods will rename components that aren't imported from Canvas Kit. They also rename sub-components like `Skeleton.Header`. This change addresses both of these issues.
This change implements the following:
Fixed code mods that improperly rename non-Canvas Kit components as well as Canvas Kit sub-components. This typically includes non-Canvas Kit `Header` components and Canvas Kit's `Skeleton.Header` being improperly renamed in the JSX, but solves for all future cases of Canvas Kit component names.
---
Past behavior:
```jsx
import { Header as CanvasHeader } from '@workday/canvas-kit-labs-react/header';
import { Header } from './localProjectHeader';
import { Skeleton } from '@workday/canvas-kit-labs-react/skeleton';
const SomeComponent = () => {
return <> …
```

fix(codemod): Limit specifier renaming to Canvas Kit imports

---

modules/docs/utils/build-mdx.js

Fixes: #1571 
Fixes an issue in the build-mdx script where it was incorrectly rewriting a named import in `Flex.stories.mdx` to a default import.
`import {FlexStyle} from './examples/PropTables.splitprops.tsx'` was being rewritten to `import FlexStyle from './examples/PropTables.splitprops.tsx'` when instead it should NOT have been rewritten at all. Imports from splitprops files need to remain named imports.
This PR updates the regex we use to rewrite the imports to properly exclude all imports from `splitprops` files. The code change itself is very small (adds a `(?!.*splitprops)` [negative lookahead](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Assertions#other_assertions) to the regex); most of the PR is better documentation around how the regex for …

fix: Fix build mdx script to better handle splitprops files

---

modules/react/action-bar/lib/useActionBarModel.tsx

PR fixes issue with focus order for ActionBar. It was still select hidden buttons before focusing overflow menu button.

fix(action-bar): Make hidden buttons non-interactive

---

modules/react/action-bar/lib/ActionBarItem.tsx

This PR removes subcomponents from `ActionBar.Item`. Because `ActionBar.Item` is build under Button component, these subcomponents are not necessary.

fix(action-bar): Remove subcomponents from ActionBar.Item

---

jest/verifyComponent.tsx
modules/react-fonts/README.md

This cleanups our `verifyComponent`'s import for Emotion (it might be using Emotion 10 incorrectly) as well as the example imports for using `@workday/canvas-kit-react-fonts`.
Updated documentation for `@workday/canvas-kit-react-fonts` to correctly import utilities from Emotion 11 rather than Emotion 10.
---

fix: Update remaining Emotion 11 imports

---

modules/preview-react/side-panel/stories/examples/RightOrigin.tsx

Fixes: #1643 
I tested this in IE11 too; here's the link to the deployed story: https://5d854c26ba934e0020f5e98a-mqybeegohw.chromatic.com/?path=/story/preview-side-panel-react--right-origin
Here's a CodeSandbox to play with too: https://codesandbox.io/s/sidepanel-right-origin-f7peik?file=/src/RightOrigin.tsx
Before:
After:
---
Used [margin-left: auto](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-right#values) instead of absolute positioning.

docs: Update SidePanel right origin story [skip release]

---

modules/react/pagination/lib/Pagination/PageButton.tsx

Removes a console warning from `PageButton` in the Pagination component that was inadvertently introduced in #1648.

fix(pagination): Remove console warning

---

.github/workflows/release-minor.yml

Add a way to release minor versions from Github!

ci: Add CI button to release minor versions [no release]

---

modules/react/popup/lib/PopupPopper.tsx

fix: Add missing `Popper` props to `Popup.Popper`

---

modules/react/radio/stories/examples/Basic.tsx

Fixes: #1725
---
This PR:
- Updates the duplicated `value` for the fifth radio input
- Adjusts the `width` style to use a space token
- Edits the label copy to fit the language of the other inputs
`modules/react/radio/stories/examples/Basic.tsx`
- View the Radio Basic story example
**Before**
**After**
Thanks for reviewing!

docs: Fix RadioGroup Basic example

---

cypress/integration/Tooltip.spec.ts

Fixes: #1720 
The links for "NonInteractive" examples didn't work.  Before this change the link read:
https://workday.github.io/canvas-kit/?path=/story/testing-react-popups-tooltip--noninteractive 
but now with the fix, we have the correct link:
https://workday.github.io/canvas-kit/?path=/story/testing-react-popups-tooltip--non-interactive

docs: Change link URL to non-interactive examples

---

modules/labs-react/expandable/lib/ExpandableAvatar.tsx

Per accessibility, we don't need an alt text on the Expandable Avatar because it is a decorative element. Also, we default the element to be a div because we can't have a button within a button.

fix: Update avatar on expandable component

---

modules/react/menu/lib/MenuItem.tsx

Fixes: #1743 
This PR fixes bug with remaining hover behavior in `Menu.Item.Icon`.

fix(menu): Fix issue with color change on menu item icon hover

---

.github/workflows/project-automations.yml

- using new gh token that was created for project board automations

ci: Update secret to new token for project board actions [skip release]

---

modules/react/popup/lib/PopupPopper.tsx

Fixes: #1771 
---
We fixed these types in #1701, for V7, but we didn't fix the issue in V6. This PR adds PopperProps to PopupPopper.
`modules/react/popup/lib/PopupPopper.tsx`

fix: Add PopperProps to PopupPopper props

---

modules/react/common/lib/utils/components.ts
modules/react/common/spec/components.spec.tsx

Class components can only use `React.LegacyRef` (instead of `React.Ref`). Trying to use `createComponent` with class components resulted in type issues because `React.LegacyRef` was not supported. This change checks to see if it's a class component before deciding which ref type to apply.
This also enables `createComponent` to be used with `react-native`:
```tsx
import { View } from 'react-native'
import { createComponent } from '@workday/canvas-kit-react/common'
const MyView = createComponent(View)({
Component(props, ref, Element) {
return <View ref={ref} {...props} />;
},
});
```
---

fix(common): Add support for class components to createComponent

---

.github/PULL_REQUEST_TEMPLATE.md

We've been using the release category badge for a while, and it is difficult to parse and change the category. It is also harder to read the category in the badge due to lower contrast. This change updates the pull request template to make "Release Category" be a regular section.
Documentation
---
Check out the markdown rendering here: https://github.com/Workday/canvas-kit/blob/8303782db7e16963a31ffc1c0d878ccec44fa2de/.github/PULL_REQUEST_TEMPLATE.md
No testing necessary

docs: Make release category easier to change in PR template

---

modules/react/button/stories/button/Button.stories.mdx
modules/react/tooltip/stories/Tooltip.stories.mdx

Removes stale references to Icon Buttons (removed in v7) from the Button and Tooltip MDXes.
Documentation
---
Examine to Button and Tooltip MDXes in Storybook to verify all traces of Icon Button are removed.

docs: Remove stale references to Icon Buttons [skip release]

---

.github/workflows/close-related-issues.yml

Close related issues when the pull request is closed regardless of the target branch of the pull request. Github already closes issues with pull requests targeting the default branch, but Canvas Kit supports multiple support branches. An issue is considered closed when it is merged into `support`, for example. This change decreases the overhead of maintaining Canvas Kit Github.
Infrastruture
---

ci: Close related issues with pull requests [skip release]

---

.github/workflows/project-automations.yml

- Updating to v2 of [leonsteinhaeuser/project-beta-automations](https://github.com/leonsteinhaeuser/project-beta-automations) since v1 was deprecated 1 Oct
- Changing from `pull_request` to `pull_request_target` due to permission restrictions
- Adding Type value within project for Epic, Bug, Spike
- PRs for merge/prerelease/minor-into-prerelease/major, merge/master-into-prerelease/minor & dependabots are automatically added to current sprint for review
Infrastructure

ci: Updates to Project Board Actions [skip release]

---

.github/workflows/forward-merge.yml
.github/workflows/pull-request.yml
modules/react/popup/lib/hooks/useReturnFocus.tsx
utils/publish-canary.mjs

Fixed multiple ci failures:
- Popup tests in React 18 due to different `useLayoutEffect` timing
- forward-merge Action not erroring on Chromatic changes
- pull-request Action not failing properly
- `prerelease/minor` canary builds failing to publish
Infrastructure
---
`useReturnFocus`

ci: Fix popup tests and ci bugs [skip release]

---

cypress/integration/Breadcrumbs.spec.ts
modules/docs/mdx/8.0-UPGRADE-GUIDE.mdx
modules/react/breadcrumbs/lib/Breadcrumbs.tsx
modules/react/breadcrumbs/lib/BreadcrumbsList.tsx
modules/react/breadcrumbs/lib/BreadcrumbsOverflowButton.tsx
modules/react/breadcrumbs/spec/SSR.spec.tsx
modules/react/breadcrumbs/stories/Breadcrumbs.stories.mdx
modules/react/breadcrumbs/stories/examples/Basic.tsx
modules/react/breadcrumbs/stories/examples/CurrentItemTruncation.tsx
modules/react/breadcrumbs/stories/examples/Overflow.tsx
modules/react/breadcrumbs/stories/examples/RTL.tsx
modules/react/breadcrumbs/stories/stories_VisualTesting.tsx

Resolves: #1818 
We discussed in our a11y meeting that we'd like to make the aria props for the Breadcrumbs nav and the overflow button required and add them to our doc examples for consistency and making it more visible to teams. 
Components
Changes: 
- Added requirement of `aria-label` for `nav` element in `Breadcrumbs` component.
- Added requirement of `aria-label` for overflow button.
- Limited overflow button render: it renders only when `overflowButtonProps` containing at least `aria-label` prop passed to `Breadcrumbs.List`.
---
`modules/react/breadcrumbs`

feat(breadcrumbs): Update Breadcrumbs aria props, examples, and a11y guidance

---

modules/react/collection/stories/examples/MultiSelection.tsx

Updates the `multiSelectionManager` import in the Collection MultiSelection example to import from `@workday/canvas-kit-react/collection` rather than `../../lib/useSelectionListModel`. This keeps the example self-contained. This will allow the example to be copy-and-pasteable and prevent issues with consumers of the `canvas-kit-docs` package such as the Canvas Site.
Documentation
---
Ensure the Collection Multi Selection example renders identically as before. To navigate to it within Storybook: `WELCOME > Dev Docs > Collections > Multi Selection`

docs: Fix multiSelectionManager import in Collections example

---

modules/react/common/lib/utils/models.ts
modules/react/common/spec/models.spec.tsx
modules/react/tabs/lib/useTabsModel.tsx

Fix the `TConfig` type exported by the `createModelHook` utility function to work better with model composition. The definition of `useTabsModel` was simplified due to this change.
Types
---
`useTabsModel`

fix: Fix a model's TConfig type and add tests

---

modules/preview-react/menu/lib/Menu.tsx
modules/preview-react/menu/spec/Menu.spec.tsx

Fixes: #1878 
Recently added headers but did not correctly update the index for keyboard style "clicks"
Components
---
I added console.logs the MenuItems in storybook and was able to reproduce bug.

fix: Correctly call keyboard click events when Preview Menu has headers

---

modules/codemod/lib/v8/promoteComponentsToTesting.ts
modules/codemod/lib/v8/spec/promoteComponentsToTesting.spec.ts

Fixes: #1889 
Codemods
---
`modules/codemod/lib/v8/promoteComponentsToTesting.ts`
The codemod was always adding the `nodePath` to the `foundImport` array even if no imports needed to be promoted. Now we have a check to see if any imports need to be transformed. I also added a test to verify the behavior. 
I'm reasonably certain this is a robust fix from the test I added, but I'm not super familiar with this codemod, so a more thorough review would be nice.
The best way to test this is by running the tests locally.

fix(codemod): Fix promote components to testing codemod

---

modules/react/common/lib/utils/useModalityType.ts

There could be many reasons localStorage is blocked (content security policy, iframe cross origin, etc). `useModalityType` uses localStorage to avoid possible flashing of UI for users. But a blank screen due to an access denied error is worse, so we'll wrap `localStorage` access in a `try/catch` block to gracefully fallback to guessing when localStorage is not available.
Components
---

fix: Fail gracefully if localStorage is blocked in useModalityType

---

modules/react/breadcrumbs/lib/BreadcrumbsCurrentItem.tsx
modules/react/text/lib/LabelText.tsx
modules/react/text/lib/TypeLevelComponents.tsx

Fixes: #1905  
Changed text package import to relative and removed `Text.as` from `LabelText` and `Breadcrumbs.Item` to fix CSB render.
Components

fix(text): Update text component imports

---

modules/labs-react/search-form/lib/SearchForm.tsx
modules/labs-react/search-form/spec/SearchForm.spec.tsx

This adds the `labelId` prop to `SearchForm` so users can override the generated value if needed.
Components
---
Here is what the generated id looks like (`"sevu0"`), default behavior maintained:

fix(search-form): Enable overriding the generated labelId

---

modules/react/button/lib/TertiaryButton.tsx
modules/react/button/stories/button/Button.stories.mdx

Fixes: #1813  
Fixes tertiary button props docs. Now has correct language referring to button `size` props. 
Documentation
---
`/modules/react/button/lib/TertiaryButton.tsx`
`/modules/react/button/stories/button/Button.stories.mdx`

fix: Made changes to docs for Tertiary button

---

jest/setupTests.ts
modules/react/switch/spec/Switch.spec.tsx
package.json
yarn.lock

Remove `@emotion/jest`. We don't use snapshots and Testing Library has a non-Emotion specific way of testing styles
Dependencies

chore: Remove @emotion/jest

---

modules/react/pagination/stories/examples/ResponsiveRange.tsx
modules/react/pagination/stories/pagination.stories.mdx

Fixes: #1965
Documentation
---
This is a documentation-only change. We're adding an example for how to build a responsive range for Pagination with `useResizeObserver`.
`modules/react/pagination/stories/examples/ResponsiveRange.tsx`
- Visit the [Storybook example](https://5d854c26ba934e0020f5e98a-cdabjimqxg.chromatic.com/?path=/docs/components-navigation-pagination-react--responsive-range)
A cat responding to the size of the container.

docs: Add Pagination responsive range example

---

.storybook/manager-head.html

**Current**
When folder was expanded it was highlighted despite it not being the current folder
**Fix**
The current highlight will only be within the current story folder
Subheading contrast fix
Infrastructure

fix: Storybook sidebar highlight styling

---

cypress/integration/Popup.spec.ts
modules/popup-stack/lib/PopupStack.ts
modules/react/popup/lib/hooks/useReturnFocus.tsx
modules/react/popup/stories/stories_testing.tsx

Fixes: #1990 
Allows components to override which element focus is returned to when closing a popup. When not overridden, the default behaviour continues.
Components
---
modules/react/popup/lib/hooks/useReturnFocus.tsx
The Testing/React/Popups/Popup/ReturnFocusTest story has been updated to include an example. Click on the link in the popup and see that focus is moved to the text input. When clicking anywhere else, existing focus move behaviour is preserved.

fix: Allow overriding of return focus when closing a popup

---

.github/assign_label_reviewers.yml
.github/workflows/pull-request-label-reviewer.yml

Adding new action that will auto assign a reviewer to the PR when the label `ready for review` has been added.
Infrastructure 
---
Please see the [action documentation](https://github.com/totallymoney/assign-reviewers-by-labels-action) to verify the set up
.github/assign_label_reviewers.yml - this is the config
.github/workflows/pull-request-label-reviewer.yml - this is the action

ci: Adding action to auto assign PR reviewer on label [skip release]

---

modules/codemod/lib/softDeprecate/Stack/softDeprecateStack.ts
modules/codemod/lib/softDeprecate/Stack/spec/softDeprecateStack.spec.ts

This is a fix for the softDeprecate codemod for `Stack`, `HStack` and `VStack`. It was not recognizing the `spacing` prop on `HStack` and `VStack`. 
Fixes: #2035  
To fix the `softDepreacte/Stack` codemod to recognize the `spacing` prop on `HStack` and `VStack`. 
Codemods
`/modules/codemod/lib/softDeprecate/Stack/softDeprecateStack.ts`

fix: Fixed an issue with codemod not recognizing VStack or HStack

---

modules/labs-react/expandable/lib/ExpandableTitle.tsx

<kbd>🐛 Bug Squish</kbd><kbd>🚤 Quick Fix</kbd>
Fixes: #2073 
[ExpandableTitle has some styles in a style attr](https://github.com/Workday/canvas-kit/blob/755aa6f628c9f6a09a9a094e39296dba2e47e0cc/modules/labs-react/expandable/lib/ExpandableTitle.tsx#L24-L26). It is preventing css attribute overrides.
Components
Not explicitly a breaking change for `Expandable.Title`, but does alter the specificity for fontFamily, fontSize, lineHeight, fontWeight, color, and textAlign.
---

fix: Remove style attribute on Expandable Title

---

modules/react/collection/lib/useCursorListModel.tsx
modules/react/collection/lib/useListItemRovingFocus.tsx
modules/react/tabs/stories/examples/DynamicTabs.tsx

Fix the custom list model to correctly use custom `getId` config. The BaseListModel creates `items` that are wrapped with extra metadata. `useListItemRovingFocus` will now use the wrapped item metadata correctly and `useCursorListModel` will set the correct cursorId
Fixes #2095 
Components
An example was incorrectly using the wrong id. Note that `state.items` in a dynamic collection wraps your provided items so there is a `.id` property on `state.items`. `model.getId` is no longer needed and will be removed in the future to avoid confusion.
---

fix(collection): Correctly use custom getId

---

modules/react/common/lib/utils/components.ts
modules/react/common/spec/components.test-d.tsx

This change allows a styled component to be used as the default component in `createComponent`, `createContainer`, and `createSubcomponent`. Before the `ref` was not be extracted correctly. This mean the `ref` was incompatible with any other components.
Components
The following is now allowed:
```tsx
const StyledComponent = styled('button')({})
const MyComponnent = createComponent(StyledComponent)({
Component(elemProps, ref, Element) {
return <Box as={Element} ref={ref} {...elemProps} />
}
})
```
---
- `modules/react/common/lib/utils/components.ts`
- `modules/react/common/spec/components.test-d.tsx`

fix: Extract the correct ref with a styled component

---

modules/codemod/README.md
modules/codemod/index.js

Fixes: #2136
The codemod was ignoring valid JSCodeshift options that are helpful to optimize the script. This patch allows `--ignore-pattern`, `--ignore-config`, and `--verbose` to be passed through. I also set the codemod to ignore `node_modules` directories by default and updated the docs.
Codemods
---
There's not a great way to test this manually, but if the codemod tests pass, it works. I added the output of running this updated script in another consumer repo to show that it works as expected.
```sh
🐠  yarn canvas-kit-codemod v5 src/ --ignore-config=".gitignore" --verbose=2                                                                                                         (base)
yarn run v1.22.19
$ /../../node_modules/.bin/canvas-kit-codemod v5 src/ --ignore-config=.gitignore …
```

fix(codemod): Pass codemod options to jscodeshift script

---

.github/workflows/canary.yml
.github/workflows/forward-merge.yml
.github/workflows/pull-request.yml

Fixes: #2107 
Canary build is failed because storybook requires node 16. Composite action `install` already updated to use node 16. 
After refactoring `release` and `minor-release` actions, we can replace hard-coded install steps (caching and packages install) by calling the composite action. It allows cleaning repeated steps to increase code readability and to make action maintenance easier in situations like this failure. 
Infrastructure

ci: Replace install steps by composite actions

---

modules/react/popup/lib/PopupCard.tsx

Fixes: #1919 
Fixed the bug in PopUpCard where multiple margin value broke `maxHeight` calculation.
Components
---

fix: PopupCard maxHeight calc function

---

cypress/integration/FormField.spec.ts
modules/react/form-field/lib/FormField.tsx
modules/react/form-field/lib/Label.tsx
modules/react/form-field/spec/FormField.spec.tsx

Fixes #2051
Components
---
Go to the Required stories of "Form Field", "TextInput" and "TextArea". Verify the `label` does not have a `required` attribute, verify the `input` does have a required attribute, and the `abbr` has an `aria-hidden="true"` attribute.

fix(form-field): Forward required prop to input

---

modules/preview-react/table/stories/Table.stories.mdx
modules/preview-react/table/stories/examples/BasicWithHeading.tsx
modules/preview-react/table/stories/examples/FixedColumn.tsx
modules/preview-react/table/stories/examples/TableWithContainer.tsx

Fixes: #2158 
Fixes a few issues with the Preview Table docs when consuming the docs on the Canvas Site.
Documentation
---

docs: Fix Preview Table docs

---

modules/react/package.json

Fixes: #2161
Dependencies
---
`@workday/canvas-kit-react/popup` depends on `react-dom`, but it wasn't listed as a peer dependency. This PR fixes that.

fix: Add react-dom peer-dep to main package

---

modules/react/common/lib/utils/components.ts
modules/react/common/spec/components.spec.tsx

The `.as()` method on components can be very useful to extend, but change the default element of a component.
```tsx
// with `styled` - It is a `Box` component, but will render a `<button>` by default instead of a `<div>`
const Button = styled(Box.as('button'))(styles)
// inside a render function since `.as()` is a stable reference
const Button = () => {
const BoxButton = Box.as('button')
return <BoxButton />
}
// for tricky composition with multiple as...
return <InputGroup.Input as={FormField.Input.as(Combobox.Input)} />
```
This change does 2 things:
1. Add `.as()` to `createContainer` and `createSubcomponent` components
2. Makes the `.as()` of all 3 component utility functions return a stable reference using `memoize`
Components
---

feat: Add 'as' method with a stable reference to all component utilities

---

modules/react/button/lib/BaseButton.tsx
modules/react/button/lib/parts/ButtonLabelIcon.tsx

Fixes: #2099 
Motivation: `BaseButton` and `ButtonLabelIcon` need to extend `SystemIconProps`.
Components
---

fix: BaseButton and ButtonLabelIcon extend SystemIconProps

---

.storybook/main.js

Adds a `SKIP_DOCGEN=true` option to Storybook to get Storybook to load faster by skipping all docgen. This is nice when you want to work only on the component and get faster feedback. The Docgen adds about 2s on all hot module reloading.
The MDX doc will still work, but all `SymbolDoc` calls will not return any useful content.
Infrastructure
---
Storybook's `main.js` file
Run `SKIP_DOCGEN=true yarn start`

chore: Add option to skip docgen

---

yarn.lock

More info: https://github.com/advisories/GHSA-xv2f-5jw4-v95m
Dependencies
---
I told yarn to upgrade the `fsevents^1.2.7` resolution. `fsevents` changed its own dependencies, which cascaded to a number of other dependency updates and changes. The only important update is `fsevents^1.2.7` now resolves to `1.2.13` which is outside the effected range.

chore: Upgrade fsevents to a non-vulnerable version

---

modules/docs/mdx/9.0-UPGRADE-GUIDE.mdx
modules/react/common/lib/utils/components.ts
modules/react/common/spec/components.spec.tsx
modules/react/menu/lib/MenuContextTarget.tsx
modules/react/menu/lib/MenuTarget.tsx

`composeHooks` accidentally broke at some point during our compound component paradigm building. It no longer merges the output of all incoming hooks together properly. This fix changes the signature of `composeHooks` and `BehaviorHook` to allow for the correct extraction of output props.
Components
The type signature of `composeHooks` was changed to give more accurate return prop types. This may cause issues with Typescript if your code expected the incorrect return types.
---

fix: Return the correct props from composeHooks

---

modules/react/common/lib/utils/components.ts

It looks like we can simplify the `composeHooks` type signature and remove the overload.
Components
---

chore: Simplify composeHooks function

---

cypress/integration/ComboboxLabs.spec.ts

Rename `Combobox.spec.ts` to `ComboboxLabs.spec.ts`. We're adding a Combobox to main - the rename makes room.
Components
---

chore: Rename Combobox.spec to ComboboxLabs.spec

---

modules/react/collection/lib/keyUtils.ts
modules/react/collection/lib/useListItemRovingFocus.tsx
modules/react/collection/lib/useListResetCursorOnBlur.tsx

Extract out key-based collection navigation into a utility file to be used in other hooks. For example, an `aria-activedescendant` based navigation hook.
Components
---

chore: Extract keyUtils to be used in other key-based collection hooks

---

modules/docs/mdx/9.0-UPGRADE-GUIDE.mdx
modules/react/collection/lib/useBaseListModel.tsx
modules/react/collection/lib/useCursorListModel.tsx
modules/react/collection/spec/useCursorModel.spec.tsx
modules/react/tabs/stories/examples/DynamicTabs.tsx

Virtual lists using dynamic data need to intercept navigation changes to trigger data loading. If data isn't loaded yet, an `id` isn't known yet. The navigation managers were updated to use indexes instead of ids to handle unloaded data. This should not effect most people as the navigation manager is provided by default. This is mostly internal.
Components
The signature of the `NavigationManaget` and `NavigationRequestor` was changed to use numeric indexes instead of string identifiers. This will only break for those who created a custom navigation manager.
---
The tests are the best place to start
All code is covered by tests

chore: Use index instead of identifier for cursor navigation

---

modules/react/collection/index.ts
modules/react/collection/lib/useListItemAllowChildStrings.ts
modules/react/collection/spec/useListItemAllowChildStrings.spec.tsx
modules/react/collection/stories/Collection.stories.mdx
modules/react/collection/stories/examples/StringChildren.tsx

Add string children support to the collection system via `useListItemAllowChildStrings` elemProps hook.
Components
---
Play with the `StringChildren` example. Also tests cover this functionality

feat(collection): Add support for string children

---

modules/docs/mdx/9.0-UPGRADE-GUIDE.mdx
modules/react/collection/lib/useCursorListModel.tsx
modules/react/collection/lib/useListItemRovingFocus.tsx

Fixes: #1234 
Not all collections need an initial cursor position to function. This functionality is more suitable for roving tabindex and doesn't work as well for `aria-activedescendant`. This change moves the functionality out of the cursor model and into `useListItemRovingFocus`
Components
If you use `useListModel` to create AND need the initially registered item to be the cursor position AND do not use `useListItemRovingFocus`, you'll have to add logic to set the cursor to that first item in the list. If you use both `useListModel` and `useListItemRovingFocus`, there is not change in behavior.
---

chore(collection): Move initial cursor to roving focus

---

jest/verifyComponent.tsx
modules/react/common/lib/utils/components.ts
modules/react/text-input/index.ts
modules/react/text-input/lib/InputGroup.tsx
modules/react/text-input/spec/InputGroup.spec.tsx
modules/react/text-input/stories/examples/Icons.tsx

It is error prone to add a clear input button to an `InputGroup`. This change makes `ClearInputButton` a subcomponent of `InputGroup` where `InputGroup` internally tracks the inputRef and can match our accessibility specifications.
Components
---
Try typing in the input of this story: https://5d854c26ba934e0020f5e98a-twbtpktbtg.chromatic.com/?path=/story/components-inputs-text-input--icons

feat(text-input): Add clear icon to InputGroup

---

.github/workflows/dist-tag.yaml
.github/workflows/release-major.yml
utils/dist-tag.mjs

Resolves: #2185 
This PR adds 2 actions:
- `Dist Tag Update` for the fast dist tag update (I left only functionality for updating tag. We can easily add functionality for removing if we need it.)
- `Major Release` to automize a release process for the next major version
Infrastructure

chore: Add actions for major release

---

modules/react/collection/lib/useCursorListModel.tsx
modules/react/collection/lib/useListItemRovingFocus.tsx

Use HTML to extract id when changing focus to avoid issues when the server and client do not agree on id generation. Also, force-choose a default cursor ID when no `initialCursorId` is passed in the model config.
Fixes: #2152, #2218
Components
---
Go through the steps outlined in #2152
The SSR cannot be tested manually without a static-site generator.

fix(collection): Fix SSR focus and multiple tab stops

---

utils/publish-canary.mjs

Lerna doesn't seem to support the `canary` option anymore when creating prereleases. The command doesn't work correctly for us anyways, so I'm removing it. From what I can gather (docs don't mention it and info is sparse), it is supposed to create a pre-id using previous tags and the number of commits between the last tag and the current `HEAD`. But this caused problems for us for a long time because we release with every commit on `master` which caused the commit count to repeat and caused the order of versions to be listed out of order. We started using CI build numbers to fix the problem [#1281](https://github.com/Workday/canvas-kit/pull/1281/commits/95b31c1ae82e9a0996996e03a41c86f68419c96e).
Infrastructure
---
I've verified the regex matches and extracts version information properly …

ci: Fix canary releases

---

modules/codemod/index.js
modules/codemod/lib/v10/example.ts
modules/codemod/lib/v10/index.ts
modules/codemod/lib/v10/spec/example.spec.ts
modules/codemod/lib/v10/spec/expectTransformFactory.ts

Resolves: #2238  
I've added initial settings for v10 codemod, example codemod has been created to prevent typescript failure in index.
Codemods

feat: Set initial v10 codemod

---

modules/react/popup/lib/hooks/useCloseOnTargetHidden.ts
modules/react/popup/lib/hooks/usePopupModel.ts

Fixes a circular dependency that was caused by important from the category root. The circular dependency was throwing an error when writing cypress component tests for certain canvas kit components (i.e. SidePanel). The fix is to change the imports to be relative.
Components
---
I searched the `modules/react/popup/lib` directory for any usage of `from '@workday/canvas-kit-react/popup'` and the 2 files changed were the only instances I found.

fix: Change Popup imports to prevent circular dependencies

---

modules/react/collection/lib/useListModel.tsx

Default `T` in the `ListProps` type signature to `any` to allow overriding of the `item` in the dynamic signature.
For example:
```tsx
<Menu items={items}>
<Menu.List>
{(item: Item) => <Menu.Item data-id={item.id}>{item.text}</Menu.Item>
</Menu.List>
</Menu>
```
In this example, TypeScript will error on `item: Item` because `item` is defaulted to `unknown` which TypeScript complains is incompatible. We use `any` because there is no way to infer `item` in the render prop from the `items` from the `Menu` component. TypeScript doesn't do inference across JSX components.
Components
---

fix(collection): Default `T` to `any` to allow overriding children types

---

modules/react/popup/lib/fallbackPlacements.ts

We are manually copying `placements` because `@popperjs/core` does not export enums in the commonjs package. This caused Jest tests to fail since Jest uses commonjs module format by default.
https://github.com/floating-ui/floating-ui/issues/1325
Components
---

fix: Popper placements export in fallbackPlacements

---

modules/preview-react/select/lib/Select.tsx

Fixes: #2262  
This updates certain comments about the `options` prop of `Select` to better match the actual typing of the prop. The prop can include a mix of strings and objects, rather than just one or the other, but the comments did not make that clear.
Documentation

docs: Update comments about Select options prop to match actual use

---

.storybook/routes.js
modules/react/status-indicator/lib/StatusIndicator.tsx

Deprecate `StatusIndicator` in main. 
Fixes: #2081  
`StatusIndicator` in preview is a better alternative since it's newer and a compound component. 
Components
---
`/modules/react/status-indicator/lib/StatusIndicator.tsx`
`/.storybook/routes.js/`

feat: Deprecated Status Indicator in Main

---

cypress/integration/Checkbox.spec.ts
modules/react/checkbox/lib/Checkbox.tsx
modules/react/checkbox/stories/examples/Indeterminate.tsx

Fixes: #2280   
The underlying checkbox was not getting the indeterminate attribute applied and we were relying on it being both checked and indeterminate to update the visual display. This change sets the attribute and updates the CSS to also check the `:indeterminate` pseudo class. Indeterminate checkboxes are a bit odd as [the state can't be directly changed via HTML and needs to be set with a ref](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#indeterminate_state_checkboxes)
Components
---

fix(checkbox): Fix indeterminate state not getting correctly applied

---

cypress/integration/Autocomplete.spec.ts
modules/react/combobox/lib/ComboboxInput.tsx

Removes the accidental logic that closes the menu and clears the input when no item is selected.
Fixes: #2288
Components
---
Go to the Autocomplete example and type "Peach" and hit the enter key. It should not clear the input

fix(combobox): Do not clear the input when no item is selected

---

modules/react/action-bar/lib/useActionBarModel.tsx

I noticed some console logs when I was running a unit test with some components that relied on CK internally that I figured I could go ahead and declutter:
Feel free to close this if you want to keep them around!
Components
---
`useActionBarModel.tsx` 😏 
It's probably more effort to set up a fresh repro repo than it is to fix the change 😁 Probably any test running a component with ActionBar would show these guys.
⬆️

chore: Ditch a few console logs from useActionBarModel that can clutter up test logs

---

cypress/integration/Switch.spec.ts
modules/react/switch/lib/Switch.tsx
modules/react/switch/spec/Switch.spec.tsx

Contributing updates to the accessibility guidelines on the Canvas Kit design site, I noticed the Switch component rendered with an ARIA checkbox role. This didn't seem appropriate for the Switch component.  Additionally, removing tabindex attribute. Didn't seem necessary when the input element is already in focus order anyway.
Components
---
`/modules/react/switch/lib`
1. Make sure the Switch component still appears in keyboard focus order, 
2. Make sure the Switch component still responds to the Space bar and changing state, 
3. Validate screen readers are describing the component's role as "switch"
4. Validate screen readers are describing the state of "on" or "off"
ARIA roles do not have any impact on the visual UI.

fix: Changing ARIA role to switch

---

modules/preview-react/select/lib/Select.tsx
modules/preview-react/select/lib/SelectBase.tsx

Fixes: #2303 
When you click to open the preview `<Select />` menu, onBlur event is immediately triggered. This is somewhat expected since the focus moves from the button to the menu, however is not desirable since many validation libraries use the blur event to check the field. This change blocks triggering the blur event unless the menu is closed.
Components
---
I tried writing RTL tests for this, but couldn't get the events to trigger like they do for real users. Not sure if we would need to introduce the user-event lib for more accurate results.
I tested in storybook adding an onBlur to the FormField wrapper

fix(preview): Blur firing incorrectly onClick

---

modules/react/breadcrumbs/lib/hooks/utils/index.ts
modules/react/breadcrumbs/stories/stories_VisualTesting.tsx

Fixes a bug where Breadcrumbs truncates the array of items even if there are only two or three items in the array and an overflow button is present.
Fixes: #2306
Components
---
Before
After
Story Visual updated

fix: Breadcrumbs first item gets cut-off when two items in array

---

modules/react/popup/lib/hooks/useReturnFocus.tsx

SVG elements should not be used as popup targets, but we shouldn't be restricting them. This change allows SVG elements to be valid elements when it comes to calculating focus returning and management in the popup system.
Fixes #2330
Components
---

fix(popup): Allow SVG elements in focus calculations

---

modules/docs/mdx/10.0-UPGRADE_GUIDE.mdx
modules/react/text-input/lib/InputIconContainer.tsx

Fixes: #2186 
PR contains `InputIconContainer` deprecation.
Components
`InputIconContainer` has been deprecated, because it does not handle bidirectionally or icons at the start of an input. Please use [`InputGroup`](https://workday.github.io/canvas-kit/?path=/story/components-inputs-text-input--icons) instead.
---

feat: Deprecate InputIconContainer

---

modules/docs/lib/widgets/external.tsx

The external `SymbolDoc` type did not render type parameters:
```ts
Record<string, number>
```
This fix updates the external symbol type to include the type parameters.
Documentation
---

docs: Render type parameters in external SymbolDoc symbols

---

modules/docs/mdx/10.0-UPGRADE_GUIDE.mdx
modules/react/table/lib/Table.tsx
modules/react/table/lib/TableRow.tsx

Deprecate `Table` in main.
Resolves: #2249 
Components
`modules/react/table/lib/Table.tsx`
`modules/react/table/lib/TableRow.tsx`
`modules/docs/mdx/10.0-UPGRADE_GUIDE.mdx`
`/.storybook/routes.js/` is already updated with route to Table in Preview https://github.com/Workday/canvas-kit/blob/prerelease/major/.storybook/routes.js#L15

feat: Deprecated Table in Main

---

modules/react/avatar/lib/Avatar.tsx

The site was seeing `<img>` and `<video>` as elements in the jsdoc and creating empty elements. But putting these elements in backticks, it prevents the site from interpreting them as elements and rather as part of the jsdoc.
Documentation
---

fix: Add jsdoc element in backticks for Avatar

---

modules/react/button/lib/PrimaryButton.tsx

The `PrimaryButton` styling works great when there are no conflicting styles. However, the state pseudo selectors take an unopinionated approach on the text color of the button, which makes it easily overridden by globally scoped css (particularly when using `as="a"`). 
In platforms like [Docusaurus](https://docusaurus.io/), it's common to have styling for `a:hover`. Since `PrimaryButton` does not have any `color` set for `:hover` (or other states), this gets overridden by a simple global specifier, resulting in something that looks like this:
While I could add another style for `a[type="button"]:hover { color: #fff }`, this would cause other problems because we have no way of determining via DOM a `PrimaryButton` from a `SecondaryButton`. If this rule were applied to a SecondaryButton, …

fix: Force PrimaryButton text color in all states

---

modules/react/common/lib/CanvasProvider.tsx

We needed to pass a default canvas theme in the canvas provider in cases where consumers don't pass a theme
Components
---

fix: Set a default theme in canvas provider

---

.storybook/main.js
modules/styling-transform/lib/styleTransform.ts
modules/styling/stories/examples/StylingButton.tsx

Fix the styling transformer to correctly write the call expression for `createStyles` for commonjs. Without this change, the `createStyles` is not rewritten to `canvas_kit_styling_1.createStyles`.
Infrastructure

fix: Fix commonjs styling transform

---

modules/react/button/lib/BaseButton.tsx
modules/react/button/lib/Button.tsx

Fixes: https://github.com/Workday/canvas-kit/issues/2380
We have to forward the colors prop to `baseButton` and `button` to allow colors customization.
Components
---

fix: Pass colors prop to basebutton and button

---

modules/react/button/lib/TertiaryButton.tsx

Allows the `colors` prop to be forwarded to `BaseButton` from `TertiaryButton`
Components
---

fix(button): Allow colors to override TertiaryButton

---

modules/react/select/lib/Select.tsx

Fixes: #2409 
The new Select component highlights text on double click/focus. This makes it look like you can typeahead/search. This PR visually removes the background color of the highlight.
Components
---
This is my first time trying the new styling stuff, so let me know if I did it correctly!!!
Open storybook to the new Select input, make a selection, then double click the text.
Before:
so, please include a screenshot or short gif. -->
After:

fix(select): Remove visual selection on Select input

---

babel.config.js
modules/styling/lib/cs.ts
modules/styling/spec/cs.spec.ts
package.json

Adding static styles to the `cs` prop creates a `style` attribute. This fix updates `cs` prop handling to create a CSS class instead.
The following is now supported officially:
```tsx
cs={{ padding: 10 }}
```
Instead of creating `style={{padding:10}}`, it will now invoke `@emotion/css` and will return a className.
Components
---
`cs.spec.ts`

fix: Update cs prop to create a class instead of style

---

modules/react/select/lib/hooks/useSelectInput.ts

When passing `initialSelectedIds` to the `useSelectModel`, the input was rendering the id instead of the text value. This updates the code to render the text value.
Components
---

fix(select): Set initial selected id to the text value

---

cypress/integration/Autocomplete.spec.ts
modules/preview-react/radio/lib/RadioGroup.tsx

When `error` is undefined, the styled attribute was still being applied. This only adds the style attribute with the box shadow when there's an error.
Components
---

fix: Check for undefined error in radio group

---

modules/react/common/lib/InputProvider.tsx

This change silences the `InputProvider` error logs when fetching from local storage in an SSR context. This error prints for every page of SSR sites, so it can really take over log output in builds. 
Components
---

fix: Quiet InputProvider logs for SSR

---

modules/react/menu/lib/MenuPopper.tsx
modules/react/popup/lib/PopupPopper.tsx

Fixes: #2435
There appear to be some scenarios where having `popperOptions` defined in the React render loop creates an infinite loop of recalculations within PopperJS and cause the browser to freeze up. This particular incident occurred when nested popups were closed multiple times.
Components
---

fix: Fixes popperOptions rerendering bug

---

modules/preview-react/form-field/lib/FormFieldLabel.tsx
modules/preview-react/package.json

Preview Form field has the same multiline asterisk issue as the main line one, see #2217. This fixes the asterisk so it is always pinned to the end of the text. 
Components
We removed a wrapping flex element so elemProps is now spread directly on the `<label>` element and the asterisk is at the end of the label.
---

fix(preview): Fix multiline asterisk on preview form field

---

modules/react/form-field/lib/Label.tsx

Fixes: #2217
Components
We've wrapped the contents of the `label` element including the asterisk in a `span`. The asterisk now is at the end of the `label`.
Offline discussion with @mannycarrera4, we want the required asterisk to be at the end of the label when the text label is wrapped. 
**Before**
**After**

fix: FormField fix alignment for required asterisk

---

modules/styling/lib/cs.ts
modules/styling/spec/cs.spec.tsx

Fixes: #2452
The `style` attribute was being converted into a class name. The styles were being added and passing visual tests, but doing so in an unoptimized way. We use the `style` attribute for styles that change frequently to avoid expensive Style recalculations and we accidentally broke that.
Components
---
You could try adding a `style` attribute to any example. Without this change, the style attribute gets removed and the styles get merged into the element's main CSS class.

fix: Fix forwarding of the style attribute

---

modules/react/collection/lib/useOverflowListModel.tsx

Proposal fix for: #2297
Motivation:
Currently the overflow feature of Tabs does not work the "selected" id does not belong to the valid ids list. My proposal solution for this is to get the first id if the given "selected" id is invalid, because (if my understanding is correct), we need `selectedKey` to determine the width of the tab bar (https://github.com/Workday/canvas-kit/blob/master/modules/react/collection/lib/useOverflowListModel.tsx#L29)
Components
---
For testing purpose:
From the example from sandbox in #2297, you can add the following code 
```tsx
useEffect(() => {
model.events.select({ id: '' });
}, []);
```
into `modules/react/tabs/stories/examples/OverflowTabs.tsx` file and play around with it.
https://media.giphy.com/media/yFYioeSeCa99YF9Ucj/giphy.gif

fix: OverflowTab does not render when no tab is selected

---

modules/styling/lib/cs.ts
modules/styling/spec/cs.spec.tsx

Fixes: #2461
[CSSType doesn't support CSS vars](https://github.com/frenic/csstype/issues/126), so we're extending and casting the types to support them for now.
Components
---

fix: Extend CSSObject types to support CSS variables

---

modules/codemod/index.js
modules/codemod/lib/v11/__remove_this__.ts
modules/codemod/lib/v11/index.ts
modules/codemod/lib/v11/spec/__remove_this__.spec.ts
modules/codemod/lib/v11/spec/expectTransformFactory.ts
modules/docs/mdx/11.0-UPGRADE-GUIDE.mdx

Fixes: #2473 
Adds initial codemod for V11 and updates maintaining doc
Infrastructure
---

feat: Add initial v11 setup

---

modules/react/common/lib/CanvasProvider.tsx
modules/react/modal/stories/stories_VisualTesting.tsx
modules/react/popup/lib/hooks/usePopupStack.ts

Forwards the theme overrides to the stack element used in Popups and Modals. This fix also removes unnecessary style overrides for branding colors that aren't changed from the default.
Fixes: #2480 
Components
---
A new story was added for custom themes of a Modal

fix: Forward branding CSS variables through portals

---

modules/styling/lib/cs.ts

Allow booleans on modifiers in Stencils. We need to default the `vars` config in Stencils to allow the `MaybeBoolean` type to work. Otherwise we'll get `vars` defaulting to `Record<string, string> | Record<Record<string, string>` which won't be compatible if `modifiers` have a `boolean` type. This won't work: `<Record<string, string> & { someKey?: boolean }`. `Record<string, string>` is too overly permissive and we need to default `vars` to an empty object to avoid widening the type.
Components

fix: Default createStyles vars to empty object

---

modules/styling/lib/cs.ts

Fixes: #2506 
Fixing TS error for boolean modifiers in compound stencils styles.
```ts
// this shows TS error
compound: [
{
modifiers: {variant: 'inverse', disabled: true},
styles: {...}
}
]
```
Infrastructure

fix: Fix TS error for boolean modifiers in compound stencils styles

---

modules/styling-transform/lib/utils/parseNodeToStaticValue.ts
modules/styling-transform/spec/utils/parseNodeToStaticValue.spec.ts

Fixes: #2516 
Added `ElementAccessExpression` support to the type parser.
Infrastructure

fix: Add ElementAccessExpression support to the parser

---

modules/styling-transform/lib/styleTransform.ts
modules/styling-transform/lib/utils/createStyleObjectNode.ts
modules/styling-transform/lib/utils/handleCalc.ts
modules/styling-transform/lib/utils/handleCreateStencil.ts
modules/styling-transform/lib/utils/handleCreateStyles.ts
modules/styling-transform/lib/utils/handleCreateVars.ts
modules/styling-transform/lib/utils/handleCssVar.ts
modules/styling-transform/lib/utils/handleFocusRing.ts
modules/styling-transform/lib/utils/handleKeyframes.ts
modules/styling-transform/lib/utils/handlePx2Rem.ts
modules/styling-transform/lib/utils/parseNodeToStaticValue.ts
modules/styling-transform/lib/utils/parseObjectToStaticValue.ts
modules/styling-transform/lib/utils/types.ts
modules/styling-transform/spec/utils/handleCreateStencil.spec.ts
modules/styling-transform/spec/utils/handleCreateVars.spec.ts
modules/styling-transform/spec/utils/handleKeyframes.spec.ts
modules/styling-transform/spec/utils/parseNodeToStaticValue.spec.ts
modules/styling-transform/spec/utils/parseObjectToStaticValue.spec.ts
modules/styling/lib/cs.ts
modules/styling/spec/cs.spec.tsx

Add `keyframe` support to the static style parser. Refactored transformers a bit to use a `context` object instead of multiple parameters. This makes the transforms a bit more flexible and keeps parameter count down.
Infrastructure
---
`handleKeyframes.spec.ts`
Add `keyframes` somewhere in a React file.
```
(cd modules/react; yarn clean && yarn build:es6)
```
Run `yarn clean` when done

feat: Add keyframe support to static style parser

---

modules/preview-react/side-panel/stories/examples/Basic.tsx
modules/preview-react/side-panel/stories/examples/RightOrigin.tsx
modules/preview-react/side-panel/stories/examples/Variant.tsx

Fixes: #2523  
For the Basic example, Alternate example, and Right-to-left example, they should display a hidden `<span>` with `labelProps` when in the collapsed state. This helps keep the `aria-labelledby` reference on the toggle button valid while collapsed. 
Documentation 
Updates the Basic example, Alternate example, and Right-to-left example to display a hidden <span/> element when in the collapsed state. 
`modules/preview-react/side-panel/stories/examples/Basic.tsx`
`modules/preview-react/side-panel/stories/examples/Variant.tsx`
`modules/preview-react/side-panel/stories/examples/RightOrigin.tsx`
While using VoiceOver on MacOS:
1. Turn on VoiceOver: Cmd + Power button 3x
2. Open Safari and navigate to Storybook > Preview > SidePanel > Basic
3. Verify SidePanel is in opened expanded …

fix: SidePanel Examples aria-labelledby Update

---

modules/preview-react/_examples/stories/examples/Table/WithSelectableRows.tsx

This PR fixes the Selectable Table Row example to make it more screen reader friendly.
Documentation
---

docs: Fix Table example

---

modules/preview-react/loading-sparkles/lib/LoadingSparkles.tsx
modules/preview-react/package.json
modules/preview-react/tsconfig.json

The style transform was not being run on preview components and therefore the CSS variable fallbacks were never automatically added. This change fixes that by running the style transform on the preview package.
Components
---

fix: Add CSS var fallbacks on Preview

---

utils/fix-package-json-versions.js
utils/forward-merge.js
utils/resolve-package-json.js
utils/spec/fix-package-json-versions.spec.ts
utils/spec/resolve-package-json.spec.ts

- Fixes a common merge issue with our `package.json` files when `support` and `master` have different versions and `master` has an additional dependency next to it. For example:
```
<<<<<<< merge/prerelease/minor-into-prerelease/major
"@workday/canvas-kit-styling": "^10.3.3",
=======
"@workday/canvas-kit-styling": "^10.3.2",
"@workday/canvas-tokens-web": "^1.0.2",
>>>>>>> prerelease/major
```
It will now resolve correctly.
- Fixes an issue where `prerelease/major` adds a mono-repo dependency like `@workday/canvas-kit-styling` and it doesn't get updated by the forward merge and the forward merge fails with a depcheck stating all dependencies need the same version strings. Merge conflicts don't find it, so the forward-merge adds an additional process to gather all mono-repo dependency …

ci: Fix forward-merge version conflicts [skip release]

---

modules/styling-transform/lib/utils/handleKeyframes.ts

Fixes the style transform for keyframes in commonjs module export type. If the `keyframe` is a call expression node type, the `ts.factory.updateCallExpression` is used instead of creating a new one. Creating a new AST node has a negative effect on TypeScript's own `commonjs` module transformation where it looses access to the original parent node and doesn't transform the import correctly.
Components

fix: Fix keyframes transform for commonjs modules

---

utils/forward-merge.js

Fix a syntax error in `forward-merge.js` that updates version strings in `package.json` files
Infrastructure
---

ci: Fix package.json fix syntax error [skip release]

---

utils/resolve-package-json.js
utils/spec/resolve-package-json.spec.ts

There were only tests when the incoming version was lower than the current version, but not the other way around. This caused the merge script to remove a dependency that was newer. In `prerelease/major`, the tokens dependency is `1.0.2` while in master it is `1.0.0`. This fix should resolve that.
Infrastructure

ci: Fix resolve-package-json merge file [skip release]

---

modules/styling-transform/lib/utils/handleCalc.ts
modules/styling-transform/lib/utils/handleCreateStencil.ts
modules/styling-transform/lib/utils/handleCssVar.ts
modules/styling-transform/lib/utils/handleKeyframes.ts
modules/styling-transform/lib/utils/handlePx2Rem.ts
modules/styling-transform/lib/utils/parseNodeToStaticValue.ts
modules/styling-transform/lib/utils/parseObjectToStaticValue.ts
modules/styling-transform/lib/utils/types.ts
modules/styling-transform/spec/utils/parseNodeToStaticValue.spec.ts
utils/style-transform/handleFocusRing.ts

Fixes: #2587
The static style transform was always turning numbers into strings with a `px` suffix. This isn't correct and Emotion has extra logic to turn a number into the correct string. For example, an opacity doesn't have a unit. This fix updates the logic to forward numbers straight to Emotion to process which should give a correct result.
Infrastructure
---

fix: Forward numeric style prop transform handling to Emotion

---

modules/react/common/lib/styles/focusRing.ts
modules/styling-transform/index.ts
modules/styling-transform/lib/utils/parseObjectToStaticValue.ts
modules/styling-transform/spec/utils/parseObjectToStaticValue.spec.ts
utils/style-transform/spec/handleFocusRing.spec.ts

This change moves `maybeWrapCSSVariables` to a external wrapper function that recurses through all the style object values to wrap any unwrapped CSS variables and also adds a fallback if necessary. The code was originally dispersed around parsing, but has now been put in a consistent place to make sure CSS var wrapping doesn't get missed.
This change also adds hard-coded var fallbacks for dynamic uses so we don't accidentally introduce a dependency on the new tokens before we're ready to require them.
Fixes: #2603 
Infrastructure
---
Tests

fix: Add CSS fallback to custom transforms

---

modules/styling-transform/lib/styleTransform.ts
modules/styling-transform/lib/utils/types.ts
styling.config.ts

Adds a per-module prefix so that `labs` and `preview` can have different prefixes to avoid collisions.
Infrastructure
---
Run `yarn build`

feat: Add per-module prefix

---

modules/styling/lib/cs.ts
modules/styling/spec/cs.spec.tsx

Fixes: #2613
Fixed issue with stencil and vars with not wrapping css variable by `var()` in css code for values passed inside on component level.
Components
---

fix: Wrap css variables passed into stencil and vars

---

modules/styling/lib/cs.ts
modules/styling/spec/cs.spec.tsx

Fixes stencils to handle variables and deeply nested style objects in both the `cs` prop and `handleCsProp` function.
Styling
---
Specifications
Replicate test code

fix: Fix stencil types to handle vars and deeply nested styles

---

modules/react/button/lib/BaseButton.tsx
modules/react/segmented-control/stories/stories_VisualTesting.tsx

Fixes: #2622 
This continues with the intended change to icons in `SegmentedControl` that were broken with icons with background layers. The intent was to treat all icon fill layers the same in `SegmentedControl` and we failed to do that properly. This change simplifies the icon fill selectors and ensures the icons always look as intended and don't require guess work from icon designers.
Components
This change may trigger a visual regression with certain icons in buttons and `SegmentedControl` buttons. This change is intentional and fixes an accidental regression between v9 and v10. There should be no other breaking changes.
---
Visual regression test story and the basic SegmentedControl story
https://5d854c26ba934e0020f5e98a-zgkrlvcqwf.chromatic.com/?path=/story/testing-buttons-segmented- …

fix(button): Fix icon colors in buttons and SegmentedControl

---

modules/styling-transform/lib/utils/handleCreateStencil.ts
modules/styling-transform/spec/utils/handleCreateStencil.spec.ts
modules/styling/lib/cs.ts
modules/styling/spec/cs.spec.tsx
modules/styling/spec/tsconfig.json
modules/styling/stories/Basics.stories.mdx

Fixes variables used inside a stencil. Before this used to cause problems when `color` is expected to be a string:
```tsx
const myStencil = createStencil({
vars: {
color
},
base({color}) {
color // `string | undefined`, but should aways be a `string`
}
})
```
This change also introduces the concept of uninitialized stencil variables. It always worked, but I've added documentation and support in the static style parser.
I also fixed a but where JSDoc of a stencil variable did not get forwarded properly.
Styling
---
Tests

fix(styling): Fix variables in stencil config

---

.github/workflows/forward-merge.yml

If for some reason someone has a branch on their forked repository that matches the branch on remote, the commands fails. This change ensures that it always tracks upstream remote instead of what you might have on your own forked repo.
Infrastructure
---

fix: Update forward merge to track remote branch [skip release]

---

modules/react/common/lib/CanvasProvider.tsx
modules/react/layout/lib/utils/mergeStyles.ts
modules/react/layout/spec/mergeStyles.spec.tsx
modules/react/package.json
modules/styling-transform/lib/styleTransform.ts
modules/styling-transform/lib/utils/handleInjectGlobal.ts
modules/styling-transform/spec/utils/handleInjectGlobal.spec.ts
modules/styling/lib/cs.ts
modules/styling/package.json
modules/styling/spec/cs.spec.tsx
modules/styling/stories/Basics.stories.mdx
modules/styling/stories/MergingStyles.stories.mdx

Add a way to create an Emotion instance with initialization options, including a `nonce` or custom `stylis` plugins. Before, the Emotion instance created by `@emotion/css` was used. Now `@emotion/css` is used as a fallback if an instance hasn't been created by the time a style utility is called.
Fixes: #2628 
This change adds the following opt-in features:
- Change the default Emotion cache instance used by Canvas Kit and the application
- Allow use of `injectGlobal` from `@workday/canvas-kit-styling` that uses the shared instance.
Infrastructure
This change does not introduce any breaking changes, but creating a custom Emotion instance can introduce a breaking change. A custom instance should only be used if all instances of Canvas Kit on the page are above the version this change is …

chore: Add nonce support to styling

---

modules/styling/lib/cs.ts
modules/styling/spec/cs.spec.tsx
modules/styling/stories/Basics.stories.mdx

Fix TypeScript types when the variable and modifiers share the same keys. This is supported without issue at runtime, but TypeScript would throw an error. Now if the keys are the same, the types will include the modifier keys, but allow any string.
For example, the following is now supported:
```tsx
const myStencil = createStencil({
vars: {
width: '10px',
},
base({width}): {
return {
width: width
}
},
modifiers: {
width: {
zero: {
width: '0', // overrides base styles
},
},
},
});
myStencil({width: 'zero'}); // `'zero'` is part of autocomplete
myStencil({width: '10px'}); // width also accepts a string
```
Styling
---
Tests

fix(stencil): TypeScript support for variable/modifier with same key

---

modules/styling-transform/lib/utils/parseNodeToStaticValue.ts
modules/styling-transform/spec/utils/handleCreateStencil.spec.ts

Makes local variables safe for Emotion since `"label"` is a reserved string in Emotion.
Components

fix: Make variable names safe for Emotion

---

modules/react/select/lib/hooks/useSelectInput.ts

`value` was not passed to the underlying select input. Consumers would pass `value` but it wasn't working. This change passes the value to the input so consumers can control it and the visual input would reflect it..
Components
---

fix: Pass value to visual input in select

---

.storybook/main.js
.storybook/style-transform-loader.js
.storybook/symbol-doc-loader.js

Fixes an issue introduced with the style transform where `SymbolDoc` stopped working because the style transform overrode the webpack doc loader
Documentation
---
[](https://5d854c26ba934e0020f5e98a-xklgwshvzc.chromatic.com/?path=/docs/components-buttons--primary)
Look at the component API docs

ci: Fix SymbolDoc

---

modules/react/loading-dots/stories/LoadingDots.stories.mdx
modules/react/loading-dots/stories/examples/Accessible.tsx

The Soap400 color for the `LoadingDots` component does not meet WCAG guidelines for non-text contrast while used on light background colors. For this example, I used a darker background color that allows Soap400 to meet the minimum 3:1 contrast ratio. I also added better screen reader support with the `AriaLiveRegion` component that both lets users know about the loading status, and when loading has completed. 
Documentation 
Accessible `LoadingDots` example has been updated, by changing background to a darker color that allows `soap400` to meet the minimum 3:1 contrast ratio and adding better screen reader support with the `AriaLiveRegion` component.
The "Accessible" example of the `LoadingDots` component, and the storybook mdx file. 
1. Turn on your favorite screen reader
2. Recommend …

docs: Improve the "accessible" example of loading dots

---

modules/preview-react/radio/lib/RadioText.tsx
modules/styling/lib/cs.ts
modules/styling/spec/cs.spec.tsx

Fixes: #2703  
Fixed issue with default modifiers type:
```ts
const textStencil = createStencil({
base: {},
modifiers: {
"type": {
"title.large": {}
}
}
});
const labelStencil = createStencil({
extends: textStencil,
base: {},
modifiers: {variant: {"inverse": {}}}
// the next line shows issue
// that type `{type: "title.large"}` is not compatible with `{variant: {"inverse": {}}}`
defaultModifiers: {type: "title.large"}
}
Components

fix: Fix default modifiers type

---

.yarnrc
modules/docs/package.json
modules/preview-react/package.json
modules/react/package.json
modules/styling-transform/package.json
modules/styling/package.json
package.json
yarn.lock

Update @workday/canvas-tokens-web version to 1.3.1
Infrastructure

chore: Update @workday/canvas-tokens-web version

---

modules/react/common/lib/CanvasProvider.tsx

Update `CanvasProvider` to use JS tokens instead of hard-coded strings. This allows the style transformer to automatically include fallbacks.
Components
---
Make sure state tables with custom themes still work.

fix: CanvasProvider should use JS tokens instead of hard-coded strings

---

modules/styling/lib/cs.ts
modules/styling/spec/cs.spec.tsx

Fixes: #2718
Fixed style merging in compat mode that can result in incorrect styles
Components
This fixes an issue where styles would merge incorrectly in compatibility mode. Compatibility mode is triggered when our component is augmented by a style prop, wrapped with `styled`, passed a `css` prop, or passed a `cs` prop with object styles. This fix ensures that `modifiers` via `createModifiers` or `createStencil` merge styles the same way in both static and compat modes. See the linked issue for more details.
---
Test file
You can verify the test fails if the cs file is reverted

fix: Style merging in compat mode

---

modules/preview-react/_examples/stories/examples/TextInputWithReactHookForm.tsx
modules/react/combobox/lib/hooks/useComboboxInput.ts
modules/react/select/lib/Select.tsx
modules/react/select/lib/hooks/useSelectInput.ts

Forward `onFocus` to  `Select` and forward `focus()` and `blur()` to the visual input.
Fixes: #2716
Components
---

fix(select): Redirect focus to visual input

---

modules/docs/docgen/spec/createProgramFromSource.ts
modules/labs-react/combobox/lib/Combobox.tsx
modules/preview-react/text-input/spec/TextInput.spec.tsx
modules/react/button/spec/Button.spec.tsx
modules/react/collection/spec/useCursorModel.spec.tsx
modules/react/common/spec/components.spec.tsx
modules/react/common/spec/mergeProps.spec.tsx
modules/react/form-field/spec/FormField.spec.tsx
modules/styling-transform/spec/createProgramFromSource.ts
modules/styling-transform/spec/findNodes.ts
modules/styling-transform/spec/utils/getErrorMessage.spec.ts
modules/styling-transform/spec/utils/getVarName.spec.ts
modules/styling-transform/spec/utils/handleCalc.spec.ts
modules/styling-transform/spec/utils/handleCreateStencil.spec.ts
modules/styling-transform/spec/utils/handleCreateStyles.spec.ts
modules/styling-transform/spec/utils/handleCreateVars.spec.ts
modules/styling-transform/spec/utils/handleCssVar.spec.ts
modules/styling-transform/spec/utils/handleKeyframes.spec.ts
modules/styling-transform/spec/utils/handlePx2Rem.spec.ts
modules/styling-transform/spec/utils/parseNodeToStaticValue.spec.ts
modules/styling-transform/spec/utils/parseObjectToStaticValue.spec.ts
modules/styling/lib/cs.ts
modules/styling/spec/cs.spec.tsx
modules/styling/spec/tsconfig.json
tsconfig.spec.json
utils/style-transform/spec/handleFocusRing.spec.ts

This commit adds back code that was accidentally removed during the last merge and fixes some merge conflicts that had the wrong merge. I also enabled `strictNullChecks` on specs. It should have failed the build, not allowing a lot of mistaken merge conflicts.
Infrastructure
---

fix: Fixed some mistaken merge conflicts

---

modules/react/layout/lib/utils/mergeStyles.ts

Flex style props are not part of `mergeStyles`. This will cause breaking changes if we remove style props from a component when an application uses flex style props. For example,
```tsx
<ListBox flexDirection="row">...</ListBox>
```
If we used a `flexDirection` style prop in v10, but move it to a Stencil in v11, the `flexDirection="row"` will no longer work. This is because `mergeStyles` is covering all style props except for flex style props like `flexDirection`. The `flexDirection` prop will be prop drilled all the way down to the `Flex` layout component which will now be applied under the `flexDirection: 'column'` of the Stencil, changing the behavior of the style prop. It is not our intention to break style props in v11, so the `mergeStyles` should handle all style props so that …

feat: Add flex styles to mergeStyles

---

modules/styling-transform/lib/utils/parseNodeToStaticValue.ts
modules/styling-transform/spec/utils/handleCreateStencil.spec.ts

Fixes the style transform where a Stencil is extending a base Stencil from another package. The wrong prefix was being chosen.
Styling
---

fix(styling-transform): Stencils use the correct variable prefix

---

modules/preview-react/pill/lib/Pill.tsx
modules/preview-react/pill/lib/PillIconButton.tsx

`Button` and `SystemIcon` were refactored with `createStencil` and that required updates to the `Pill` component. Some subtle styling issues were introduced. I worked through all these issues, rethinking a few style organization issues with `Pill`
Fixes: #2727
Components
---
Load the Pill stories

fix(pill): Fix Pill styles after stencil refactor

---

modules/styling/stories/MergingStyles.stories.mdx

`Mergiing Styles` -> `Merging Styles`
Documentation
---
Run Storybook

docs: Fix typo in Merging Styles story name

---

modules/react/badge/lib/CountBadge.tsx

Fixes CountBadge display name
Components
---

fix: Fix CountBadge display name

---

modules/styling-transform/lib/styleTransform.ts
modules/styling-transform/lib/utils/handleCreateStencil.ts
modules/styling-transform/lib/utils/handleParentModifier.ts
modules/styling-transform/spec/utils/handleCreateStencil.spec.ts
modules/styling-transform/spec/utils/handleParentModifier.spec.ts
modules/styling/lib/cs.ts
modules/styling/spec/cs.spec.tsx

PR #2741 added the ability to target parent modifier class names to build selectors, but doesn't work in compat mode because compat mode merges all the CSS class names into a single, new class name. I added a `parentModifiers` function that handles this for both React Kit and CSS Kit and updated stencils to add inert class names for the purpose of always matching a selector.
I also fixed a bug where passing `undefined` to a Stencil for a modifier key resulted in overriding `defaultModifiers`.
Styling
---
**Before**:
React static mode
```tsx
<div {...mergeStyles(elemProps, myStencil({ size: 'large' }))} />
```
HTML
```html
<div class="css-12345 css-abcde"></div>
```
Styles
```css
.css-abcde :where(.css-123ab) {
...
}
```
React compat mode
```tsx
<div {...mergeStyles(elemProps, [myStencil({ …
```

fix(styling): Fix parent selectors in compat mode

---

modules/css/package.json
modules/docs/mdx/11.0-UPGRADE-GUIDE.mdx
modules/labs-css/package.json
modules/preview-css/package.json
modules/preview-react/form-field/index.ts
modules/preview-react/form-field/lib/FormField.tsx
modules/preview-react/form-field/lib/FormFieldContainer.tsx
modules/preview-react/form-field/lib/FormFieldHint.tsx
modules/preview-react/form-field/lib/FormFieldLabel.tsx
modules/preview-react/form-field/lib/formFieldStencil.ts
modules/preview-react/form-field/lib/hooks/useFormFieldModel.tsx
modules/preview-react/form-field/lib/hooks/useFormFieldOrientation.tsx
modules/preview-react/form-field/stories/examples/Custom.tsx
modules/preview-react/text-area/lib/TextArea.tsx
modules/preview-react/text-input/lib/TextInput.tsx
modules/preview-react/text-input/spec/TextInput.spec.tsx
modules/styling-transform/lib/utils/handleParentModifier.ts
modules/styling-transform/spec/utils/handleCreateStencil.spec.ts
modules/styling-transform/spec/utils/handleParentModifier.spec.ts
modules/styling/lib/cs.ts
modules/styling/spec/cs.spec.tsx

Refactor preview `FormField` Stencil to use `parentModifier` and remove the need for style information in the model and extra modifiers needed in the CSS Kit output
Components
The required asterisk is now a pseudo element. While the asterisk was never read out loud by screen readers, Testing Library required it in the `*ByLabelText` query. `*ByRole` uses the w3c [accessible name calculation specification](https://www.w3.org/TR/accname-1.2/), but `*ByLabelText` uses [textContent](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent). Additional information: https://github.com/testing-library/dom-testing-library/issues/929
v10:
```ts
screen.getByLabelText('Email*'); // Email is a required field and asterisk is included in name
screen.getByRole('textbox', {name: 'Email'}); // …
```

chore(form-field): Update the preview FormField Stencil

---

modules/preview-react/package.json
modules/preview-react/radio/lib/StyledRadioButton.tsx

Fixes: https://github.com/Workday/canvas-kit/issues/2744
Components
StyledRadio was spreading props to the input and it's parent div. This change removed spreading prop to the parent div except for className.
---

fix(radio): Spread props to input

---

modules/preview-react/package.json
modules/styling-transform/lib/utils/handleCreateStencil.ts
modules/styling-transform/spec/utils/handleCreateStencil.spec.ts

Improve CSS Kit selectors by dropping the prefix for modifiers.
Styling
--
**HTML**:
```html
// before 
<button class="cnvs-button cnvs-button-tertiary cnvs-button--size-large cnvs-button-tertiary--size-large cnvs-button--icon-position-only cnvs-button-tertiary--icon-position-only">
// after
<button class="cnvs-button cnvs-button-tertiary size-large icon-position-only">
```
**CSS**:
```css
// before 
.cnvs-button--size-large.cnvs-button--icon-position-only {
// base button compound modifier styles
}
.cnvs-button-tertiary.cnvs-button--size-large.cnvs-button--icon-position-only {
// tertiary button compound modifier styles
}
// after
.cnvs-button.size-large.icon-position-only {
// base button compound modifier styles
}
.cnvs-button-tertiary.size-large.icon-position-only {
// tertiary button …
```

chore: Improve CSS Kit selectors

---

modules/styling-transform/lib/utils/parseObjectToStaticValue.ts
modules/styling-transform/spec/utils/handleCreateStencil.spec.ts
modules/styling-transform/spec/utils/parseObjectToStaticValue.spec.ts

Support shorthand properties in Stencils for variables.
Styling
---
For example:
```ts
const myStencil = createStencil({
vars: {
color: 'red',
},
base({ color }) => ({
color // shorthand property wasn't supported
})
})
```

fix: Support shorthand properties in Stencils

---

modules/react/common/lib/utils/models.ts
modules/react/common/spec/models.spec.tsx

Fixes: #2756
Models use the object spread operator to allow `config` to override `defaultConfig`. If `undefined` is passed to a key, it would cause `undefined` to be assigned to config even if the model didn't allow for that. Instead of using an object spread, `config` keys are looped over to check for `undefined` values.
Components
---
Extended change information:
```tsx
const useMyModel = createModelHook({
defaultConfig: {
foo: 'bar'
},
requiredConfig: {}
})(config => {
return {
state: {
foo: config.foo // type is `{foo: string}`
},
events: {}
}
})
const model = useMyModel({
foo: undefined
})
```
**Before**
```tsx
model.state.foo // undefined
```
**After**
```tsx
model.state.foo // 'bar'
```

fix: Prevent undefined from overriding model defaultConfig

---

cypress/integration/Select.spec.ts
modules/react/select/lib/hooks/useSelectInput.ts

Update `aria-haspopup` to `menu` in `Select.Input`. This was added some time ago, but the order of composed hooks overwrote the value.
Components
---
Tests

fix(select): Update aria-haspopup to 'menu'

---

modules/react/button/stories/stories_ToolbarButtons.tsx

Fixes: https://github.com/Workday/canvas-kit/issues/2730
Documentation
---
- [na] PR Release Notes describes additional information useful to call out in a release message or removed if not applicable
- [na] Breaking Changes provides useful information to upgrade to this code or removed if not applicable
Before:
After:

chore: Add robust example in storybook for ToolbarDropdown button

---

modules/labs-react/combobox/lib/Combobox.tsx
modules/labs-react/expandable/lib/ExpandableIcon.tsx
modules/labs-react/search-form/lib/SearchForm.tsx
modules/react/avatar/lib/Avatar.tsx
modules/react/common/lib/theming/index.ts
modules/react/common/lib/theming/styled.ts
modules/react/skeleton/lib/parts/skeletonText.tsx
modules/react/tabs/lib/TabsList.tsx

Fixes: #2767.
Refactor styled components to use `shouldForwardProps` to filter out style props to eliminate the warning: `Warning: received <bool type> for a non-boolean attribute <name of attribute>`. 
This warning has been failing a couple of test suites that other people have set up in other projects that use CK components and prevents upgrades to CK11, so I would like to unblock those initiatives.
Components
---
This issue is caused by us passing down style props to the DOM and adding `shouldForwardProps` to filter out these properties solves it.
I've identified all (well all that I can find) areas that require `shouldForwardProps` to filter out style props to prevent this warning. I also added an extra option to include functionality to use `shouldForwardProps` to the overridden …

fix: Prevent style-only props from being forwarded to elements

---

modules/react/select/lib/Select.tsx
modules/react/select/spec/Select.spec.tsx

Fixes the `Select` component when using `React.StrictMode` by adding a ref value guard in the `useImperativeHandle` hook.
Components
---

fix(select): Add conditional for Select in React.StrictMode

---

modules/popup-stack/lib/PopupStack.ts
modules/react/popup/stories/Popup.stories.mdx
modules/react/popup/stories/examples/ExternalWindow.tsx

Popups now render in the same window as their target element.
Fixes #2831 
Components
---
Unfortunately, opening contents in a new window doesn't work within an `iframe` of a code sandbox correctly, so there cannot be an example code sandbox. I created a new example to showcase this behavior: https://5d854c26ba934e0020f5e98a-fgaxeeknap.chromatic.com/iframe.html?args=&id=components-popups-popup--external-window&viewMode=story
[PopupExternalWindow.webm](https://github.com/user-attachments/assets/c40897e0-3cb5-4d89-853c-3fa6677e2698)

fix: Popups render in the target's window

---

modules/react/popup/stories/Popup.stories.mdx
modules/react/popup/stories/examples/ExternalWindow.tsx

Fixes an issue introduced in #2829 where an example imported `Flex` using a [relative path](https://github.com/Workday/canvas-kit/pull/2829/files#diff-eb9d95064ad483df88214fab614969e7f3111bdbdcd06348c6f349d520880d64R19) to `../../../layout` rather than `@workday/canvas-kit-react/layout`. The relative path does not work for consumers of `@workday/canvas-kit-docs` (i.e., the Canvas Site).
Documentation
---
Verify the ExternalWindow example for Popup still works correctly.

fix: Fix Popup ExternalWindow example import

---

modules/react/collection/lib/ListBox.tsx

Adds correct support for `marginTop` and `marginBottom` on `ListBox` and `Menu.List` components.
Components
---
Changing the `marginTop` or `marginBottom` of `ListBox` examples or `Menu.List` examples.

fix: Support marginTop and marginBottom on ListBox

---

cypress/integration/Autocomplete.spec.ts
cypress/integration/Select.spec.ts
modules/react/combobox/lib/ComboboxMenuItem.tsx

Fixes 2860.  `aria-selected` for combobox menu items. The cursor was used to determine `aria-selected` instead of the selected item. This changes the visuals of the selected vs focus state, but that issue is covered in #2828.
Components
This change fixes `aria-selected` in `Combobox.Menu.Item` components, but this does change the visuals of what is considered "selected". If you have any visual tests that have a screenshot of a selected state, the visual regression will have to be updated. The same is true for DOM-based snapshot tests. `aria-selected="true"` will now be added when an item is selected and not just when the virtual cursor is on the item. If your snapshot captures this DOM state, the snapshot will have to be updated.
---

fix(combobox): Use correct state for aria-selected

---

cypress/integration/Autocomplete.spec.ts
cypress/integration/Select.spec.ts
modules/react/select/lib/Select.tsx
modules/react/select/lib/hooks/useSelectInput.ts

Redirect the `PopupModel.state.targetRef` to the user input element instead of the hidden server input element. Tests were added to specify this behavior.
Fixes: #2868 
Components
---
Tests

fix(select): Clicking the input closes the menu

---

modules/react/combobox/lib/ComboboxMenuItem.tsx

Fixes selected state when the selection mode is set to `multiple`
Components
---

fix(combobox): Show selected state when multiple is enabled

---

modules/react/layout/spec/mergeStyles.spec.tsx
modules/styling/lib/cs.ts
modules/styling/spec/cs.spec.tsx

Enable compat mode all the time to ensure correct style merging regardless of environment. For more information, reference our [discussion](https://github.com/Workday/canvas-kit/discussions/2893)
Infrastructure
We're seeing style merging issues when using createStyles or createStencil. It only happens when every style override of the element uses these utilities and @emotion/react or @emotion/styled is not used on the same element. These utilities rely on module execution order and we're having a few reports where modules are possibly executing out of order. In order to allow everyone to use createStyles and createStencil without worrying about style merge issues, we're going to enable compat mode all the time. We'll look into possible out-of-order execution issues in the future and plan …

fix: Enable styling compat mode to ensure proper style merging

---

modules/react/breadcrumbs/lib/BreadcrumbsItem.tsx
modules/react/collection/lib/useOverflowListItemMeasure.tsx

All items hidden by overflow should be [inert](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/inert)
Components
---

fix: Make overflow items inert

---

modules/docs/lib/Value.tsx
modules/react/button/lib/types.ts
modules/react/button/stories/button/examples/CustomStyles.tsx
modules/react/button/stories/button/examples/Primary.tsx

Fixes: #2905  
This fixes a TS error in buttons that wouldn't allow the update of the focusRing styles through the colors prop. Also, deprecated the use of focusRing within focus in the colors prop on buttons and added support for boxShadowInner and boxShadowOuter within focus in colors prop. 
Components
Deprecated the use of focusRing within focus in the colors prop on buttons as this does not work with our current styling methods. Added support for boxShadowInner and boxShadowOuter within focus in colors prop. 
---
`/modules/react/button/lib/types.ts`

fix: Updated ButtonColors interface to deprecated focusRing from focus

---

modules/react/popup/lib/hooks/useAssistiveHideSiblings.ts

Fixes a rare issue when the popup model's stack ref is `undefined`. This will mostly happen in `StrictMode`.
Components
---
(https://workday.github.io/canvas-kit/?path=/docs/guides-documentation-guidelines--page)

fix: Handle empty stack ref in useAssistiveHideSiblings

---

modules/labs-react/search-form/lib/SearchForm.tsx

Add ellipsis to placeholder text in the search form.
Components
---

fix(search-form): Show ellipsis when placeholder overflows

---

modules/react/text-input/lib/InputGroup.tsx
modules/styling/lib/cs.ts

Add support for the new Canvas tokens that utilize CSS Variables in `InputGroup` and export the `maybeWrapCssVars` function from the styling package.
Components
---

feat(text-input): Support CSS Variables in InputGroup

---

modules/docs/mdx/12.0-UPGRADE-GUIDE.mdx

Fixes: #2907  
Cleaning up the Upgrade Guide for v12. 
Documentation 
---
`/modules/docs/mdx/12.0-UPGRADE-GUIDE.mdx`

chore: Upgrade Guide Cleanup 

---

modules/styling-transform/spec/utils/handleCreateStencil.spec.ts
modules/styling/lib/cs.ts
modules/styling/spec/cs.spec.tsx

A modifier key of `_` can be used to indicate a fallthrough modifier. This is useful if we want to conditionally add a CSS property only when a CSS variable is provided.
https://github.com/Workday/canvas-kit/discussions/2941
Styling
---

feat(styling): Add support for fallthrough modifiers

---

.github/workflows/canary.yml

Fixes: https://github.com/Workday/canvas-kit/issues/2947
Infrastructure
---

fix: Remove extract docs in canary to prevent exceeding limit [skip release]

---

modules/styling/lib/cs.ts
modules/styling/spec/cs.spec.tsx

- Support modifiers with a `false` value
Styling
---
Tests

fix: Support false modifier values

---

modules/react/button/lib/DeleteButton.tsx
modules/react/button/lib/PrimaryButton.tsx
modules/react/button/lib/SecondaryButton.tsx
modules/react/button/lib/TertiaryButton.tsx
modules/react/button/stories/button/examples/CustomStyles.tsx
modules/react/button/stories/button/examples/Primary.tsx

Fixes: #2946  
Updates Button variants to fix merge style issue. 
Components
Updates Button variants to fix merge style issue. 
---
`/modules/react/button/lib/PrimaryButton.tsx`
`/modules/react/button/lib/SecondaryButton.tsx`
`/modules/react/button/lib/TertiaryButton.tsx`

chore: Fixed Button Style Merge Issue

---

modules/react/text-input/lib/InputGroup.tsx
modules/react/text-input/lib/TextInput.tsx
modules/react/text-input/stories/visualTesting.stories.tsx
modules/styling-transform/lib/utils/handleCreateStencil.ts
modules/styling-transform/spec/utils/handleCreateStencil.spec.ts

Convert `InputGroup` to use Stencils. This allows anything using the `InputGroup` to not force compatibility mode.
Components
---

chore(text-input): Convert `InputGroup` to use Stencils

---

modules/docs/mdx/10.0-UPGRADE-GUIDE.mdx
modules/docs/mdx/12.0-UPGRADE-GUIDE.mdx
modules/docs/mdx/5.0-UPGRADE-GUIDE.mdx
modules/docs/mdx/6.0-UPGRADE-GUIDE.mdx
modules/docs/mdx/7.0-UPGRADE-GUIDE.mdx
modules/docs/mdx/MAINTAINING.mdx
modules/preview-react/menu/stories/Menu.mdx
modules/react/form-field/lib/FormFieldLabel.tsx
modules/react/form-field/stories/FormField.mdx
modules/react/form-field/stories/FormField.stories.ts
modules/react/form-field/stories/examples/HiddenLabel.tsx
modules/react/menu/stories/Menu.mdx
modules/react/status-indicator/stories/StatusIndicator.mdx

Add `isHidden` to FormFIeld.Label to support what hidden label that existed in form field main before promotion.
Components
If you want to hide the label but maintain accessibility, add the `isHidden` prop on the `FormField.Label` element.
---

fix: Add isHidden to FormField label element

---

modules/docs/mdx/12.0-UPGRADE-GUIDE.mdx
modules/docs/package.json
modules/react/collection/lib/useOverflowListTarget.tsx
modules/react/common/lib/utils/components.ts
modules/react/common/lib/utils/mergeProps.ts
modules/react/common/spec/components.spec.tsx
modules/react/common/spec/mergeProps.spec.tsx
modules/styling-transform/lib/styleTransform.ts
modules/styling-transform/package.json
modules/styling/package.json
package.json
utils/check-dependencies-exist.js
yarn.lock

- Upgrade TypeScript to 5.0
- Upgrade ESLint to 5.61
- Fix `mergeProps` type signature
- Fix `createElemProps` type signature
- Fix `composeHooks` type signature
More info: https://github.com/Workday/canvas-kit/discussions/2979
Components
`elemProps` hooks using `composeHooks` have more accurate type signatures which may lead to new type errors. For information, view our [discussion](https://github.com/Workday/canvas-kit/discussions/2979). 
---

fix: Fix mergeProps, createElemPropsHook, and composeHooks types

---

modules/docs/mdx/12.0-UPGRADE-GUIDE.mdx
modules/react/collection/lib/useCursorListModel.tsx
modules/react/collection/lib/useListItemRovingFocus.tsx
modules/react/combobox/lib/hooks/useComboboxKeyboardTypeAhead.ts
modules/react/select/lib/hooks/useSelectInput.ts
modules/react/select/stories/examples/WithIcons.tsx

Allow the `ListModel` `navigation.getItem()` to return `undefined`.
Components
A list model's `navigation.getItem()` can return `undefined` if no item is found. Previously it threw an error, which cause many problems. It is now up to the caller to decide what to do with an `undefined` return value
---

chore: Collection navigation getItem can return undefined

---

cypress/component/Autocomplete.spec.tsx
modules/react/text-input/lib/InputGroup.tsx
modules/react/text-input/stories/TextInput.mdx
modules/react/text-input/stories/visualTesting.stories.tsx

Fixes `InputGroup.InnerEnd` `width` and positioning calculations. Without this change, `InnerEnd` elements are rendered in the wrong location.
Components
---
Variable widths before this change:
Variable widths after this change:

fix: Fix InputGroup inner end width calculations

---

.storybook/main.ts
modules/docs/mdx/10.0-UPGRADE-GUIDE.mdx
modules/docs/mdx/5.0-UPGRADE-GUIDE.mdx
modules/docs/mdx/6.0-UPGRADE-GUIDE.mdx
modules/docs/mdx/7.0-UPGRADE-GUIDE.mdx
modules/docs/mdx/MAINTAINING.mdx
modules/preview-react/menu/stories/Menu.mdx
modules/react/menu/stories/Menu.mdx
modules/react/status-indicator/stories/StatusIndicator.mdx
package.json
yarn.lock

Add Github Flavored Markdown back to Storybook 7
Documentation
---

docs: Fix Markdown tables

---

modules/codemod/index.js

Fixes: https://github.com/Workday/canvas-kit/issues/2995
Codemod
---

fix: Add codemod to main index file to export

---

modules/react/collection/lib/useOverflowListMeasure.ts

Adds the setting of the container gap to the `useOverflowListMeasure` hook
Components
---

fix: Add gap to overflow calculations

---

modules/react/icon/lib/SystemIcon.tsx

Add a `rem` value for the default size to `SystemIcon`
Fixes #3028
Components
---

fix: SystemIcon supports rem by default

---

modules/styling-transform/lib/utils/handleCreateStencil.ts
modules/styling-transform/lib/utils/parseNodeToStaticValue.ts

Fix variable lookups in Stencils during static style transformation.
Infrastructure

fix: Fix Style transform stencil variable lookup

---

modules/docs/package.json
modules/labs-react/package.json
modules/popup-stack/package.json
modules/preview-react/package.json
modules/react-fonts/package.json
modules/react/package.json
modules/styling/package.json
package.json

`ts-patch` was running our typescript builds in parallel, causing cache issues between modules. Removing `--parallel` from the `build` step within each package so that it is sequential.
Infrastructure
---

fix: Prevent build step in modules from running in parallel

---

modules/react/form-field/lib/FormFieldLabel.tsx

Remove default modifier for formfield label. False should be handled by the stencil.
Components
---

fix: Remove default modifier for formfield label

---

modules/preview-react/status-indicator/lib/StatusIndicatorLabel.tsx

Deconstruct `typeLevel` from `elemProps` in `StatusIndicator.Label` to ensure type styles can be overwritten. 
Components
---

fix: Deconstruct typelevel from props and pass to stencil

---

modules/react/collection/lib/useOverflowListTarget.tsx

Make sure to measure `offsetHeight`. This was missed during this [PR](https://github.com/Workday/canvas-kit/pull/3035/files#) that added the vertical overflow behavior.
Components
---

fix: Measure offsetHeight vertical overflow

---

modules/docs/mdx/CREATING_COMPOUND_COMPONENTS.mdx

Add docs around `createContainer` vs `createComponent` in the `create compound component` section in our docs.
Documentation
---

docs: Add info to create compound component regarding createComponent

---

modules/react/select/lib/SelectInput.tsx

Fixes: https://github.com/Workday/canvas-kit/issues/3078
Components
---

fix: Add pointer events none to Select caret

---

modules/codemod/package.json
package.json
yarn.lock

Fixes: https://github.com/Workday/canvas-kit/issues/3084
Based on an [open issue in jscodeshift](https://github.com/facebook/jscodeshift/issues/534), `recast` seems to be adding an extra parens in the return call in our unit tests. One of the suggested solutions was to downgrade `recast`. In v12, this has been fixed, but adding this resolution for v11.
Dependencies
---

fix: Resolve recast dep from jscodeshift to remove extra parens

---

modules/react/side-panel/lib/SidePanel.tsx

Filter out the `openDirection` prop so it doesn't get forwarded to the `<button>` element.
Components
---

fix(side-panel): Filter out invalid DOM prop

---

modules/preview-react/common/index.ts
modules/preview-react/common/lib/parts/_brand-assets.ts
modules/preview-react/common/lib/parts/index.ts

Fixes: #3012  
Updated and added new dub and logo references in `preview`.
Components
Workday has new logos with updated colors. We've added these to the `preview` package for a smooth transition for consumers. 
If you would like to consume these, here is the import:
```tsx
import {dubLogoPrimary, dubLogoReversed} from '@workday/canvas-kit-preview-react/common'
```
_{Old -> New}_
dubLogoBlue -> dubLogoPrimary
dubLogoWhite -> dubLogoReversed 
wdayLogoBlue -> wdayLogoPrimary
wdayLogoWhite -> wdayLogoReversed
dubLogoMonoBlue 
dubLogoMonoWhite
wdayLogoMonoBlue
wdayLogoMonoWhite 
---
`/modules/preview-react/common`

feat: Update CKR Dub and Logo References

---

modules/docs/package.json
modules/labs-react/package.json
modules/preview-react/package.json
modules/react/button/stories/button/Button.mdx
modules/react/button/stories/button/examples/ThemeOverrides.tsx
modules/react/button/stories/visual-testing/PrimaryButton.stories.tsx
modules/react/common/lib/CanvasProvider.tsx
modules/react/common/lib/theming/createCanvasTheme.ts
modules/react/common/lib/theming/theme.ts
modules/react/common/lib/theming/types.ts
modules/react/common/spec/createCanvasTheme.spec.tsx
modules/react/package.json
modules/styling-transform/package.json
modules/styling/package.json
package.json
utils/storybook/customThemes.ts
yarn.lock

Fixes: https://github.com/Workday/canvas-kit/issues/3121
Theming
The `CanvasProvider` created a cascading barrier for our brand tokens. In the case where `brand.action.**` tokens are defined at the root level, say `:root` in a a CSS file, we want those tokens to cascade through the `CanvasProvider` down to our `PrimaryButton`'s.  To allow this, we've removed them from the `CanvasProvider` and `variables.css`.
- `@workday/canvas-tokens-web@2.1.1` **removed** `--cnvs-brand-action-**` tokens from our `variables.css` to ensure proper cascading of this token to theme our `PrimaryButton`'s.
- The `CanvasProvider` has **removed** defaulting `brand.action.**` for theming and is longer a valid theme property on `CanvasTheme` type. 
- In order to ensure proper cascading of the …

fix: Remove action tokens from CanvasProvider to allow cascading

---

modules/react/select/lib/Select.tsx

Width was deconstructed from Select input props. We should remove it it from the deconstructed props to ensure correct styling when you pass with to Select.Input.
Components
---

fix: Ensure width is passed to Select input

---

cypress/integration/Popup.spec.ts
modules/react/button/lib/BaseButton.tsx
modules/react/common/lib/utils/elements.ts
modules/react/popup/lib/hooks/useReturnFocus.tsx
modules/react/popup/stories/stories_testing.tsx

Separate the concept of focusability between keyboard and mouse. Buttons with a `tabindex` of `-1` are focusable via a pointer device, but not via a keyboard. A user clicking on a button that isn't focusable by keyboard is still a valid target for avoiding focus stealing.
Fixes #3140
Fixes: #1234 
Components
---
Test
Go to the `ReturnFocusTest` and open the popup and click on the tabindex button. The Cypress Test also does this.

fix(popup): Fix useReturnFocus to respect tabindex=-1 buttons

---

modules/react/combobox/lib/hooks/useComboboxInputConstrained.ts

Update `useComboboxInputConstrained` to use reconfiguration vs rewrite for `focus`/`blur` method redirection. This fixes an issue with `user-event` that overwrites these methods to not be rewritable: https://github.com/testing-library/user-event/pull/1252
The extra syntax makes things feel a little more enterprise Java.
Components
---

fix(combobox): Use focus/blur reconfig vs rewrite for testing library

---

modules/styling-transform/lib/utils/parseNodeToStaticValue.ts
modules/styling-transform/spec/utils/parseNodeToStaticValue.spec.ts

Add support for negative numbers in `createStyles` and `createStencil`
Styling
---

fix: Support negative values

---

modules/docs/mdx/TESTING.mdx

Adds Snapshot serializers to the testing documentation with ways to ignore hashes injected by our Static Styling package.
Documentation
---

docs: Add Snapshot serializers to ignore hashes

---

modules/react/common/lib/utils/components.ts
modules/react/common/spec/components.spec.tsx

Add support for the `ElementComponent` type in `createContainer` and `createSubomponent`
Fixes: #3182 
Components
---

fix: Compound components should accept `ElementComponent`

---

modules/react/popup/lib/hooks/useDisableBodyScroll.ts

Update `useDisableBodyScroll` to use CSS classes to control body overflow instead of handling styles directly.
Fixes: #3224 
Components
Popups using `useDisableBodyScroll`, including `Modal`s now use a CSS class conditionally applied to the `document.body` element instead of setting the `overflow: hidden;` style directly. `!important` is used to win over any other style applied to the `document.body`.
---

fix(popup): Nested Popups using `useDisableBodyScroll`

---

modules/react/icon/lib/SystemIconCircle.tsx

Forward `elemProps` again in `SystemIconCircle` after a regression
Fixes #3227
Components
---

fix(icon): Forward `elemProps` in `SystemIconCircle`

---

.github/workflows/forward-merge.yml

Fixes the forward-merge job. GitHub removed the `actions/cache@v2` branch. It has be updated to `actions/cache@v3`
Infrastructure
---

ci: Fix forward merge workflow

---

utils/publish-canary.mjs

We have issues with pre-ids in our canary builds where package managers sort alphabetically. This is an issue when we go from `999` to `1000`. When sorting alphabetically, "1000" is before "999" instead of after. If we prefix with a zero, we can handle up to 9999 before we have this issue. `0999` is properly sorted before `1000`
Infrastructure
---

ci: Pad canary build ids with zeros

---

modules/react/common/lib/utils/components.ts
modules/react/select/lib/SelectInput.tsx

Removing unintentional props from `SelectInputProps`. Any component that uses `create*` component utility functions and uses `ExtractProps` for the prop interface should use `never` as the second parameter. The `never` means "don't include the default HTML attributes in the prop interface". The `as` prop is used to determine the final HTML attributes. Forgetting to use the `never` means the prop interfaces can be incompatible unintentionally, causing TypeScript issues for developers doing things we say is supported.
Components
---

fix(select): Remove excess props from `SelectInputProps`

---

modules/preview-react/multi-select/lib/MultiSelectInput.tsx
modules/preview-react/multi-select/lib/MultiSelectedItem.tsx
modules/preview-react/multi-select/lib/MultiSelectedList.tsx
modules/preview-react/multi-select/stories/MultiSelect.mdx
modules/preview-react/multi-select/stories/MultiSelect.stories.ts
modules/preview-react/multi-select/stories/examples/Disabled.tsx

Forward disabled prop to the whole component. The `MultiSelect.Input` will now forward the `disabled` prop down to the `Pill` component and will apply disabled styling to the container element.
Fixes: #3294
Components
---

fix: Ensure disabled is passed to MultiSelect sub components so input plus options are disabled

---

modules/react/common/lib/theming/types.ts

Fixes: https://github.com/Workday/canvas-kit/issues/3298
Types
We've deprecated `Themeable`. Use the `CanvasProvider` with the `theme` object to theme your application at the root level. If you wish to customize styles for a component you can use CSS variables and our tokens to do so. [Here's an example](https://workday.github.io/canvas-kit/?path=/docs/components-buttons--docs#custom-styles) with our Buttons.
Before we introduce our new Tokens, we had `Themeable` to indicate that our components can be themed. As we've transitioned to updating our components to use our new CSS tokens, this type is no longer needed. Our components can be themed at the root level via the `CanvasProvider`  our through our CSS tokens.
---

chore: Deprecated Themeable. Use CanvasProvider instead

---

modules/preview-react/multi-select/lib/useMultiSelectModel.ts

fix(multi-select): Support items update in selection pills

---

.github/workflows/pull-request.yml

Fixes: #3344
Updated inputs for chromatic.
Infrastructure

chore: Update chromatic action settings

---

modules/react/button/lib/BaseButton.tsx

Fixes: #3357
Add `pointerEvents: none` to the SVG style in `BaseButton` component. This fixes a bug in React 19 where clicking the SVG icon within a button prevents the click event and loses focus.
Components
---
[modules/react/button/lib/BaseButton.tsx]
- Build the package and check if pointer-events is available on the DOM on <svg> tag. 
- Try out this demo button with the new modules. https://stackblitz.com/edit/toolbar-button-tooltip-sswuectw?file=src%2FDemo.tsx 
N/A

fix: Add pointerEvents style to svg in BaseButtonComponent

---

.storybook/main.ts
.storybook/typescript-transform.ts
modules/labs-react/tsconfig.json
modules/preview-react/tsconfig.json
modules/react/tsconfig.json
styling.config.ts
tsconfig.json
typings.d.ts

Fixes the style transform to add back the `focusRing` plugin that was accidentally removed in #3356 
Infrastructure
---

fix: Add focusRing plugin back to style transform

---

modules/docs/lib/Value.tsx

Spec tables in Storybook extend past the container size and start a horizontal scroll in docs. This addresses the styling of those tables.
Fixes: #3404  
Documentation
---
`/modules/docs/lib/Value.tsx`

fix: Spec tables extend through container size

---

modules/styling-transform/lib/createTypeScriptWatchProgram.ts

Fix an issue where the TypeScript watch program clears the terminal. This can make development more difficult because messages outside TypeScript will disappear on file changes.
Infrastructure
---

ci: Fix watch message to not clear terminal

---

modules/react/collection/lib/useOverflowListItemMeasure.tsx

Fix dev warning for React 19 and fix `inert` in React 19. In React <19, adding `inert=''` added the attribute and the correct behavior. In React 19, `inert=''` does not add the attribute. `'true'` works in all versions of React, but triggers a warning in React 19, so we detect React version and set the value differently to ensure correct runtime behavior and avoid any React warnings.
Components
---

fix(collection): Fix `inert` prop in React 19

---

modules/react/button/lib/parts/ButtonLabelIcon.tsx
modules/react/common/lib/utils/components.ts
modules/react/common/lib/utils/insights.ts
modules/react/tsconfig.json

Fixes: #3451 
This PR adds component tagging for analytics.
Infrastructure
---

chore: Add component tracking tags
