modules/button/react/package.json, modules/cookie-banner/react/package.json, modules/core/react/package.json, modules/fonts/react/package.json, modules/icon/react/package.json, modules/loading-animation/react/package.json, modules/status-indicator/react/package.json, yarn.lock
Align all packages to depend on `emotion@^9.2.12`
applicable
=> Align emotion versions in packages

.travis.yml, utils/travis/getGit.sh
- Update Travis secure vars because of move from Travis CI .com to .org.
- Change storybook build/deploy target branches to `release-*` only
- Quick `getGit.sh` script
applicable
=> Update Travis Secure Vars

.travis.yml
- Re-order Travis stages to do PR Preview then Publish then Storybook. This allows us to get fixes out a bit earlier (rather than wait for a storybook build that can take ~10 min)
- Fix Travis GH Pages deploy conditional to allow deployment on `release-*`. (see https://docs.travis-ci.com/user/deployment/#examples-of-conditional-deployment)
- Set `node_js` to an array instead of a value to get rid of red squiggly error (like in this example here: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions)
applicable
=> Reorder jobs for earlier publishing

.travis.yml
Does what #36 should have done 😅 
applicable
=> Reorder Stages

CONTRIBUTING.md
This PR updates module path in CONTRIBUTING.md to match the ones created by `yarn create-module`. It also fixes a typo in the commit writting guidelines.
=> Update module URLs in CONTRIBUTING.md

modules/tooltip/react/lib/Tooltip.tsx, modules/tooltip/react/spec/__snapshots__/Tooltip.snapshot.tsx.snap
The Tooltip React component doesn't have a font. This PR adds it.
=> Add missing font to Tooltip

modules/side-panel/react/lib/SidePanel.tsx
Addresses: https://github.com/Workday/canvas-kit/issues/73
=> fix: remove event handler for resize when component unmounts

CHANGELOG.md
Forgot to add Travis changes to changelog for release.
applicable
=> docs(changelog): add travis changes to log

modules/side-panel/react/lib/SidePanel.tsx, modules/side-panel/react/stories/stories.tsx
Resolves: https://github.com/Workday/canvas-kit/issues/73
=> fix(SidePanel): resolves properly removing handle resize call

modules/avatar/react/README.md, modules/avatar/react/lib/Avatar.tsx, modules/avatar/react/spec/Avatar.snapshot.tsx, modules/avatar/react/spec/__snapshots__/Avatar.snapshot.tsx.snap
Fixes: https://github.com/Workday/canvas-kit/issues/77 and includes some misc. doc updates.
=> fix(Avatar): change prop spread order to allow for overriding the aria label

modules/loading-animation/css/README.md, modules/loading-animation/css/index.scss, modules/loading-animation/css/lib/loading-dots.scss, modules/loading-animation/css/package.json, modules/loading-animation/css/stories.tsx
This PR updates the Loading Animation CSS styles so they match the React component. 
| Breaking Changes | Yes    | Yes   |
- Previously, the css was handling the positioning of the loading dots; now, the user will need to position the loading dots container themselves.
- `.wdc-loading-spinner` has been renamed to `.wdc-loading-dots`.
refactor(loading-animation): update CSS styles to match React implementation (#83)
=> refactor(loading-animation): Update CSS styles to match React implementation

modules/action-bar/css/lib/action-bar.scss, modules/action-bar/css/lib/variables.scss, modules/action-bar/css/stories.tsx
Match css to the react action bar
=> refactor(action-bar): Update css styles to match React implementation

modules/card/css/README.md, modules/card/css/lib/card.scss, modules/card/css/stories.tsx
Most of the styles for the card was matching the react card. The story and readme needed to be updated to match the styles that are the same in the react card component.
=> refactor(Card): Update CSS styles to match React implementation

modules/button/react/lib/IconButton.tsx
Fixes: https://github.com/Workday/canvas-kit/issues/118
=> fix(IconButton): Pass buttonRef to button element

modules/_canvas-kit-react/package.json
=> fix: add menu component to universal module

jest.config.js
Fixes #88
| Breaking Changes | No    | No   |
fix: Add code-coverage to *.ts files (#148)
Adds *.ts files to the code coverage list and ignores *.d.ts files
```
-----------------------------|----------|----------|----------|----------|-------------------|
File                         |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-----------------------------|----------|----------|----------|----------|-------------------|
All files                    |    93.16 |    93.85 |    94.86 |    93.13 |                   |
action-bar/react/lib        |      100 |      100 |      100 |      100 |                   |
ActionBar.tsx              |      100 |      100 |      100 |      100 | …
```
=> fix: Add code-coverage to *.ts files

modules/button/css/README.md, modules/button/css/lib/button.scss, modules/button/css/lib/icon-button.scss, modules/button/css/lib/variables.scss, modules/button/css/stories.tsx
There were several issues uncovered with https://github.com/Workday/canvas-kit/pull/53. This PR addresses them.
=> fix(button): CSS button fixes

modules/checkbox/react/lib/Checkbox.tsx, modules/checkbox/react/spec/__snapshots__/Checkbox.snapshot.tsx.snap, modules/radio/react/lib/Radio.tsx, modules/radio/react/spec/__snapshots__/Radio.snapshot.tsx.snap
This PR fixes a positioning issue found by @sjohnson18 affecting Checkbox and Radio react components.
Fixes: https://github.com/Workday/canvas-kit/issues/163
=> Fix positioning of Checkbox and Radio react components

modules/icon/css/README.md, modules/icon/css/index.scss, modules/icon/css/lib/canvas-kit-css-icon.js, modules/icon/css/lib/icon-list.scss, modules/icon/css/lib/icon.scss, modules/icon/css/lib/utils.js, modules/icon/css/package.json, modules/icon/css/stories.tsx, modules/icon/react/stories/stories.tsx
This PR updates the Icon CSS styles so they match the React component. 
| Breaking Changes | No    | No   |
refactor(icon): Update CSS styles to match React implementation (#159)
=> refactor(icon): Update CSS styles to match React implementation

modules/banner/react/lib/Banner.tsx, modules/checkbox/react/lib/Checkbox.tsx, modules/form-field/react/lib/FormField.tsx, modules/menu/react/lib/MenuItem.tsx, modules/radio/react/lib/Radio.tsx, modules/switch/react/lib/Switch.tsx
=> fix: Extend component props with correct interfaces

modules/_canvas-kit-css/package.json, modules/modal/css/LICENSE, modules/modal/css/README.md, modules/modal/css/index.scss, modules/modal/css/lib/modal.scss, modules/modal/css/package.json, modules/modal/css/stories.tsx, modules/modal/react/stories/stories.tsx, modules/popup/css/README.md, modules/popup/css/index.scss, modules/popup/css/lib/popup.scss, modules/popup/css/package.json, modules/popup/css/stories.tsx
This PR implements the Modal CSS styles so they match the React component. 
| Breaking Changes | No    | No   |
feat(modal): Implement CSS styles to match React implementation (#185)
=> feat(modal): Implement CSS Modal to match React implementation

modules/form-field/react/stories/stories_Switch.tsx, modules/switch/react/README.md, modules/switch/react/lib/Switch.tsx, modules/switch/react/spec/__snapshots__/Switch.snapshot.tsx.snap
This PR addresses:
- Feature request: (https://github.com/Workday/canvas-kit/issues/202) There are no styles for alerts and errors
- Bug: (https://github.com/Workday/canvas-kit/issues/201) The checkbox input is visible on Safari
applicable
=> Switch: Update

modules/action-bar/css/README.md, modules/action-bar/css/stories.tsx, modules/button/css/README.md, modules/button/css/stories.tsx, modules/form-field/css/README.md, modules/form-field/css/stories/stories_Checkbox.tsx, modules/form-field/css/stories/stories_Radio.tsx, modules/form-field/css/stories/stories_Select.tsx, modules/form-field/css/stories/stories_TextArea.tsx, modules/form-field/css/stories/stories_TextInput.tsx, modules/menu/css/README.md, modules/menu/css/stories.tsx, modules/modal/css/README.md, modules/modal/css/stories.tsx, modules/page-header/css/README.md, modules/page-header/css/stories.tsx, modules/popup/css/README.md, modules/popup/css/stories.tsx, modules/table/css/README.md, modules/table/css/stories.tsx, modules/tooltip/css/README.md, modules/tooltip/css/stories.tsx
After finishing the [css-update](#200) branch, we had an audit/review from Accessibility. This branch addresses the items found in that review. While none of these changes are part of the source code of the modules, we want to set a best practice by having accessible examples in the stories and README files.
This PR is blocking #200
=> refactor: A11y updates for CSS stories and Readmes

modules/switch/react/lib/Switch.tsx, modules/switch/react/spec/__snapshots__/Switch.snapshot.tsx.snap
The checkbox input is visible on some web browsers. This PR fixes the issue.
=> fix(switch): Hide checkbox input

modules/checkbox/react/lib/Checkbox.tsx, modules/checkbox/react/spec/Checkbox.spec.tsx
Fixes: https://github.com/Workday/canvas-kit/issues/158
=> fix(checkbox): Change default id to be unique per instance

modules/_labs/README.md, utils/create-component/createComponent.js, utils/create-component/createCssModule.js, utils/create-component/templates/css/stories.js, utils/create-component/templates/react/stories.js
I had a couple bugs for labs modules that slipped in with #211, this resolves them.
=> fix: Address misc. bugs in create-component script

modules/core/react/package.json
=> chore(core): Add react-emotion as a dep

modules/_labs/header/react/lib/Header.tsx
=> fix(header): Support onMenuClick without menuToggle

API_PATTERN_GUIDELINES.md, eslintrc.js, modules/_labs/header/react/lib/parts/DubLogoTitle.tsx, modules/_labs/header/react/lib/parts/Search.tsx, modules/_labs/header/react/lib/parts/WorkdayLogoTitle.tsx, modules/_labs/menu/react/lib/MenuItem.tsx, modules/button/react/lib/ButtonBase.tsx, modules/button/react/lib/ButtonStyles.ts, modules/button/react/lib/DropdownButton.tsx, modules/button/react/lib/IconButton.tsx, modules/button/react/lib/TextButton.tsx, modules/button/react/lib/utils.ts, modules/modal/react/lib/Modal.tsx, modules/page-header/react/lib/PageHeader.tsx
We had some warnings creeping in from #154 and in the tests. This branch resolves all linting warnings. There are still a few test warnings, but they are unrelated to our components. Hoping those are resolved by #267.
=> fix: Resolve lint and test warnings

modules/status-indicator/react/lib/StatusIndicator.tsx
Closes https://github.com/Workday/canvas-kit/issues/91
warning in the console:
```
Using kebab-case for css properties in objects is not supported. Did Did you mean WebkitFontSmoothing?
```
applicable
=> fix(StatusIndicator): Rename -webkit-font-smoothing- to WebkitFontSmoothing

modules/icon/css/package.json
Fixes: https://github.com/Workday/canvas-kit/issues/302
=> fix(icon): Add index.scss to package.json for css icon

COMPONENT_STATUS.md
Fix markup to have the correct cell counts for component status table.
=> docs: Fix Component Status table

README.md
=> chore: Update readme with thankyous

modules/_labs/menu/react/package.json, package.json, yarn.lock
Update to the latest Storybook Chromatic. This should fix the asset issue we've had with Firefox
=> chore: Update Storybook Chromatic

cypress/integration/storybook.spec.ts, package.json
Fixed an issue preventing Storybook from rendering correctly. Also added a test to make sure Storybook documentation works correctly. We had tests for individual stories, but not for Storybook as a whole.
=> docs: Fix Storybook iframe rendering

utils/storybook/StaticStatesTable.tsx
I used an incorrect check in #372 and didn't catch the side effect. This fixes the if statement.
=> test: Fix StaticStatesTable row check

.travis.yml
For our release process we cut a branch called `release` and just update the changelog and bump the package versions using `lerna`. I don't see a reason why we need to explicitly check the build or run tests.
applicable
=> chore: Prevent build on travis release

CHANGELOG.md
Forgot to add the header for the changes.
And one of the PRs was reverted in the release branch.
=> chore: Correct Changelog

.nvmrc
=> chore: Change nvmrc to use lts/dubnium

utils/publish-canary.js
=> ci: Fix undefined variable in canary publish

utils/publish-canary.js
=> ci: Fix testing mistake with canary publish

modules/button/react/lib/ButtonStyles.ts
Fixes: https://github.com/Workday/canvas-kit/issues/368
applicable
=> fix(button): Avoid using transition all for buttons

modules/icon/react/lib/SystemIcon.tsx, modules/icon/react/spec/SystemIcon.spec.tsx
Fixes: https://github.com/Workday/canvas-kit/issues/470
=> feat(icon): Support accent layer

TESTING.md
=> docs: Update docs for visual testing change

commitlint.config.js
This PR treats all the folders in the `_labs` directory as valid scopes for commit messages.
For instance:
```
fix(pagination): Fix something about Pagination
```
=> chore: Add lab modules as valid scopes for commit messages

CONTRIBUTING.md
While going over the developer on boarding, i realized we still reference Enzyme when we've made the switch over to react testing library
=> fix: Update contributing readme with correct testing reference

.travis.yml, package.json, yarn.lock
We can speed up our PRs (and master builds) by reducing the amount of times Storybook gets built between Cypress, Chromatic, and build-storybook
=> build: Improve PR build times

modules/_labs/combobox/react/lib/Combobox.tsx, modules/_labs/combobox/react/stories/stories.tsx, modules/_labs/header/react/lib/parts/SearchBar.tsx
This PR fixes #476 as well as an issue in collapsed mode where the input is too low
I tweaked the story for combobox to catch a regression but it requires autofocus to be set on the input let me know if that can cause issues in automation.
This is a possible alternative to https://github.com/Workday/canvas-kit/pull/485
=> fix: Combobox and search bar not in container

modules/_labs/menu/react/lib/Menu.tsx, modules/_labs/menu/react/lib/MenuItem.tsx
Fixes: https://github.com/Workday/canvas-kit/issues/514
=> fix(menu): Update aria role for menu

modules/_labs/combobox/react/README.md, modules/_labs/combobox/react/lib/Combobox.tsx, modules/_labs/combobox/react/spec/Combobox.spec.tsx, modules/_labs/combobox/react/stories/stories.tsx, modules/_labs/header/react/README.md, modules/_labs/header/react/lib/parts/SearchBar.tsx, modules/_labs/header/react/spec/SearchBar.spec.tsx
To support extending the combobox to support more features I ported the core component to a React Functional Component. ~Nothing in behavior should be changed.~ JK updated a prop name and added a new prop. Let me know if those should go in a separate PR
=> feat(combobox): Convert to functional component and add translation function for status text

COMPONENT_STATUS.md
Added new components and taxonomy changes.
=> docs: Update Component Status

API_PATTERN_GUIDELINES.md, modules/_labs/core/react/lib/CanvasProvider.tsx, modules/core/react/README.md, modules/core/react/lib/InputProvider.tsx, modules/core/react/spec/InputProvider.spec.tsx, utils/storybook/InputProviderDecorator.tsx
Fixes: https://github.com/Workday/canvas-kit/issues/543
=> feat(core): Allow InputProvider to use a configurable container

modules/_labs/menu/react/lib/Menu.tsx
=> fix(menu): Fix flashing on initial selected index

eslintrc.js, modules/_labs/core/react/lib/theming/useTheme.ts, modules/core/react/spec/InputProvider.spec.tsx, modules/icon/css/lib/canvas-kit-css-icon.js, modules/icon/css/lib/utils.js, modules/icon/react/lib/AppletIcon.tsx, package.json, yarn.lock
This hotfix cherry-picks 6b8f2bb70b6b2a7de98a90ea7675174f25cc73c0 and will be released as v3.4.1.
=> Hotfix 3.4.1

package.json, yarn.lock
Addresses vulnerability advisory re: https-proxy-agent
applicable
=> chore: Update Lerna

modules/table/css/stories.tsx
=> fix(table): Remove focus on CSS table rows

.eslintrc.js
Fixes this issue for us: https://github.com/typescript-eslint/typescript-eslint/issues/967
=> fix: Fix ESLint VSCode plugin

utils/publish-canary.js
We just noticed an issue with the deploys for the `prerelease/v4` branch. It's building fine, but it was failing to deploy due to a duplicate version error.
The problem arose because Lerna uses the commit count since the latest annotated tag (using `git describe`) to differentiate versions. While Lerna includes a sha in the version (e.g. `foo@4.0.0-prerelease.12+3d6bee55`), anything after a `+` is stripped out by NPM. Because of this, after creating a beta release our commit count restarted and we were producing duplicate versions.
Unforunately, [Lerna seems to be ignoring the feature request to make this configurable and they aren't offering any support to change this `+` to a `.`](https://github.com/lerna/lerna/issues/1893). This means we need to manually append the sha to the preid. …
=> ci: Fix Prerelease Canary Duplicate Build Versions

modules/badge/css/package.json, modules/badge/react/package.json
Allows Badge packages to be publicly published.
applicable
=> fix: Add public access to Badge publish config

modules/card/react/package.json, modules/card/react/stories/visual-testing/stories_card.tsx
Partially fixes: https://github.com/Workday/canvas-kit/issues/683
Add snapshots for card component
=> test(card): Add stories and enable snapshots

modules/side-panel/react/package.json, modules/side-panel/react/stories/visual-testing/stories_SidePanel.tsx, modules/side-panel/react/stories/visual-testing/stories_VisualTesting.tsx
Partially fixes: #683
Add snapshots for side panel component
=> test(side-panel): Add stories and enable snapshots

modules/segmented-control/react/README.md, modules/segmented-control/react/lib/SegmentedControl.tsx, modules/segmented-control/react/package.json, modules/segmented-control/react/stories/stories.tsx, modules/segmented-control/react/stories/stories_VisualTesting.tsx
In #710 I found a few issues that I wanted to resolve here:
- I thought the selection of the first button wasn't working, but it appears the storybook `action` call is introducing a delay. It still works, but it just takes 1-2 seconds to become toggled. Not sure this is worth dealing with so I just added a comment
- There was a bug with theming
- There were a few labs references left over (Readme and story name)
Also:
- Switched story to CSF
- Added a visual testing story
=> fix(segmented-control): Misc. fixes and story improvements

modules/avatar/react/stories/stories_visualTesting.tsx
Unfortunately Storybook configuration isn't strongly typed.
=> ci(avatar): Fixed threshold setting

modules/status-indicator/react/stories/stories_VisualTesting.tsx
I accidentally merged https://github.com/Workday/canvas-kit/pull/692 without addressing my comment about the icons. This should fix the problem
=> test(status-indicator): Fix visual testing story icons

modules/_labs/select/react/lib/SelectMenu.tsx
Fixes an issue with the Select menu not scrolling to the currently selected option if it's out of view.
=> fix(select): Fix scrolling to the selected option

modules/_labs/header/react/lib/parts/WorkdayLogoTitle.tsx
In #705 we missed using the props correctly in header.
**Note: There are a ton of issues in header related to this problem, but I didn't notice any regressions because of it.**
=> fix(header): Fix header default props

modules/_labs/core/react/stories/stories.tsx, modules/_labs/core/react/stories/stories_visualTesting.tsx
Resolves #709 
This PR updates the Labs/Core snapshots to CSF and adds visual regression tests.
`modules/_labs/core/react/stories/stories_visualTesting.tsx`
* `yarn start`
* View the following stories:
* `?path=/story/labs-core-react--space`
* `?path=/story/labs-core-react--type`
* `?path=/story/testing-react-labs-core--type-and-space`
n/a
applicable
applicable
=> chore: Update Labs Core stories and add snapshots

CHANGELOG.md, modules/_labs/core/react/stories/stories.tsx, modules/_labs/core/react/stories/stories_visualTesting.tsx
=> Merge/master into prerelease/v4

utils/publish-canary.js
`publish-canary.js` had a few errors introduced by #665 
These have been fixed in this PR but I'm really not sure why we haven't run into this within the last few weeks. Still investigating that part.
applicable
=> fix: Address various publish-canary.js bugs

modules/popup-stack/package.json
One small thing we forgot to remove from the `create-module` script output.
=> chore(popup-stack): Fix repo url in package.json

modules/text-area/react/spec/TextArea.spec.tsx
To improve code coverage of the text area component, we should have a functional unit test that ensures the text area value is persisted even when there is a placeholder.
=> test(text-area): Added placeholder with value unit test

modules/avatar/react/lib/Avatar.tsx
fix: #724 
applicable
Before/after
=> fix(avatar): Fix undesired halo around Dark variant

modules/popup/react/README.md
Just a doc update in the Popup Readme.
applicable
=> fix: Update Popup readme example

modules/skeleton/react/README.md, modules/skeleton/react/lib/skeleton.tsx
=> docs(skeleton): Update to remove mention of aria-live

CHANGELOG.md
=> docs: Update CHANGELOG w/ correct release dates

modules/_labs/menu/react/index.ts
Exports the MenuProps interface so we can extend the props for a wrapper component.
- [] tests are changed or added
applicable
Just exporting a type so consumers can extend it.
=> feat(menu): Export MenuProps

cypress/integration/TextArea.spec.ts, cypress/integration/TextInput.spec.ts, modules/button/react/stories/stories_OutlineButton.tsx
Fixes: https://github.com/Workday/canvas-kit/issues/779
Added test to assert the placeholder attribute exist in the text area component as well as the text input component
=> test: Add cypress test for placeholder in input and text area component

modules/_canvas-kit-css/index.scss, modules/_canvas-kit-css/package.json
=> [ISSUE-849] fix: Add canvas-kit-css-badge to canvas-kit-css

modules/core/css/README.md
The Sass variables for the border-radius were incorrect, so I updated them.
applicable
=> fix: Update core CSS border-radius docs

modules/popup/react/README.md
Small documentation update to match the popup API.
=> docs(popup): Fix usePopup hook example docs

COMPOUND_COMPONENTS.md
This doc explains the concept of compound components that is the planned paradigm for building components in Canvas Kit moving forward.
Check out the rendered document here: https://github.com/Workday/canvas-kit/blob/13b61d14c73a48524413fdb7e52d30cdb01961fb/COMPOUND_COMPONENTS.md
=> docs: Add compound component doc

COMPOUND_COMPONENTS.md, modules/core/react/lib/type.ts, yarn.lock
=> Merge/master into prerelease/v5

modules/_labs/side-panel/react/lib/SidePanel.tsx, modules/_labs/side-panel/react/lib/hooks.ts, modules/_labs/side-panel/react/stories/stories.tsx
=> fix(side-panel): Fix keyframes animation

cypress/integration/Tabs.spec.ts, modules/_labs/tabs/react/lib/Tab.tsx
fix [1013](https://github.com/Workday/canvas-kit/issues/1013)
https://user-images.githubusercontent.com/82905449/115457932-f11b3780-a1d9-11eb-8dd0-0d0bf974e43c.mov
=> fix(tabs): Fix aria-selected for unselected tabs

.github/workflows/ci.yml, .nvmrc, .travis.yml
Node 10 is no longer supported
=> ci: Upgrade to node 14

modules/docs/mdx/CREATING_COMPOUND_COMPONENTS.mdx
- Update Disclosure API:
- `state.open` -> `state.visible`
- `events.open` -> `events.show`
- `events.close` -> `events.hide`
- remove `events.toggle`
- Add `mergeProps` where appropriate
=> docs: Update Create Compound Component docs

modules/_labs/combobox/react/lib/Combobox.tsx, modules/_labs/combobox/react/stories/stories.tsx
=> fix(combobox): Fix Combobox RTL issue

yarn.lock
=> fix: Update yarn.lock

modules/checkbox/react/lib/Checkbox.tsx, modules/checkbox/react/spec/Checkbox.spec.tsx
- Add [`aria-checked`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/checkbox_role) for accessibility and easier testability with [`toBeChecked`](https://github.com/testing-library/jest-dom#tobechecked) / [`toBePartiallyChecked`](https://github.com/testing-library/jest-dom#tobepartiallychecked)
=> feat(checkbox): Add aria-checked for accessibility and testability

modules/docs/mdx/5.0-MIGRATION-GUIDE.mdx
=> docs: Review v5 migration guide

modules/react/package.json
=> fix: Update main package deps

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, README.md, modules/docs/mdx/CONTRIBUTING.mdx, modules/react/pagination/README.md, modules/react/pagination/stories/pagination.stories.mdx, modules/react/tabs/README.md
Links to mdx files in docs references .md files and need to be resolved.
=> docs: Update readme links to use mdx

modules/preview-react/breadcrumbs/README.md, modules/preview-react/color-picker/README.md, modules/preview-react/menu/README.md, modules/preview-react/package.json, modules/preview-react/select/README.md, modules/preview-react/side-panel/README.md, modules/react/pagination/stories/pagination.stories.mdx, modules/react/tabs/README.md, modules/react/tabs/stories/Tabs.stories.mdx, modules/react/tokens/lib/type/levels.ts
I found some stragglers from #944. Hopefully this is all of them!
=> docs: Update old labs references

modules/_labs/combobox/react/lib/Combobox.tsx, modules/_labs/combobox/react/spec/Combobox.spec.tsx
Modified Combobox to accept empty strings to allow clearing the combobox input. Part of effort for https://jira2.workday.com/browse/CXS-2565
=> feat(combobox): Modify combobox to accept empty string as initialValue

.storybook/docgen-plugin.js, modules/react/modal/lib/Modal.tsx, modules/react/modal/stories/Modal.stories.mdx, modules/react/modal/stories/examples/ReturnFocus.tsx, modules/react/tokens/stories/stories.tsx
=> docs: Fix prop tables. Also add spec table to Modal

modules/_labs/combobox/react/lib/AutocompleteList.tsx, modules/_labs/combobox/react/lib/Combobox.tsx
Address https://github.com/Workday/canvas-kit/issues/1156
Address https://github.com/Workday/canvas-kit/issues/1112
applicable
=> fix(combobox): Add type attribute and remove tabindex attribute

modules/react/common/lib/utils/components.ts
=> docs: Remove incorrect info on ExtractProps

modules/labs-react/combobox/README.md
When copying the example from the README, I noticed the import for menu item was incorrect. It should be from preview. 
applicable
=> fix(preview): Update readme to show correct import for menu item

cypress/integration/Breadcrumbs.spec.ts, modules/preview-react/breadcrumbs/stories/Breadcrumbs.stories.mdx, modules/preview-react/breadcrumbs/stories/examples/Basic.tsx
Resolves #1166 
Looks like @NicholasBoll merged the last PR (#1206) before @jamesfan got all his comments in. 😄 So, I made a new branch with updates based on that feedback.
applicable
=> docs: Update Breadcrumbs docs to mdx (Review Updates)

modules/react/package.json, yarn.lock
=> chore(table): Update polished package to fix security warning

modules/react/button/stories/button/Button.stories.mdx, modules/react/button/stories/icon-button/IconButton.stories.mdx, modules/react/skeleton/stories/Skeleton.stories.mdx, modules/react/status-indicator/stories/StatusIndicator.stories.mdx, modules/react/table/stories/Table.stories.mdx
Move our variant documentation over so that it's not duplicated in our component articles
=> docs: Improved Variant/Type/State docs

modules/labs-react/common/lib/Box.tsx
=> fix: Add to Box omitted props list

.travis.yml
Travis is broken. This might fix it.
applicable
=> ci: Fix Travis releases

README.md
=> docs: Add Version Support section to Readme

modules/codemod/index.js
=> fix: Update codemod to support output streaming

modules/react/loading-animation/lib/LoadingDots.tsx, modules/react/loading-animation/stories/LoadingAnimation.stories.mdx, modules/react/loading-animation/stories/examples/RTL.tsx
Fixes: #1296 
Using the CKR version of styled fixes the spacing of the loading animation for RTL.
Possible visual regression if you have overrides to get the old version working for RTL.
---
=> fix(LoadingAnimation): Add support for RTL

modules/codemod/index.js, modules/codemod/lib/v7/index.ts, modules/codemod/lib/v7/spec/expectTransformFactory.ts, modules/docs/mdx/7.0-MIGRATION-GUIDE.mdx
=> chore: Initial setup for v7

modules/react/_examples/stories/CookieBanner.stories.mdx, modules/react/_examples/stories/examples/CookieBanner.tsx
=> docs: Add CookieBanner example

modules/preview-react/side-panel/lib/SidePanel.tsx, modules/react/button/lib/IconButton.tsx
Fixes: https://github.com/Workday/canvas-kit/issues/909, https://github.com/Workday/canvas-kit/issues/894
=> fix(side-panel): Add tooltip to toggle button for side panel

modules/preview-react/side-panel/lib/SidePanel.tsx
=> fix(side-panel): Remove console.log

modules/react/popup/lib/hooks/useInitialFocus.tsx, modules/react/popup/stories/stories_testing.tsx
=> fix(popup): Fix body scrolling using useInitialFocus

modules/preview-react/side-panel/stories/examples/AlwaysOpen.tsx, modules/preview-react/side-panel/stories/examples/Basic.tsx, modules/preview-react/side-panel/stories/examples/ExternalControl.tsx, modules/preview-react/side-panel/stories/examples/RightOrigin.tsx, modules/preview-react/side-panel/stories/examples/Variant.tsx
=> docs(side-panel): Fix padding in header

modules/react/cookie-banner/stories/stories.tsx, modules/react/tabs/stories/examples/OverflowTabs.tsx
=> fix: Fix button imports

modules/labs-react/common/lib/Box.tsx, modules/react/common/lib/utils/index.ts
Fixes: #1482 
---
This was already fixed in v7, but we're back-porting it now.
=> fix: Fix Box valid prop passing

modules/react/action-bar/lib/ActionBar.tsx
=> fix(action-bar): Update styled function to support RTL

modules/react/toast/lib/Toast.tsx
=> fix(toast): Add aria attributes to alert toast

modules/css/banner/package.json, modules/css/button/package.json, modules/css/form-field/package.json, modules/labs-react/package.json, modules/preview-react/package.json, modules/react/package.json
=> chore: Update accent, applet, and system icon deps

modules/labs-react/combobox/lib/Combobox.tsx
Fixes: #1559  
If there are a lot of items in a Combobox, the container that the Combobox item is in will increase and can potentially add a scrollbar to the parent/page body.
---
=> fix(combobox): Add "overflow: hidden" to MenuContainer

modules/codemod/lib/v7/index.ts
Adding the codemods to the index file to run
=> fix: Update codemod to run all transforms

modules/react/banner/stories/examples/RefForwarding.tsx, modules/react/tabs/stories/examples/OverflowTabs.tsx
Updates examples in Banner and Tabs to import from packages rather than a path (canvas-site requires package imports when consuming examples from canvas-kit).
=> fix: Fix imports in examples

modules/react/tabs/stories/Tabs.stories.mdx
Fixes the Tabs MDX to account for changes in v7.
=> docs: Fix docs to account for v7 changes

modules/react/table/index.ts, modules/react/table/lib/TableRow.tsx
=> fix(table): Refactor TableRow to use createComponent

modules/docs/mdx/7.0-UPGRADE-GUIDE.mdx
Clean up upgrade docs for BaseButton example
=> docs: Clean up upgrade docs for base button example

modules/react/action-bar/stories/ActionBar.stories.mdx, modules/react/action-bar/stories/examples/DeleteAction.tsx
Resolves: #1627  
PR adds an Action Bar example that uses a Delete Button.
=> docs(action-bar): Add delete action example to ActionBar

modules/react/pagination/lib/Pagination/PageButton.tsx, modules/react/pagination/stories/stories_visualTesting.tsx
Fixes: https://github.com/Workday/canvas-kit/issues/1647
Adds theming support to `PageButton`
=> fix(button): Make PageButton in Pagination themable

cypress/integration/Pagination.spec.ts, modules/react/pagination/lib/Pagination/common/useLiveRegion.tsx
=> fix(pagination): Remove aria-relevant attr

modules/docs/mdx/7.0-UPGRADE-GUIDE.mdx
Fixes: #1688
---
There have been a handful of questions about the removal of `ActionBar`'s `fixed` prop, so I added some more context so we can send a link instead of repeating ourselves in support threads.
=> docs: Update ActionBar upgrade guide docs

modules/codemod/index.js
Enables the `v8` parameter when running the codemod.
=> fix(codemod): Add support for v8 param to codemod

modules/react/popup/lib/hooks/useReturnFocus.tsx
A bug was happening in a model that doesn't specify a return target and only appears in responsive view, where the user resized the screen to make the modal disappear: 
```
Uncaught TypeError: Cannot read properties of null (reading 'parentElement')
at getScrollParent (useReturnFocus.js?92d7:5:1)
```
The existence of the popup in the failing example depends on screen size, and that target doesn't exist when the screen size is big enough again (both popup and target are removed from the DOM) - which crashed the code.
Components
---
=> fix: Error handling to fix TypeError bug on models used in responsive modals/popups

.github/PULL_REQUEST_TEMPLATE.md, cypress/integration/Popup.spec.ts, modules/docs/utils/get-specifications.js
Fixes flaky Cypress popup specification
Test
---
=> test: Fix flaky Cypress popup specification

.github/workflows/project-automations.yml
Fixes invalid workflow for project board automations
Infrastructure
=> ci: Fixing to make workflow valid-name needed for each if [skip release]

modules/docs/mdx/8.0-UPGRADE-GUIDE.mdx
Resolves: #1856  
This will add information about React 18 Upgrade to v8 Upgrade guide
Documentation
=> docs: Add React 18 Upgrade to v8 upgrade guide

modules/docs/mdx/8.0-UPGRADE-GUIDE.mdx
Fixes: #1788  
Adding responsive style support documentation to the v8 upgrade guide. 
Documentation
---
`/modules/docs/mdx/8.0-UPGRADE-GUIDE.mdx`
=> docs: Updating Responsive Styles Support Section of V8 Guide

modules/preview-react/menu/lib/Menu.tsx, modules/react/menu/lib/MenuContextTarget.tsx, modules/react/menu/lib/MenuTarget.tsx
Noticed that some event keys didn't match what is standard based on mdn [keys](https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#navigation_keys)
Also, [modal card padding](https://github.com/Workday/canvas-kit/blob/prerelease/major/modules/react/modal/lib/ModalCard.tsx#L18) should be `24px` not `32px` so this PR fixes that issue as well.
Components
Optional release note message. Changelog and release summaries will contain a pull request title. This section will add additional notes under that title. This section is not a summary, but something extra to point out in release notes. An example might be calling out breaking changes in a labs component or minor visual changes that need visual regression updates. Remove this section if no additional release …
=> fix: Update modal padding and event keys to match modern browsers

modules/react/layout/index.ts, modules/react/layout/lib/Box.tsx, modules/react/layout/lib/utils/styleProps.ts
Fixes: #865
Types
---
`modules/react/layout/index.ts`
n/a
=> feat: Add StyleProp types

README.md
Removing 2 dead links & adding v8 Upgrade Guide link
Documentaion
---
=> chore: Remove deadlinks, add v8 upgrade guide to README

modules/react/common/stories/examples/ResponsiveStyles.tsx
Fixes example codeblock in responsive docs to adjust to smaller sizing of canvas site. 
Fixes: #1922  
Documentation
---
`/modules/react/common/stories/examples/ResponsiveStyles.tsx`
=> docs: Responsive Codeblock Fix

.github/workflows/release.yml
Fixes: #1959
Infrastructure
---
`.github/workflows/release.yml`
=> chore: Remove conventional-recommended-bump from release.yml

modules/css/form-field/stories/stories.tsx
Remove `react` sub folder for css form field
Documentation
---
=> fix: Remove react sub folder for form field

modules/react/text-area/stories/TextArea.stories.mdx
- fix typo in TextArea story mdx for sh command
updates mdx for TextArea story. No breaking changes.
Documentation
---
- [n/a] Breaking Changes provides useful information to upgrade to this code or removed if not applicable
modules/react/text-area/stories/TextArea.stories.mdx
n/a
n/a
n/a
[a smiling Shiba Inu typing on a laptop](https://media.giphy.com/media/mCRJDo24UvJMA/giphy.gif)
=> docs(TextArea): Update installation package name

modules/react/radio/stories/examples/Alert.tsx, modules/react/radio/stories/examples/Basic.tsx, modules/react/radio/stories/examples/Disabled.tsx, modules/react/radio/stories/examples/Error.tsx, modules/react/radio/stories/examples/Inverse.tsx, modules/react/radio/stories/examples/LabelPosition.tsx, modules/react/radio/stories/examples/NoValue.tsx, modules/react/radio/stories/examples/RefForwarding.tsx, modules/react/radio/stories/examples/Required.tsx
Fixes: #1600 
Components
---
https://user-images.githubusercontent.com/32447341/213775483-cefaa65d-75f6-42f3-8e74-cd50b8327384.mov
https://user-images.githubusercontent.com/32447341/213776091-9596c808-d0ec-45e3-8e1e-03a2fe0a4746.mov
@mannycarrera4 brought up two possible solutions to make each storybook to have different `name` value:
- We update each storybook example to have a unique name using useUniqueId so each examples has a unique name
- Or we can update the name property to be something like name="crust1", name="crust2".
I am choosing the solution to use `useUniqueId` to avoid this problem from occurring in the future when someone potentially adds more examples.
=> fix: Radio button navigation does not stay within its form

modules/codemod/lib/softDeprecate/Stack/softDeprecateStack.ts, modules/codemod/lib/softDeprecate/Stack/spec/softDeprecateStack.spec.ts
Adjusted soft dep of `Stack` codemod to adjust styled component. 
`styled(Stack)` -> `styled(Flex)`
Fixes: #2005  
Codemods
`modules/codemod/lib/softDeprecate/Stack/softDeprecateStack.ts`
=> fix: Update to soft dep stack codemod for styled component

modules/react-fonts/README.md
Fixes: #2009 
This fixes an error in the react-fonts package README.
Documentation
---
=> docs: Fix typo in react-font README

modules/react/tooltip/stories/stories_testing.tsx
Chromatic is still having a hard time loading fonts, we've increased the delay to see if it helps.
Testing
---
=> test: Increase font delay to make chromatic happy [skip release]

modules/labs-react/expandable/stories/Expandable.stories.mdx
Fixes: #2015
Documentation
---
`modules/labs-react/expandable/stories/Expandable.stories.mdx`
=> docs: Fix Expandable prop tables

CONTRIBUTING.md
Fixes: #2011 
Documentation
---
=> fix: Update broken link in CONTRIBUTING.md

.github/workflows/reviewer-lottery.yml
Fixes yml error on lottery pr action
Infrastructure
---
=> ci: Fix to invalid yml error [skip release]

modules/react/tooltip/stories/stories_testing.tsx
The placements story takes a second to load because we're rendering the tooltip with popper. The code has some logic for making sure if the popper is open.
Proposal:
- Always set the popper to open=true (we're not testing if the tooltip opens in the placements visual testing)
Remove any useeffect for setting open to true
- Set the font family on tool to sans-serif to make sure we're not waiting on roboto to load
This loads the story instantly in storybook vs before i could see a slight lag
- Add comment int story regarding font 
Testing
---
=> test: Update tooltip testing story to render properly

.github/workflows/project-automations.yml, .github/workflows/reviewer-lottery.yml
Small tweaks to reviewer lottery & project board actions
Infrastructure 
---
=> ci: Updates to lottery and project actions [skip release]

package.json
Update the `browserlist` in `package.json`. We dropped support for IE11 and we support Firefox ESR.
Infrastructure
---
package.json
=> chore: Update browserlist config for eslint compat/compat [skip release]

modules/docs/docgen/plugins/enhancedComponentParser.ts
Fixes: #2084
Documentation
---
=> docs: Filter out model props in container components

modules/docs/mdx/9.0-UPGRADE-GUIDE.mdx
Fixes: #2093 
Layout removal section haas been deleted from v9 Upgrade Guide with #2012.
Documentation
=> docs: Revert removal of Layout section

modules/react/button/stories/button/Button.stories.mdx
Resolves: #2098 
Documentation
---
=> docs: Added doc for Delete Button story

modules/react/layout/lib/utils/position.ts
Add a new `inset` property to position props list.
Resolves: #2100
Components
---
@vibdev Please let me know if I added this to the right place (: 
Tested this new property in `modules/react/layout/stories/stories_BoxVisualTesting.tsx`.
=> feat: Added inset to PositionStyleProps

modules/codemod/lib/v9/deprecateStack.ts, modules/codemod/lib/v9/spec/deprecateStack.spec.ts
Some typos/copy paste issues were caught. This is a PR to fix them. 
Fixes: #2126  
Codemods
---
=> fix: Stack Codemod Fix

modules/react/common/lib/utils/colorUtils.ts, modules/react/common/spec/colorUtils.spec.tsx, modules/react/icon/lib/AccentIcon.tsx, modules/react/icon/lib/SystemIcon.tsx, modules/react/icon/lib/SystemIconCircle.tsx, modules/react/icon/lib/utils.ts, modules/react/icon/spec/AccentIcon.spec.tsx, modules/react/icon/spec/SystemIcon.spec.tsx
Resolves: #2014 
Components
Optional release note message. Changelog and release summaries will contain a pull request title. This section will add additional notes under that title. This section is not a summary, but something extra to point out in release notes. An example might be calling out breaking changes in a labs component or minor visual changes that need visual regression updates. Remove this section if no additional release notes are required.
---
=> feat: Allow Icon components to use color tokens

modules/react/common/lib/utils/memoize.ts, tsconfig.json
Fixes #2117
Infrastructure
We're updating our build target from `es5` to `es2019`. This changes the syntax generated by allowing syntax supported up to `es2019`. This may impact older environments that do not support `es2019` syntax like older versions of nodejs. This could also impact older AST build parsers that don't understand newer JavasScript syntax. This could include old versions of Webpack or outdated babel parsers for Jest. If you see a message like "Syntax Error", you may have to upgrade your bundler or babel parser.
---
Testing heavily depends on the environment. Some internal teams have been testing changes to the target, but ultimately it will depend on what tools are used.
=> chore: Update the TSconfig target to es2019

.github/workflows/release-minor.yml, .github/workflows/release.yml
Fixes: #2141  
This PR updates release and minor release actions to use node 16. 
Infrastructure
=> fix: Update release actions to use node 16

.github/workflows/release.yml
Fixes: #2169 
PR to fix release action in support branch to support node 16
Infrastructure
=> fix: Update release action to support node 16

modules/react/collection/index.ts, modules/react/collection/lib/useCursorListModel.tsx, modules/react/collection/lib/useListItemAllowChildStrings.ts, modules/react/collection/lib/useListItemRovingFocus.tsx, modules/react/collection/lib/useListLoader.ts, modules/react/collection/spec/useListItemAllowChildStrings.spec.tsx, modules/react/collection/stories/Collection.stories.mdx, modules/react/collection/stories/examples/DataLoader.tsx
Add a list data loader to help with dynamically loaded data from the server. Adds documentation, tests, and an example.
Components
A data loader has been added to collections systems to make it easier to interact with server data.
```tsx
const {model, loader} = useListLoader(
{
total: 1000,
pageSize: 20,
async load({pageNumber, pageSize}) {
return fetch('/myUrl')
.then(response => response.json())
.then(response => {
return {total: response.total, items: response.items};
});
},
},
useListModel
);
```
---
Look at the data loader example: https://5d854c26ba934e0020f5e98a-mtxfwpxxbl.chromatic.com/?path=/story/features-collections--data-loader
=> feat(collection): Add a list data loader

modules/react/collection/spec/useListLoader.spec.ts
Add test for the `useListLoader` hook.
Components
---
=> test(collection): Add List Loader spec

modules/react/checkbox/lib/Checkbox.tsx
=> fix: Fix Checkbox label padding to support RTL

modules/docs/mdx/10.0-UPGRADE_GUIDE.mdx
Adding the v10 upgrade guide
Documentation
---
=> chore: Adding v10 upgrade guide

modules/preview-react/table/lib/Table.tsx
Fixes: #2210  
Replaced overflow: scroll with overflow: auto to hide scrollbars unless needed. It would allow Table to not have scrollbars unless needed
Components
We replaced overflow: scroll with overflow: auto to hide scrollbars unless needed. It would allow Table to not have scrollbars unless needed. 
---
=> fix: Replace overflow on Table

modules/react/popup/lib/Popper.tsx, modules/react/popup/lib/fallbackPlacements.ts, modules/react/popup/spec/Popper.spec.tsx
=> fix: Fix Popper imports

modules/react/common/lib/styles/accessibleHide.ts
Updates the comment describing accessibleHide utility to use more inclusive language.
Documentation
---
=> docs: Update comment describing accessibleHide utility

modules/preview-react/status-indicator/lib/StatusIndicatorIcon.tsx
Fixes: https://github.com/Workday/canvas-kit/issues/2277
Components
---
=> fix: Update status indicator icon color on hover

modules/react/common/lib/utils/colorUtils.ts
Fixes: #2311
Documentation
---
=> fix: Fix color util typo

modules/react/tabs/lib/TabsItem.tsx
Fixes: #2354 
Slugified the aria-controls value as described in the issue. `Tabs.Panel`  `id` attribute value is now the same as the `Tabs.Item` `aria-controls` value.
Components
---
=> fix(tabs): Slugify Tabs.Item aria-controls attribute (#2354)

modules/react/select/stories/examples/MenuHeight.tsx, modules/react/select/stories/examples/Required.tsx, modules/react/select/stories/examples/WithIcons.tsx
Removes unnecessary exports from a few Select examples. Our docs build process contains [logic](https://github.com/Workday/canvas-kit/blob/master/modules/docs/utils/build-mdx.js#L104) which replaces named exports with default exports (the site needs them to be default exports). The extra exports in the Select examples were being rewritten to default exports, which prevented the actual example code from referencing them. 
Documentation
---
=> docs: Fix Select examples

modules/react/combobox/lib/Combobox.tsx, modules/react/combobox/lib/ComboboxCard.tsx, modules/react/combobox/lib/ComboboxInput.tsx, modules/react/combobox/lib/ComboboxMenu.tsx, modules/react/combobox/lib/ComboboxMenuItem.tsx, modules/react/combobox/lib/ComboboxMenuList.tsx, modules/react/combobox/lib/hooks/useComboboxInput.ts, modules/react/combobox/lib/hooks/useComboboxListKeyboardHandler.ts, modules/react/select/lib/Select.tsx
Update an import that causes a circular dependency.
Components
---
=> fix(select): Fix circular import statement

modules/react/modal/lib/ModalOverlay.tsx
Fixes: https://github.com/Workday/canvas-kit/issues/2352
Components
---
=> fix: Prevent modal from overlapping on mobile devices

modules/preview-react/_examples/stories/examples/SelectWithFormik.tsx, modules/preview-react/_examples/stories/examples/TextInputWithReactHookForm.tsx
Updates the example Forms to use both uncontrolled and controlled versions of the new mainline `<Select />` component.
Documentation
---
Try it out in storybook
=> docs(select): Add controlled and uncontrolled Select examples

modules/preview-react/index.ts
Fixes: #2417 
Fixes index file to export `Table` in preview.
Components
---
`/modules/preview-react/index.ts`
=> fix: Table in preview export fix

modules/styling/lib/cs.ts
Fixes: #2450
Just removing a console log which was spamming my console
Components
=> fix: Remove console.log

modules/react/_examples/stories/SearchForm.stories.mdx, modules/react/_examples/stories/examples/SearchFormBasic.tsx
Adds an example for how to build a basic search form using the latest canvas kit components. This does not include an example with typeahead/autocomplete.
Documentation
---
=> docs(_examples): Add example for basic search form

modules/styling/lib/cs.ts, modules/styling/spec/cs.spec.tsx, modules/styling/stories/Stencils.stories.mdx, modules/styling/stories/examples/CreateStencil.tsx
Resolves: #2464
Adds stencils to the `styling` package to help organize component styles.
Discussion: #2412
Components
---
=> feat: The one with Stencils

modules/preview-react/pill/lib/Pill.tsx
Fixes: #2466  
Removes console logs from Pill.tsx component. 
Components
=> fix(Pill): Remove Console Logs

modules/styling-transform/lib/styleTransform.ts, modules/styling-transform/spec/styleTransform.spec.ts, modules/styling/lib/cs.ts, modules/styling/spec/cs.spec.tsx
Adds the `makeEmotionSafe` function to the styling transform function.
Fixes: #2469
Infrastructure
---
Spec file
=> fix: Make the style transform Emotion safe

modules/react/tokens/lib/type/index.ts, modules/styling/index.ts, modules/styling/lib/calc.ts, modules/styling/lib/px2rem.ts, modules/styling/spec/calc.spec.ts, modules/styling/spec/px2rem.spec.ts, modules/styling/stories/StylingFunctions.stories.mdx
Resolves: #2474
Styling
---
`/modules/styling/lib/negate.ts`
=> feat: Add Canvas styling functions

.github/reviewer-lottery.yml
Remove James for now
Infrastructure
---
=> ci: Update reviewer-lottery.yml [skip release]

.eslintrc.js, modules/react/common/lib/CanvasProvider.tsx, modules/react/layout/lib/utils/mergeStyles.ts, modules/react/layout/spec/mergeStyles.spec.tsx, modules/styling/lib/cs.ts
Fixes: #2504
I'm not sure why this rule was added, but we've been manually ignoring it, so we might as well get rid of the rule.
Infrastructure
---
=> chore: Remove ESLint warning for @emotion/css

cypress/integration/Popup.spec.ts, modules/react/popup/lib/hooks/useCloseOnOutsideClick.ts, modules/react/popup/stories/stories_testing.tsx
Fixes: https://github.com/Workday/canvas-kit/issues/2314
Components
Prevents popup or dialog from closing when a combobox menu item is selected.
---
=> fix: Prevent popup from closing when combobox item is clicked

modules/docs/mdx/11.0-UPGRADE-GUIDE.mdx, modules/preview-react/form-field/lib/FormField.tsx, modules/preview-react/form-field/lib/FormFieldHint.tsx
Fixes: https://github.com/Workday/canvas-kit/issues/2398
Components
Update FormField in Preview to use our new styling utilities and tokens.
---
=> chore: Refactor FormField in Preview to use new styling utilities and tokens

modules/docs/mdx/11.0-UPGRADE-GUIDE.mdx, modules/react/switch/lib/Switch.tsx
Fixes: #2389  
Updates styles to use new style utilities and variables.
Components
Switch now uses Canvas Tokens and our new styling utilities. The component now supports the cs prop, but otherwise the API has not changed. It should behave identically as it did in previous versions however, there may be some slight visual changes.
There may be slight visual changes.
---
`/modules/react/switch/lib/Switch.tsx`
`/modules/docs/mdx/11.0-UPGRADE-GUIDE.mdx`
=> chore: Switch Styles Refactor

modules/preview-react/radio/lib/RadioGroup.tsx, modules/preview-react/radio/lib/RadioLabel.tsx, modules/preview-react/radio/lib/RadioText.tsx, modules/preview-react/radio/lib/StyledRadioButton.tsx, modules/preview-react/table/lib/Table.tsx, modules/preview-react/table/lib/TableBody.tsx, modules/preview-react/table/lib/TableCaption.tsx, modules/preview-react/table/lib/TableCell.tsx, modules/preview-react/table/lib/TableFooter.tsx, modules/preview-react/table/lib/TableHead.tsx, modules/preview-react/table/lib/TableHeader.tsx, modules/preview-react/table/lib/TableRow.tsx
Fixes: #2584 
Updating these two previous refactors to use style structure and createStencil as default moving forward.
Components
---
`/modules/preview-react/radio/lib/RadioButton.tsx`
`/modules/preview-react/table/lib/Table.tsx`
=> chore: Updated Radio(Preview) & Table(Preview) with createStencil

.yarnrc, package.json, yarn.lock
Fixes: #2638  
Addressing critical issues brought up by dependabot.
Dependencies
---
`/package.json`
=> chore: Addressing dependency issues [skip release]

.yarnrc
Fixes yarnrc.
Dependencies
---
`/.yarnrc`
=> fix: Fixed yarnrc [skip release]

cypress/integration/Popup.spec.ts, modules/react/select/spec/Select.spec.tsx
Remove `.only` from tests.
Tests
---
=> test: Remove dot only from tests 

modules/react/tooltip/lib/OverflowTooltip.tsx
Thir [PR](https://github.com/Workday/canvas-kit/pull/2548) introduced an overzealous calculation to show the tooltip. Until we find a better solution described in this [issue](https://github.com/Workday/canvas-kit/issues/2645), reverting this change for now.
Components
Reverting the sub pixel calculation on the overflow logic until we find a better solution.
---
=> fix: Revert overflow calculation until we find a better solution

.github/workflows/scorecard.yml
Looks like scorecard had a breaking change, updating it to a non breaking change: https://github.com/ossf/scorecard-action/issues/997
Actions
---
=> fix: Update scorecard.yml [skip release]

modules/docs/package.json, modules/preview-react/package.json, modules/react/package.json, modules/styling-transform/package.json, modules/styling/package.json, package.json, yarn.lock
Resolves: #2680
Infrastructure
---
=> chore: Bump canvas-tokens-web

.github/workflows/canary.yml, package.json, yarn.lock
Adds `@storybook/cli` as a dev dependency so the `package.json` can control the version needed.
Infrastructure
=> ci: Add @storybook/cli as a dev dependency

modules/docs/mdx/10.0-UPGRADE-GUIDE.mdx, modules/react/select/lib/Select.tsx
This PR clarifies some vagueness in the v10 upgrade guide around Select, and it corrects some Select JSDoc typos
Documentation
---
=> docs: Clarify and correct Select docs

modules/docs/mdx/11.0-UPGRADE-GUIDE.mdx, modules/react/badge/lib/CountBadge.tsx, modules/react/card/stories/examples/Stencils.tsx, modules/react/checkbox/lib/CheckBackground.tsx, modules/react/collection/lib/ListBox.tsx, modules/react/icon/lib/Svg.tsx, modules/react/icon/lib/SystemIconCircle.tsx, modules/react/menu/lib/MenuCard.tsx, modules/react/switch/lib/Switch.tsx, modules/react/table/lib/Table.tsx, modules/react/table/lib/TableBody.tsx, modules/react/table/lib/TableCaption.tsx, modules/react/table/lib/TableCell.tsx, modules/react/table/lib/TableFooter.tsx, modules/react/table/lib/TableHead.tsx, modules/react/table/lib/TableHeader.tsx, modules/react/table/lib/TableRow.tsx, modules/styling-transform/lib/utils/handleCreateStencil.ts, modules/styling-transform/spec/utils/handleCreateStencil.spec.ts, modules/styling/lib/cs.ts
Add `box-sizing: border-box` automatically to all stencils.
Components
Adds `box-sizing: border-box` to all stencils. If your stencil did not add this style already, it may change the way `width` works for the component. Our intent is to make all elements use border box layouts to make width calculations more predictable. This change may change the way your component works if you use the `width` style property.
---
=> feat: Add box-sizing:border-box automatically to all stencils

modules/docs/mdx/11.0-UPGRADE-GUIDE.mdx, modules/react/loading-dots/lib/LoadingDots.tsx
Resolves: #2545 
`LoadingDots` has been updated to use system color tokens and stencils.
Components
=> chore: Update LoadingDots styles

modules/preview-react/radio/lib/RadioText.tsx, modules/preview-react/radio/lib/StyledRadioButton.tsx
Fixes: #2591 
Radio has been updated to use system colors
Components
=> chore: Update Radio to use system colors

modules/react/table/lib/Table.tsx, modules/react/table/lib/TableCaption.tsx, modules/react/table/lib/TableCell.tsx, modules/react/table/lib/TableHead.tsx, modules/react/table/lib/TableHeader.tsx, modules/react/table/lib/TableRow.tsx, modules/react/table/stories/stories_visualTesting.tsx
Fixes: #2595  
Refactor Table styles to use system tokens and remove base tokens.
Components
---
`/modules/react/table/stories/stories_visualTesting.tsx`
`/modules/react/table/lib`
=> chore(table): Refactor table to use system tokens

modules/react/collection/lib/useCursorListModel.tsx
Fixes: #2712  
Components
---
\modules\react\collection\lib\useCursorListModel.tsx
=> fix: Remove unused state parameter from getFirst in useCursorListModel

modules/preview-react/status-indicator/lib/StatusIndicator.tsx
Remove extra character from style property from StatusIndicator in Preview.
Components
---
=> fix: Remove extra character from style property

modules/styling/stories/Basics.stories.mdx
Fixes a small typo in a code example.
Documentation
=> docs: Fix typo

modules/docs/mdx/11.0-UPGRADE-GUIDE.mdx
Add info about our tokens to upgrade guide.
Documentation
---
=> fix: Add explicit info about tokens

modules/docs/package.json, modules/preview-react/package.json, modules/react/package.json, modules/styling-transform/package.json, modules/styling/package.json, package.json, yarn.lock
Fixes: #2761  
Updated Canvas Kit to use latest `canvas-tokens-web` dependency to version `2.0.0`.
Dependencies
---
`/package.json`
`/modules/docs/package.json`
`/modules/preview-react/package.json`
`/modules/react/package.json`
`/modules/styling/package.json`
`/modules/styling-transform/package.json`
=> chore: Updated Canvas Tokens Web Dependency to version 2.0.0

modules/docs/mdx/versionsTable.tsx
Fixes: #2791.
This adds CK v10 to the versions table in Storybook.
Documentation
---
Storybook versions table: http://localhost:9001/?path=/story/versions--page
Review Storybook versions table: http://localhost:9001/?path=/story/versions--page and make sure v10 link works.
https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExd28zM3A2eHRhMjV4Mm94Y28zbGZwZmZ3MGgzcGJlOWQwYnlmbHNkdSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/2xPVbsoYpYbEjYQVei/giphy.gif
=> docs: Add v10 to versions table

modules/react/button/lib/BaseButton.tsx, modules/react/button/stories/button/Button.stories.mdx, modules/react/button/stories/button/examples/Grow.tsx, modules/react/button/stories/visual-testing/stories_ButtonGrow.tsx
Addressed the grow prop not working as intended. This is an issue from v10 as well. 
Fixes: #2789  
A fix to the `grow` prop on buttons. 
Components
---
`/modules/react/button/lib/BaseButton.tsx`
=> fix: Grow Prop Fix for Buttons

modules/codemod/package.json, yarn.lock
Revert jscodeshift bump since it didn't fix SNYK issues. We'll address security issues in a separate PR.
Infrastructure
---
=> fix: Revert jscodeshift version [skip release]

modules/react/button/lib/DeleteButton.tsx, modules/react/button/lib/PrimaryButton.tsx, modules/react/button/lib/SecondaryButton.tsx, modules/react/button/lib/TertiaryButton.tsx, modules/react/button/stories/button/examples/CustomStyles.tsx
Fixes: https://github.com/Workday/canvas-kit/issues/2817
Components
---
=> fix: Fix backwards compatibility with colors prop for buttons

modules/react/avatar/lib/Avatar.tsx, modules/react/avatar/stories/stories.tsx
Add `loading="lazy"` to the Avatar image element.
Fixes: #2832 
Components
---
=> fix(avatar): Lazy load avatar images

modules/styling/stories/Basics.stories.mdx
Fixes: #2846
Documentation
---
=> docs: Fix stencil docs typo

modules/labs-react/search-form/lib/SearchForm.tsx
=> fix(SearchForm): Suppress forwarding props warning

cypress/integration/Modal.spec.ts, modules/react/modal/lib/Modal.tsx, modules/react/modal/lib/hooks/useModalCard.ts
Fixes: https://github.com/Workday/canvas-kit/issues/2853
Set `aria-modal` to false to provide better accessibility in Modals that might have a popup like a Select. 
Accessibility
---
=> fix: Set aria-modal to false for better accessibility

cypress/integration/Select.spec.ts, modules/react/select/lib/Select.tsx, modules/react/select/lib/hooks/useSelectInput.ts
Fixes: https://github.com/Workday/canvas-kit/issues/2873
Components
---
=> fix: Update select to trigger onChange

modules/docs/mdx/welcome.stories.mdx, modules/docs/mdx/welcomePage.tsx
Add clear info on canvas provider on install page to match our docs.
Documentation
---
=> docs: Update CanvasProvider info on install page

modules/react/icon/lib/SystemIcon.tsx
Fixes: https://github.com/Workday/canvas-kit/issues/2930
Components
---
=> fix: Allow inherit background color on system icon

modules/react/button/lib/BaseButton.tsx
Fixes: #2940  
Addresses issue for theming the buttons in the `Pagination` component. 
Components
Fixes theming for the `BaseButton` within `Pagination`. 
---
`/modules/react/button/lib/BaseButton.tsx`
=> fix: Update BaseButton to use correct theming color for focus ring

.github/workflows/canary.yml
Update comment to trigger a canary release
Infrastructure
---
=> fix: Update comment for canary action

modules/react/checkbox/stories/visualTesting.stories.tsx, modules/react/color-picker/stories/visualTesting.stories.tsx, modules/react/form-field/stories/visualTesting.stories.tsx, modules/react/radio/stories/visualTesting.stories.tsx, modules/react/switch/stories/visualTesting.stories.tsx, modules/react/text-area/stories/visualTesting.stories.tsx, modules/react/text-input/stories/visualTesting.stories.tsx
Add visual testing back in that were removed by accident during form field promotion
Components
---
=> fix: Add visual testing for inputs after form field promotion

.github/workflows/canary.yml, package.json, yarn.lock
We keep waiting for puppeteer to work in CI and it's failing. [This](https://github.com/storybookjs/storybook/issues/13561) might be a solution
Infrastructure
=> fix: Try to fix canary build

modules/react/menu/lib/MenuItem.tsx, modules/react/select/stories/examples/Basic.tsx, modules/react/select/stories/stories_VisualTesting.tsx
Fixes: #2974  
A fix to Menu Item to break a long unbroken string for `Select`. 
Components
A fix to Menu Item to break a long unbroken string for `Select`. 
---
`/modules/react/menu/lib/MenuItem.tsx`
=> fix: Unbroken String Overflow Menu Item Fix

.storybook/routes.js
CI keeps reporting duplicate keys in a file, this PR removes them.
Infrastructure
---
=> fix: Remove duplicate keys from routes

modules/react/button/lib/parts/ButtonLabelIcon.tsx, modules/react/button/stories/button/examples/Primary.tsx
Fixes: https://github.com/Workday/canvas-kit/issues/3000
Components
---
=> fix: Ensure button label icon uses rem

cypress/integration/Select.spec.ts, modules/react/select/lib/hooks/useSelectInput.ts
Fixes: https://github.com/Workday/canvas-kit/issues/3007
Components
---
=> fix: Update Select to open with spacebar

.github/workflows/forward-merge.yml
Fixes: #3026  
Updating the forward merge yml file to add `--component` flag.
Infrastructure
---
`/.github/workflows/forward-merge.yml`
=> ci: Updated forward merge yml

.github/workflows/canary.yml, .github/workflows/dist-tag.yaml, .github/workflows/forward-merge.yml, .github/workflows/pull-request.yml, .github/workflows/release-major.yml, .github/workflows/release-minor.yml, .github/workflows/release.yml
Update Github Actions node version to 18
Infrastructure
---
=> ci: Update node version in our github actions [skip release]

cypress/component/Tabs.spec.tsx, modules/preview-react/multi-select/lib/MultiSelectInput.tsx, modules/preview-react/multi-select/lib/MultiSelectedItem.tsx, modules/preview-react/multi-select/lib/MultiSelectedList.tsx, modules/preview-react/multi-select/lib/useMultiSelectItemRemove.ts, modules/preview-react/multi-select/lib/useMultiSelectModel.ts, modules/preview-react/multi-select/stories/examples/Basic.tsx, modules/preview-react/multi-select/stories/examples/Complex.tsx, modules/preview-react/multi-select/stories/examples/Controlled.tsx, modules/preview-react/multi-select/stories/examples/Icons.tsx, modules/preview-react/multi-select/stories/examples/Searching.tsx, modules/react/collection/index.ts, modules/react/collection/lib/focusOnCurrentCursor.ts, modules/react/collection/lib/listItemRemove.ts, modules/react/collection/lib/useListItemRemoveOnDeleteKey.tsx, modules/react/collection/lib/useListItemRovingFocus.tsx, modules/react/collection/lib/useListLoader.ts, modules/react/collection/lib/useListResetCursorOnBlur.tsx, modules/react/collection/lib/useSelectionListModel.tsx, modules/react/combobox/lib/hooks/useComboboxInput.ts, modules/react/select/stories/examples/Controlled.tsx
Fixes: #3025
Adds `remove` event to the `ListModel`. An `onRemove` config should be added to dynamic lists to remove the item from the collection.
The `MultiSelect.Input` uses this new remove event to handle removing items from the Selected pill list when the user uses the “Delete” key. Focus is managed by the collection system when an item is removed.
Components
---
=> feat(collection): Add removable support

README.md
Updates the first example in readme to use slash imports
Documentation
---
=> docs: Use slash import in first example

.storybook/routes.js, README.md, modules/docs/mdx/10.0-UPGRADE-GUIDE.mdx, modules/docs/mdx/11.0-UPGRADE-GUIDE.mdx, modules/docs/mdx/12.0-UPGRADE-GUIDE.mdx, modules/docs/mdx/CONTRIBUTING.mdx, modules/docs/mdx/welcome.mdx, modules/docs/mdx/welcomePage.tsx, modules/preview-react/menu/lib/Menu.tsx, modules/preview-react/menu/lib/MenuItem.tsx, modules/preview-react/radio/stories/Radio.mdx, modules/preview-react/status-indicator/stories/StatusIndicator.mdx, modules/react/_examples/stories/mdx/CompoundComponent.mdx, modules/react/badge/stories/CountBadge.mdx, modules/react/button/stories/button/Button.mdx, modules/react/card/stories/card.mdx, modules/react/checkbox/stories/Checkbox.mdx, modules/react/combobox/stories/Combobox.mdx, modules/react/form-field/stories/FormField.mdx, modules/react/select/stories/Select.mdx, modules/react/switch/stories/Switch.mdx, modules/react/table/stories/Table.mdx, modules/react/text/stories/BodyText.mdx, modules/react/text/stories/Heading.mdx, modules/react/text/stories/Subtext.mdx, modules/react/text/stories/Text.mdx, modules/react/text/stories/Title.mdx, modules/styling/README.md, modules/styling/stories/mdx/Overview.mdx
Fixes: #3064  
Updating links that were broken from the Storybook 7 upgrade. 
Documentation
---
`/modules/react/`
=> fix: Fixes Broken Links from Storybook 7 Upgrade

modules/docs/mdx/welcome.mdx
Fixes: #3068  
This is a fix to the Welcome Page mdx. 
Documentation
---
`/modules/docs/mdx/welcome.mdx`
=> fix: Fixed Welcome Page [skip release]

modules/docs/mdx/versionsTable.tsx
Fixes: #3070  
Updates versions table in docs. 
Documentation
---
`/modules/docs/mdx/versionsTable.tsx`
=> fix: Addressed Versions Table Update

modules/preview-react/index.ts
Fixes: #3092  
Added the new and updated CKR Dub and logo references to export from the preview package. 
Components
---
`/modules/preview-react/index.ts`
=> fix: Added CKR Dub and Logo References to preview package

modules/react/menu/lib/MenuItem.tsx, modules/react/menu/stories/testingVisual.stories.tsx
Fixes: https://github.com/Workday/canvas-kit/issues/3091
Components
---
=> fix: Add overflowWrap on MenuItem

modules/codemod/index.js, modules/codemod/lib/v13/index.ts, modules/codemod/lib/v13/utils/getImportRenameMap.ts, modules/docs/mdx/13.0-UPGRADE-GUIDE.mdx, modules/docs/mdx/versionsTable.tsx
Set up initial files for v13.
Documentation
---
=> chore: Set up v13 files

modules/react/tooltip/stories/Tooltip.mdx
Add missing semi colon to tooltip mdx
Documentation
---
=> fix: Add missing semicolon to tooltip mdx

modules/react/tooltip/stories/Tooltip.mdx
Storybook doesn't catch error, updating Tooltip mdx to correctly import components.
Documentation
---
=> fix: Update tooltip mdx to correctly render

modules/styling/lib/cs.ts
If Canvas Kit Styling is duplicated by bundling a copy, a new Emotion cache instance is created. The fix is to share an Emotion cache via the window object (if available). This will both decrease duplicated styles being injected into the page as well as fix style merging issues when a bundle is loaded after another bundle already loaded and rendered.
Fixes: #3151
Infrastructure
This change shares an Emotion cache instance on the window object. This will fix style merge issues in edge cases where a bundle's base styles override override styles of another bundle. It is unlikely that anyone relies on this broken functionality, but if anyone does, styles may be different. This change will only affect style merging from this release on and will not affect any previous version, so it is an …
=> fix(styling): Share a global Emotion instance between CK instances

modules/react/collection/lib/useBaseListModel.tsx
Issue warnings when id or text values cannot be found on a list.
Documentation
---
- [ x Label `ready for review` has been added to PR
=> chore(collection): Add contextual message when ID can't be found

modules/docs/mdx/13.0-UPGRADE-GUIDE.mdx, modules/react/tooltip/lib/TooltipContainer.tsx, modules/react/tooltip/stories/examples/Placements.tsx
Fixes: #2777  
Refactored the `Tooltip` component to use new styling utilities and tokens. 
Components
---
`/modules/react/tooltip`
=> feat: Refactor Tooltip component to use new styling utilities and tokens

modules/react/collection/lib/useBaseListModel.tsx
Fixes: https://github.com/Workday/canvas-kit/issues/3186
Components
---
=> fix: Ensure text visible when select model is hoisted

modules/docs/mdx/TESTING.mdx
Fixes: #3179
Adding a serializer example for modifier class name.
Documentation
=> docs: Updated snapshot serializers doc with modifier class name use case

modules/react/icon/lib/Graphic.tsx
Fixes the issue where `btoa` is not a valid encoder in nodejs environments. The fix ensures to use `btoa` if window is defined otherwise, use `Buffer`.
Components
---
=> fix: Account for nodejs environemnts when encoding data

modules/react/icon/lib/Graphic.tsx, modules/react/icon/stories/Icons.stories.tsx
The underlying `img` element was setting the correct height and width, but the `span` should also receive the same height and width.
Components
---
=> fix: Pass height and width to Graphic span element

modules/react/icon/lib/Graphic.tsx
Ensures btoa is defined in the browser else, use Buffer in nodejs environments. Also sets the width to 100% on span element.
Components
---
=> fix: Ensure btoa is defined on window

modules/preview-react/pill/lib/Pill.tsx, modules/preview-react/pill/lib/PillCount.tsx
Clean up some styles based on latest specs
Components
---
=> fix: Update Pill styles based on spec

modules/react/collection/lib/keyUtils.ts
Fixes keyboard navigation for menus when document is RTL mode
Components
=> fix(menu): Support vertical navigation in RTL document mode

modules/preview-react/information-highlight/lib/parts/Body.tsx, modules/preview-react/information-highlight/stories/examples/Critical.tsx, modules/preview-react/information-highlight/stories/examples/Informational.tsx
The `InformationHighlight.Body` subcomponent was previously a `p` element, which is _fine_ on its own, but it makes things unintuitive when you need to add multiple blocks of content inside the `Body`. Nesting `p` elements or adding list elements (`ul` or `ol`) is not allowed. To solve this, we're making `Body` a generic `div` element. This is consistent with our other `Body` subcomponents such as `Modal.Body`.
Fixes: #3218
Components
There are no visual changes because of this update. However, if you were relying on the `p` tag as an identifier for testing or other purposes, you'll need to adjust your implementation, as the underlying element is now a `div`. Additionally, if you'd like to keep a `p` tag around the `Body` text, you'll need to add it manually. Wrapping text in a `p` is not …
=> fix: Update InformationHighlight.Body to use div

modules/docs/mdx/13.0-UPGRADE-GUIDE.mdx, modules/preview-react/pill/lib/PillAvatar.tsx, modules/preview-react/pill/stories/examples/WithAvatar.tsx, modules/preview-react/pill/stories/examples/WithRemovable.tsx, modules/preview-react/pill/stories/testing.stories.tsx, modules/preview-react/side-panel/stories/testingCypress.stories.tsx, modules/react/_examples/stories/mdx/examples/GlobalHeader.tsx, modules/react/avatar/lib/Avatar.tsx, modules/react/avatar/stories/avatar/examples/Basic.tsx, modules/react/avatar/stories/avatar/examples/Button.tsx, modules/react/avatar/stories/avatar/examples/CustomStyles.tsx, modules/react/avatar/stories/avatar/examples/Image.tsx, modules/react/avatar/stories/avatar/examples/LazyLoad.tsx, modules/react/avatar/stories/avatar/examples/ObjectFit.tsx, modules/react/avatar/stories/avatar/examples/Size.tsx, modules/react/avatar/stories/avatar/examples/Variant.tsx, modules/react/expandable/stories/examples/Avatar.tsx, modules/react/expandable/stories/examples/LongTitle.tsx
Fixes: #3116 
Removed the `altText` default prop of `"Avatar"` for better internationalization. 
Components
Removed the default text for the `altText` prop on `Avatar`.
The `altText` prop no longer has a default of `"Avatar"`.  You *must* provide an `altText` for `<Avatar />, <Pill.Avatar />, <Expandable.Avatar />` to ensure proper accessibility. Our examples have been updated to reflect this change.
---
`/modules/react/avatar/lib/Avatar.tsx`
=> fix: Remove default altText for Avatar

modules/react/text-input/lib/InputGroup.tsx
Fixes: #3244 
Fixes some alignment issues between the items rendered inside InputGroup (in the case of a Select component, the dropdown placeholder and the dropdown icon)
Components
---
Select component should render with dropdown icon and placeholder aligned now.
Before:
After:
=> fix: Center InputGroup items

modules/react/switch/lib/Switch.tsx
Fixes: #3249  
This fixes RTL functionality with Switch.
Components
Addresses RTL issue with Switch. 
---
`/modules/react/switch/lib/Switch.tsx`
=> fix: Updates Switch to function with RTL

modules/react/common/lib/utils/mergeProps.ts, modules/react/common/spec/mergeProps.spec.tsx
Ensure `mergeProps` merges class names correctly.
Utils
---
=> fix: Ensure mergeProps merges class names

modules/preview-react/pill/index.ts, modules/preview-react/pill/stories/examples/CustomStyles.tsx
Ensure stencils are exported correctly from Pill
Components
---
=> fix: Ensure stencils are exported for Pill

modules/docs/mdx/style-props/examples/Background.tsx, modules/docs/mdx/style-props/examples/Border.tsx, modules/docs/mdx/style-props/examples/Color.tsx, modules/docs/mdx/style-props/examples/Depth.tsx, modules/docs/mdx/style-props/examples/Position.tsx, modules/docs/mdx/style-props/examples/Space.tsx, modules/preview-react/loading-sparkles/stories/examples/Basic.tsx, modules/react/expandable/stories/examples/Avatar.tsx
Remove React fragments if React isn't imported.
Components
---
=> fix: Remove fragments if React isn't imported

modules/react/tabs/lib/TabsList.tsx
Update the logic around the Tab list fade effect when scrolling with a touch device. The original logic applied a fade effect only when touch-scrolling and only in the direction of the scroll. The original intent was to apply a fade to indicate where content was being overflowed. The update adds scroll detection logic and applies a fade only to directions that can be scrolled to.
Fixes: #3377 
Components
---
[Scroll Fade.webm](https://github.com/user-attachments/assets/9b3edc21-3233-4a77-9b8f-08e29d247e78)
=> fix(tabs): Apply fade more appropriately for mobile

modules/labs-react/package.json, modules/preview-react/package.json, modules/react/package.json
Fixed type dependency version
Infrastructure
=> chore: Fix packages versions

modules/react/avatar/stories/avatar/Avatar.mdx, modules/react/avatar/stories/avatar/examples/CustomStyles.tsx, modules/react/avatar/stories/avatar/examples/LazyLoad.tsx, modules/react/badge/stories/examples/Basic.tsx, modules/react/badge/stories/examples/CustomLimit.tsx, modules/react/badge/stories/examples/NotificationBadge.tsx
Fixes issues with the Avatar and Badge docs/examples to work with the Canvas Site.
Documentation
---
=> fix: Fix docs and examples for Avatar and Badge

modules/styling/stories/mdx/Overview.mdx, modules/styling/stories/mdx/Stencils.mdx, modules/styling/stories/mdx/Utilities.mdx
Fixes styling docs so they can be properly consumed by the Canvas Site.
Documentation
---
=> fix: Fix styling docs to be compatible with site

modules/codemod/index.js, modules/docs/mdx/tokens/TokenMigrationCodemod.mdx
Updated installation steps for migration codemod
Documentation
=> docs: Update codemod installation script

modules/docs/package.json, modules/labs-react/package.json, modules/labs-react/search-form/lib/SearchForm.tsx, modules/preview-react/multi-select/lib/MultiSelectInput.tsx, modules/preview-react/package.json, modules/react/badge/lib/CountBadge.tsx, modules/react/button/lib/ToolbarDropdownButton.tsx, modules/react/button/lib/ToolbarIconButton.tsx, modules/react/expandable/lib/ExpandableContent.tsx, modules/react/expandable/lib/ExpandableTarget.tsx, modules/react/package.json, modules/react/tabs/lib/TabsItem.tsx, modules/styling-transform/package.json, modules/styling/package.json, package.json, yarn.lock
Fixes: #3431
Update tokens alpha to 11
Infrastructure
=> feat: Update tokens to latest alpha

modules/docs/mdx/14.0-UPGRADE-GUIDE.mdx, modules/react/breadcrumbs/lib/BreadcrumbsLink.tsx
Fixes: #3362 
The `Breadcrumbs` component has been updated to use newest tokens as alignment with new brand direction. Underline styles has been removed from `Breadcrumbs.Link`.
Components
The `Breadcrumbs` component has been updated to use newest tokens as alignment with new brand direction. The component uses the `standAlone` variant which removes the underline styles of the link. This change follows our usage guidance that links when used outside the context of body text, should not have an underline.
---
=> feat: Rebrand Breadcrumbs

modules/react/collection/lib/useListRenderItem.tsx
Reset the context when registering items. Virtualization was bleeding into children when a dynamic collection had a static collection and the parent had virtualization. By wrapping the children in the context provider and reseting the value, we avoid virtualization bleeding into children when a static API is used.
Components
---
=> fix: Reset context when registering items in virtual list and static API is used

modules/react/common/lib/theming/README.md
Minor doc fixes.
Documentation
---
=> fix: Minor change to trigger canary

modules/react/checkbox/lib/CheckboxInput.tsx, modules/react/common/lib/styles/focusRing.ts, modules/react/radio/lib/Radio.tsx
We changes `createStencil` to accept `CSSObjectWithVars`. `focusRing` still returned `CSSObject` with caused a conflict between the type. By removing the return type of `focusRing` we let typescript infer the type.
Utilities.
`focusRing` returns `boxShadow`. You can't define two properties of the same type on a styled object.
---
=> fix: Let typescript infer type from focusRing

modules/react/modal/lib/ModalOverlay.tsx, modules/react/modal/stories/testing.stories.tsx
Fixes RTL for modals
Components
---
=> fix(modal): Fix RTL modals

modules/docs/mdx/14.0-UPGRADE-GUIDE.mdx, modules/docs/mdx/tokens/TokenMigrationOverview.mdx
Fixes: #1234 
Documentation
---
=> docs: Fix llm filenames

cypress/support/component.ts, package.json, yarn.lock
We've been seeing a chunk load error that's mentioned in this issue: https://github.com/cypress-io/cypress/pull/31588. Gonna see if updating cypress to 14.5.0 will fix the issue?
Infrastructure
---
=> chore: Update cypress to v14

modules/docs/lib/stackblitzFiles/packageJSONFile.ts
Update stackblitz package version to include latest tokens
Documentation
---
=> fix: Update token version number for stackblitz files

modules/react/collection/lib/useListItemRegister.tsx
Fixes: https://github.com/Workday/canvas-kit/issues/3529
Properly set `aria-setsize` based on the total `options.count` of the virtual list.
Components
---
=> fix: Properly set aria-setsize to total count of virtual items
